### ISSUE TITLE
Attempt to do a manual pairing and found a bug instead.

### ISSUE THREAD

**Issue by ChengyiP** [nurikk/z2m-frontend#1006]
### What happened?

I was trying to pair a new Tuya motion sensor but to no avail. So i attempted to do a new devices pairing with instruction from this page (https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html#instructions) However, a bug found page poped up.. 
[initialState.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/7459303/initialState.json.zip)

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: http://192.168.86.35:8123/api/hassio_ingress/R2CMbxUyyK2j-5h7uHThhvhJ7p-EgQaW2m1oKoeqhpI/#/device/0x00124b001c86d2c2/exposes
**Previous url**: http://192.168.86.35:8123/45df7312_zigbee2mqtt


**Error type**: TypeError
**Error message**: Cannot read properties of null (reading 'endpoint')



TypeError: Cannot read properties of null (reading 'endpoint')
    at http://192.168.86.35:8123/api/hassio_ingress/R2CMbxUyyK2j-5h7uHThhvhJ7p-EgQaW2m1oKoeqhpI/main.90518dbdda1ba18108b9.js:2623:95
    at arrayAggregator (http://192.168.86.35:8123/api/hassio_ingress/R2CMbxUyyK2j-5h7uHThhvhJ7p-EgQaW2m1oKoeqhpI/scripts/vendor.ea7989ca51c5d50873f3.js:59094:32)
    at http://192.168.86.35:8123/api/hassio_ingress/R2CMbxUyyK2j-5h7uHThhvhJ7p-EgQaW2m1oKoeqhpI/scripts/vendor.ea7989ca51c5d50873f3.js:62200:12
    at Composite.render (http://192.168.86.35:8123/api/hassio_ingress/R2CMbxUyyK2j-5h7uHThhvhJ7p-EgQaW2m1oKoeqhpI/main.90518dbdda1ba18108b9.js:2623:54)
    at qi (http://192.168.86.35:8123/api/hassio_ingress/R2CMbxUyyK2j-5h7uHThhvhJ7p-EgQaW2m1oKoeqhpI/scripts/vendor.ea7989ca51c5d50873f3.js:70234:188)
    at pi (http://192.168.86.35:8123/api/hassio_ingress/R2CMbxUyyK2j-5h7uHThhvhJ7p-EgQaW2m1oKoeqhpI/scripts/vendor.ea7989ca51c5d50873f3.js:70233:173)
    at ck (http://192.168.86.35:8123/api/hassio_ingress/R2CMbxUyyK2j-5h7uHThhvhJ7p-EgQaW2m1oKoeqhpI/scripts/vendor.ea7989ca51c5d50873f3.js:70316:427)
    at bk (http://192.168.86.35:8123/api/hassio_ingress/R2CMbxUyyK2j-5h7uHThhvhJ7p-EgQaW2m1oKoeqhpI/scripts/vendor.ea7989ca51c5d50873f3.js:70297:347)
    at ak (http://192.168.86.35:8123/api/hassio_ingress/R2CMbxUyyK2j-5h7uHThhvhJ7p-EgQaW2m1oKoeqhpI/scripts/vendor.ea7989ca51c5d50873f3.js:70297:278)
    at Tj (http://192.168.86.35:8123/api/hassio_ingress/R2CMbxUyyK2j-5h7uHThhvhJ7p-EgQaW2m1oKoeqhpI/scripts/vendor.ea7989ca51c5d50873f3.js:70297:138)
```

### Did you donwload state.json.zip?

I will attach state.json.zip

**Comment by nurikk** [comment]
Hi, one of your converters exposes null as feature, try to check your `TS0202.js`

<img width="278" alt="Screenshot 2021-11-13 at 12 30 43 PM" src="https://user-images.githubusercontent.com/1525421/141605685-fc2d1b46-8a8f-4d38-b5d9-5994a4aa27b7.png">
