### ISSUE TITLE
Add a non supported device to an existing group

### ISSUE THREAD

**Issue by Tetmd57** [nurikk/z2m-frontend#1033]
### What happened?

After I added a device not supported to an existing group I had "Hello, you've found a bug. Congratulations!" message
When I go back to the group list and click on the group with the device not supported I had the same message.

The device not supported below:
![image](https://user-images.githubusercontent.com/61701809/141196874-9df10d72-6dad-4646-bf8b-587f4ca24539.png)

The ScreenShot of the bug message below:
![image](https://user-images.githubusercontent.com/61701809/141196709-a797789d-aa3b-40ff-9037-f4582a89c767.png)

The state.json.zip file below:
[initialState.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/7516045/initialState.json.zip)

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: http://10.0.0.37:8080/#/group/1
**Previous url**: http://10.0.0.37/


**Error type**: TypeError
**Error message**: Cannot destructure property 'exposes' of 'device.definition' as it is null.



TypeError: Cannot destructure property 'exposes' of 'device.definition' as it is null.
    at DeviceFooter (http://10.0.0.37:8080/main.90518dbdda1ba18108b9.js:4489:13)
    at Ch (http://10.0.0.37:8080/scripts/vendor.ea7989ca51c5d50873f3.js:70204:137)
    at ck (http://10.0.0.37:8080/scripts/vendor.ea7989ca51c5d50873f3.js:70314:460)
    at bk (http://10.0.0.37:8080/scripts/vendor.ea7989ca51c5d50873f3.js:70297:347)
    at ak (http://10.0.0.37:8080/scripts/vendor.ea7989ca51c5d50873f3.js:70297:278)
    at Tj (http://10.0.0.37:8080/scripts/vendor.ea7989ca51c5d50873f3.js:70297:138)
    at Lj (http://10.0.0.37:8080/scripts/vendor.ea7989ca51c5d50873f3.js:70290:163)
    at http://10.0.0.37:8080/scripts/vendor.ea7989ca51c5d50873f3.js:70170:115
    at exports.unstable_runWithPriority (http://10.0.0.37:8080/scripts/vendor.ea7989ca51c5d50873f3.js:73463:343)
    at gg (http://10.0.0.37:8080/scripts/vendor.ea7989ca51c5d50873f3.js:70169:325)
```

### Did you donwload state.json.zip?

I will attach state.json.zip

**Comment by nurikk** [comment]
Fixed, thanks
