### ISSUE TITLE
An error occurred when I clicked "group" of z2m frontend

### ISSUE THREAD

**Issue by ratunee-me** [nurikk/z2m-frontend#1036]
### What happened?

An error occurred when I clicked "group" of z2m frontend!!

[initialState.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/7525764/initialState.json.zip)

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: https://z2m.ratunee.com/#/groups
**Previous url**: 


**Error type**: TypeError
**Error message**: Cannot read properties of undefined (reading 'length')



TypeError: Cannot read properties of undefined (reading 'length')
    at https://z2m.ratunee.com/main.90518dbdda1ba18108b9.js:4077:70
    at Array.map (<anonymous>)
    at GroupsPage.renderGroups (https://z2m.ratunee.com/main.90518dbdda1ba18108b9.js:4071:63)
    at GroupsPage.render (https://z2m.ratunee.com/main.90518dbdda1ba18108b9.js:4087:18)
    at qi (https://z2m.ratunee.com/scripts/vendor.ea7989ca51c5d50873f3.js:70234:188)
    at pi (https://z2m.ratunee.com/scripts/vendor.ea7989ca51c5d50873f3.js:70233:173)
    at ck (https://z2m.ratunee.com/scripts/vendor.ea7989ca51c5d50873f3.js:70316:427)
    at bk (https://z2m.ratunee.com/scripts/vendor.ea7989ca51c5d50873f3.js:70297:347)
    at ak (https://z2m.ratunee.com/scripts/vendor.ea7989ca51c5d50873f3.js:70297:278)
    at Tj (https://z2m.ratunee.com/scripts/vendor.ea7989ca51c5d50873f3.js:70297:138)
```

### Did you donwload state.json.zip?

I will attach state.json.zip

**Comment by nurikk** [comment]
Hi, you're using miss matching frontend and z2m version, did you install something by your self?
