### ISSUE TITLE
Adding a non initialized light to a group crashes

### ISSUE THREAD

**Issue by ahd71** [nurikk/z2m-frontend#1055]
### What happened?

Created a new group, added a handful of lights, one of them were not yet initiated correctly but was possible to choose so I did. Then i reached the "bug page" and now I cannot open that group (no problem; I can recreate it; or make sure the interview completes and everything will probably be just fine),

Recommendation: If easy to not include entities that isn't properly initialized in the drop down of lights to add to the group, let's filter them out to avoid the scenario.

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: http://192.168.1.5:8080/#/group/4
**Previous url**: 


**Error type**: TypeError
**Error message**: Cannot destructure property 'exposes' of 'device.definition' as it is null.



TypeError: Cannot destructure property 'exposes' of 'device.definition' as it is null.
    at DeviceFooter (http://192.168.1.5:8080/main.90518dbdda1ba18108b9.js:4489:13)
    at Ch (http://192.168.1.5:8080/scripts/vendor.ea7989ca51c5d50873f3.js:70204:137)
    at ck (http://192.168.1.5:8080/scripts/vendor.ea7989ca51c5d50873f3.js:70314:460)
    at bk (http://192.168.1.5:8080/scripts/vendor.ea7989ca51c5d50873f3.js:70297:347)
    at ak (http://192.168.1.5:8080/scripts/vendor.ea7989ca51c5d50873f3.js:70297:278)
    at Tj (http://192.168.1.5:8080/scripts/vendor.ea7989ca51c5d50873f3.js:70297:138)
    at Lj (http://192.168.1.5:8080/scripts/vendor.ea7989ca51c5d50873f3.js:70290:163)
    at http://192.168.1.5:8080/scripts/vendor.ea7989ca51c5d50873f3.js:70170:115
    at exports.unstable_runWithPriority (http://192.168.1.5:8080/scripts/vendor.ea7989ca51c5d50873f3.js:73463:343)
    at gg (http://192.168.1.5:8080/scripts/vendor.ea7989ca51c5d50873f3.js:70169:325)
```

### Did you donwload state.json.zip?

I will not attach state.json.zip

**Comment by ahd71** [comment]
I can confirm that after the interview it was as expected possible to manage to light group again.
