### ISSUE TITLE
TS0601_air_quality_sensor - settings(specific) error

### ISSUE THREAD

**Issue by Nunak** [nurikk/z2m-frontend#1058]
### What happened?

When I click on settings(specific) for this sensor(TS0601_air_quality_sensor) I am getting this error.

[
[initialState.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/7574270/initialState.json.zip)
](url)
![error1](https://user-images.githubusercontent.com/9319841/142721380-d37278ff-2038-415f-952a-896efc0a5dfc.PNG)

Could you please solve this error?

Many thanks
Karel Peran - Nunak

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: http://rpi-006.nuni.cz:8081/#/device/0x540f57fffe975342/settings-specific
**Previous url**: 


**Error type**: TypeError
**Error message**: Cannot read properties of undefined (reading 'formaldehyd_calibration')



TypeError: Cannot read properties of undefined (reading 'formaldehyd_calibration')
    at Numeric (http://rpi-006.nuni.cz:8081/main.90518dbdda1ba18108b9.js:2451:136)
    at Ch (http://rpi-006.nuni.cz:8081/scripts/vendor.ea7989ca51c5d50873f3.js:70204:137)
    at ck (http://rpi-006.nuni.cz:8081/scripts/vendor.ea7989ca51c5d50873f3.js:70314:460)
    at bk (http://rpi-006.nuni.cz:8081/scripts/vendor.ea7989ca51c5d50873f3.js:70297:347)
    at ak (http://rpi-006.nuni.cz:8081/scripts/vendor.ea7989ca51c5d50873f3.js:70297:278)
    at Tj (http://rpi-006.nuni.cz:8081/scripts/vendor.ea7989ca51c5d50873f3.js:70297:138)
    at Lj (http://rpi-006.nuni.cz:8081/scripts/vendor.ea7989ca51c5d50873f3.js:70290:163)
    at http://rpi-006.nuni.cz:8081/scripts/vendor.ea7989ca51c5d50873f3.js:70170:115
    at exports.unstable_runWithPriority (http://rpi-006.nuni.cz:8081/scripts/vendor.ea7989ca51c5d50873f3.js:73463:343)
    at gg (http://rpi-006.nuni.cz:8081/scripts/vendor.ea7989ca51c5d50873f3.js:70169:325)
```

### Did you donwload state.json.zip?

I will attach state.json.zip

**Comment by nurikk** [comment]
Thanks, fixed
