### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by brucehead** [nurikk/z2m-frontend#1095]
### What happened?

Hello, you've found a bug. Congratulations!
Calm down
Click here, and save this file
Raise a github issue, attach previously downloaded file
Take a screenshot of this page and attach to the issue
In the github issue write detailed description for the issue, how this happened? Steps to reproduce
TypeError
Cannot read properties of undefined (reading 'temperature_calibration')
TypeError: Cannot read properties of undefined (reading 'temperature_calibration')
    at Numeric (http://192.168.0.10:8080/main.90518dbdda1ba18108b9.js:2451:136)
    at Ch (http://192.168.0.10:8080/scripts/vendor.ea7989ca51c5d50873f3.js:70204:137)
    at ck (http://192.168.0.10:8080/scripts/vendor.ea7989ca51c5d50873f3.js:70314:460)
    at bk (http://192.168.0.10:8080/scripts/vendor.ea7989ca51c5d50873f3.js:70297:347)
    at ak (http://192.168.0.10:8080/scripts/vendor.ea7989ca51c5d50873f3.js:70297:278)
    at Tj (http://192.168.0.10:8080/scripts/vendor.ea7989ca51c5d50873f3.js:70297:138)
    at Lj (http://192.168.0.10:8080/scripts/vendor.ea7989ca51c5d50873f3.js:70290:163)
    at http://192.168.0.10:8080/scripts/vendor.ea7989ca51c5d50873f3.js:70170:115
    at exports.unstable_runWithPriority (http://192.168.0.10:8080/scripts/vendor.ea7989ca51c5d50873f3.js:73463:343)
    at gg (http://192.168.0.10:8080/scripts/vendor.ea7989ca51c5d50873f3.js:70169:325)

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: http://192.168.0.10:8080/#/device/0x00158d0006a07c89/settings-specific
**Previous url**: 


**Error type**: TypeError
**Error message**: Cannot read properties of undefined (reading 'temperature_calibration')



TypeError: Cannot read properties of undefined (reading 'temperature_calibration')
    at Numeric (http://192.168.0.10:8080/main.90518dbdda1ba18108b9.js:2451:136)
    at Ch (http://192.168.0.10:8080/scripts/vendor.ea7989ca51c5d50873f3.js:70204:137)
    at ck (http://192.168.0.10:8080/scripts/vendor.ea7989ca51c5d50873f3.js:70314:460)
    at bk (http://192.168.0.10:8080/scripts/vendor.ea7989ca51c5d50873f3.js:70297:347)
    at ak (http://192.168.0.10:8080/scripts/vendor.ea7989ca51c5d50873f3.js:70297:278)
    at Tj (http://192.168.0.10:8080/scripts/vendor.ea7989ca51c5d50873f3.js:70297:138)
    at Lj (http://192.168.0.10:8080/scripts/vendor.ea7989ca51c5d50873f3.js:70290:163)
    at http://192.168.0.10:8080/scripts/vendor.ea7989ca51c5d50873f3.js:70170:115
    at exports.unstable_runWithPriority (http://192.168.0.10:8080/scripts/vendor.ea7989ca51c5d50873f3.js:73463:343)
    at gg (http://192.168.0.10:8080/scripts/vendor.ea7989ca51c5d50873f3.js:70169:325)
```

### Did you donwload state.json.zip?

I will attach state.json.zip

**Comment by brucehead** [comment]
[initialState.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/7591204/initialState.json.zip)

**Comment by nurikk** [comment]
Can you try latest dev branch?

**Comment by brucehead** [comment]
As you can see in the attachment "initialState.json.zip":
coordinator "revision": 20201127
zigbee  "version": "1.22.0"
These are the latest versions, right?

**Comment by nurikk** [comment]
No, you're using release version. This issue was fixed in dev

**Comment by nurikk** [comment]
Hi, try to switch to the latest dev branch

https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html#switch-to-the-dev-branch

**Comment by brucehead** [comment]
Hi, after updating to version 1.24.0 :
From dashboard 1.24.0
From broker 1.22.0-dev
Can you help me resolve this inconsistency?

An image to explain:
[image: image.jpg]

Thanks for your help


Il giorno gio 25 nov 2021 alle ore 14:52 John Doe ***@***.***>
ha scritto:
