### ISSUE TITLE
Cliccked "settings specific", --> please file a bug report :)

### ISSUE THREAD

**Issue by jla1710** [nurikk/z2m-frontend#1107]
### What happened?

I don't know what to expect
![bug](https://user-images.githubusercontent.com/32166939/143779622-522ef35d-2100-41f8-a994-b37d83ed7392.PNG)
[initialState.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/7614040/initialState.json.zip)

t

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: http://192.168.1.101:8123/api/hassio_ingress/ixqH7h9czi8Lee5oSPVKrV8kOdIPXsCb8NY-2NzlHts/#/device/0x5c0272fffec4bc00/settings-specific
**Previous url**: http://192.168.1.101:8123/45df7312_zigbee2mqtt


**Error type**: TypeError
**Error message**: Cannot read properties of undefined (reading 'humidity_calibration')



TypeError: Cannot read properties of undefined (reading 'humidity_calibration')
    at Numeric (http://192.168.1.101:8123/api/hassio_ingress/ixqH7h9czi8Lee5oSPVKrV8kOdIPXsCb8NY-2NzlHts/main.90518dbdda1ba18108b9.js:2451:136)
    at Ch (http://192.168.1.101:8123/api/hassio_ingress/ixqH7h9czi8Lee5oSPVKrV8kOdIPXsCb8NY-2NzlHts/scripts/vendor.ea7989ca51c5d50873f3.js:70204:137)
    at ck (http://192.168.1.101:8123/api/hassio_ingress/ixqH7h9czi8Lee5oSPVKrV8kOdIPXsCb8NY-2NzlHts/scripts/vendor.ea7989ca51c5d50873f3.js:70314:460)
    at bk (http://192.168.1.101:8123/api/hassio_ingress/ixqH7h9czi8Lee5oSPVKrV8kOdIPXsCb8NY-2NzlHts/scripts/vendor.ea7989ca51c5d50873f3.js:70297:347)
    at ak (http://192.168.1.101:8123/api/hassio_ingress/ixqH7h9czi8Lee5oSPVKrV8kOdIPXsCb8NY-2NzlHts/scripts/vendor.ea7989ca51c5d50873f3.js:70297:278)
    at Tj (http://192.168.1.101:8123/api/hassio_ingress/ixqH7h9czi8Lee5oSPVKrV8kOdIPXsCb8NY-2NzlHts/scripts/vendor.ea7989ca51c5d50873f3.js:70297:138)
    at Lj (http://192.168.1.101:8123/api/hassio_ingress/ixqH7h9czi8Lee5oSPVKrV8kOdIPXsCb8NY-2NzlHts/scripts/vendor.ea7989ca51c5d50873f3.js:70290:163)
    at http://192.168.1.101:8123/api/hassio_ingress/ixqH7h9czi8Lee5oSPVKrV8kOdIPXsCb8NY-2NzlHts/scripts/vendor.ea7989ca51c5d50873f3.js:70170:115
    at exports.unstable_runWithPriority (http://192.168.1.101:8123/api/hassio_ingress/ixqH7h9czi8Lee5oSPVKrV8kOdIPXsCb8NY-2NzlHts/scripts/vendor.ea7989ca51c5d50873f3.js:73463:343)
    at gg (http://192.168.1.101:8123/api/hassio_ingress/ixqH7h9czi8Lee5oSPVKrV8kOdIPXsCb8NY-2NzlHts/scripts/vendor.ea7989ca51c5d50873f3.js:70169:325)
```

### Did you donwload state.json.zip?

I will attach state.json.zip

**Comment by nurikk** [comment]
Hi, try to switch to the latest dev branch

https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html#switch-to-the-dev-branch
