### ISSUE TITLE
ZM25TQ motor speed change failed

### ISSUE THREAD

**Issue by roman-76** [nurikk/z2m-frontend#1169]
### What happened?

I've added tubular zigbee motor Tuya ZM25TQ and tried to change motor speed on Exposes tab
![image](https://user-images.githubusercontent.com/6941230/145932070-3bda01a2-3372-423e-88f6-7736d8dbfa79.png)
there were errors poping up and when I went to settings(specific) tab I've got an error
![image](https://user-images.githubusercontent.com/6941230/145931957-4b8fdf59-c021-40af-8712-892d2e367331.png)
[state.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/7708646/state.json.zip)
[initialState.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/7708648/initialState.json.zip)

### What browsers are you seeing the problem on?

Safari, Microsoft Edge

### Relevant stacktrace

```shell
**Current url**: http://phome-ds:8088/#/device/0xb4e3f9fffe7da5ad/settings-specific
**Previous url**: 


**Error type**: TypeError
**Error message**: Cannot read properties of undefined (reading 'invert_cover')



TypeError: Cannot read properties of undefined (reading 'invert_cover')
    at Binary (http://phome-ds:8088/main.90518dbdda1ba18108b9.js:2263:128)
    at Ch (http://phome-ds:8088/scripts/vendor.ea7989ca51c5d50873f3.js:70204:137)
    at ck (http://phome-ds:8088/scripts/vendor.ea7989ca51c5d50873f3.js:70314:460)
    at bk (http://phome-ds:8088/scripts/vendor.ea7989ca51c5d50873f3.js:70297:347)
    at ak (http://phome-ds:8088/scripts/vendor.ea7989ca51c5d50873f3.js:70297:278)
    at Tj (http://phome-ds:8088/scripts/vendor.ea7989ca51c5d50873f3.js:70297:138)
    at Lj (http://phome-ds:8088/scripts/vendor.ea7989ca51c5d50873f3.js:70290:163)
    at http://phome-ds:8088/scripts/vendor.ea7989ca51c5d50873f3.js:70170:115
    at exports.unstable_runWithPriority (http://phome-ds:8088/scripts/vendor.ea7989ca51c5d50873f3.js:73463:343)
    at gg (http://phome-ds:8088/scripts/vendor.ea7989ca51c5d50873f3.js:70169:325)
```

### Did you donwload state.json.zip?

I will attach state.json.zip

**Comment by roman-76** [comment]
BTW, it was recognized as TS0601 that looks differently
![image](https://user-images.githubusercontent.com/6941230/145932727-59a39710-a175-4c41-a9da-f69f0705e490.png)

**Comment by nurikk** [comment]
Hi, try to switch to the latest dev branch

https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html#switch-to-the-dev-branch

**Comment by roman-76** [comment]
Just wanted to confirm that switching to the latest dev branch solved the issue. Sorry for the late response.
