### ISSUE TITLE
NotFoundError Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by thunguyenba** [nurikk/z2m-frontend#1195]
### What happened?

Bug[](url
[initialState.json (1).zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/7763642/initialState.json.1.zip)
)

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: http://thunguyenba.duckdns.org:8123/api/hassio_ingress/DJSNbui8zwzQpOqqplyKtfC1npaIRbcpspX-Ks_otMU/#/
**Previous url**: http://thunguyenba.duckdns.org:8123/45df7312_zigbee2mqtt


**Error type**: NotFoundError
**Error message**: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.



Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at cj (http://thunguyenba.duckdns.org:8123/api/hassio_ingress/DJSNbui8zwzQpOqqplyKtfC1npaIRbcpspX-Ks_otMU/scripts/vendor.49fee1be1555be7ec8f9.js:84123:64)
    at dk (http://thunguyenba.duckdns.org:8123/api/hassio_ingress/DJSNbui8zwzQpOqqplyKtfC1npaIRbcpspX-Ks_otMU/scripts/vendor.49fee1be1555be7ec8f9.js:84148:468)
    at exports.unstable_runWithPriority (http://thunguyenba.duckdns.org:8123/api/hassio_ingress/DJSNbui8zwzQpOqqplyKtfC1npaIRbcpspX-Ks_otMU/scripts/vendor.49fee1be1555be7ec8f9.js:88082:343)
    at gg (http://thunguyenba.duckdns.org:8123/api/hassio_ingress/DJSNbui8zwzQpOqqplyKtfC1npaIRbcpspX-Ks_otMU/scripts/vendor.49fee1be1555be7ec8f9.js:84014:325)
    at Uj (http://thunguyenba.duckdns.org:8123/api/hassio_ingress/DJSNbui8zwzQpOqqplyKtfC1npaIRbcpspX-Ks_otMU/scripts/vendor.49fee1be1555be7ec8f9.js:84144:279)
    at Lj (http://thunguyenba.duckdns.org:8123/api/hassio_ingress/DJSNbui8zwzQpOqqplyKtfC1npaIRbcpspX-Ks_otMU/scripts/vendor.49fee1be1555be7ec8f9.js:84135:371)
    at http://thunguyenba.duckdns.org:8123/api/hassio_ingress/DJSNbui8zwzQpOqqplyKtfC1npaIRbcpspX-Ks_otMU/scripts/vendor.49fee1be1555be7ec8f9.js:84015:115
    at exports.unstable_runWithPriority (http://thunguyenba.duckdns.org:8123/api/hassio_ingress/DJSNbui8zwzQpOqqplyKtfC1npaIRbcpspX-Ks_otMU/scripts/vendor.49fee1be1555be7ec8f9.js:88082:343)
    at gg (http://thunguyenba.duckdns.org:8123/api/hassio_ingress/DJSNbui8zwzQpOqqplyKtfC1npaIRbcpspX-Ks_otMU/scripts/vendor.49fee1be1555be7ec8f9.js:84014:325)
    at jg (http://thunguyenba.duckdns.org:8123/api/hassio_ingress/DJSNbui8zwzQpOqqplyKtfC1npaIRbcpspX-Ks_otMU/scripts/vendor.49fee1be1555be7ec8f9.js:84015:61)
```

### Did you donwload state.json.zip?

I will attach state.json.zip

**Comment by nurikk** [comment]
Hi, try to switch to the latest dev branch

https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html#switch-to-the-dev-branch

**Comment by jobsidi** [comment]
tested with dev branch. It not helps. I have the same. It occurs when i click "permit join" when trying to add device. z2m subwindow of HA starts refreshing, a device appears as unknow before it detected by HA as normal device and z2m crashes at some moment.
