### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by rwb196884** [nurikk/z2m-frontend#1278]
How do you install this?

I'm guessing it's something like
```
# git clone https://github.com/nurikk/zigbee2mqtt-frontend.git
# cd zigbee2mqtt-frontend
# npm install
```
And then fuck knows what as `npm run start` doesn't work:
```
# npm run start
npm WARN npm npm does not support Node.js v10.24.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/

> zigbee2mqtt-frontend@0.6.69 start /root/zigbee2mqtt-frontend
> concurrently 'npm run start:ws' 'npm run start:dev'

[0] npm WARN npm npm does not support Node.js v10.24.0
[0] npm WARN npm You should probably upgrade to a newer version of node as we
[0] npm WARN npm can't make any promises that npm will work with this version.
[0] npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
[0] npm WARN npm You can find the latest version at https://nodejs.org/
[1] npm WARN npm npm does not support Node.js v10.24.0
[1] npm WARN npm You should probably upgrade to a newer version of node as we
[1] npm WARN npm can't make any promises that npm will work with this version.
[1] npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
[1] npm WARN npm You can find the latest version at https://nodejs.org/
[0]
[0] > zigbee2mqtt-frontend@0.6.69 start:ws /root/zigbee2mqtt-frontend
[0] > node ws.js
[0]
[1]
[1] > zigbee2mqtt-frontend@0.6.69 start:dev /root/zigbee2mqtt-frontend
[1] > webpack serve --config ./webpack.config.js --mode development
[1]
[1] == Development mode
[1] <i> [webpack-dev-server] [HPM] Proxy created: /api  -> ws://localhost:8579
[1] [webpack-cli] /root/zigbee2mqtt-frontend/node_modules/webpack-dev-server/lib/servers/WebsocketServer.js:10
[1]   static heartbeatInterval = 1000;
[1]                            ^
[1]
[1] SyntaxError: Unexpected token =
[1]     at Module._compile (internal/modules/cjs/loader.js:723:23)
[1]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
[1]     at Module.load (internal/modules/cjs/loader.js:653:32)
[1]     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
[1]     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[1]     at Module.require (internal/modules/cjs/loader.js:692:17)
[1]     at require (internal/modules/cjs/helpers.js:25:18)
[1]     at Server.getServerTransport (/root/zigbee2mqtt-frontend/node_modules/webpack-dev-server/lib/Server.js:1191:28)
[1]     at Server.createWebSocketServer (/root/zigbee2mqtt-frontend/node_modules/webpack-dev-server/lib/Server.js:1757:38)
[1]     at Server.start (/root/zigbee2mqtt-frontend/node_modules/webpack-dev-server/lib/Server.js:2305:12)
[1] npm ERR! code ELIFECYCLE
[1] npm ERR! errno 2
[1] npm ERR! zigbee2mqtt-frontend@0.6.69 start:dev: `webpack serve --config ./webpack.config.js --mode development`
[1] npm ERR! Exit status 2
[1] npm ERR!
[1] npm ERR! Failed at the zigbee2mqtt-frontend@0.6.69 start:dev script.
[1] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[1]
[1] npm ERR! A complete log of this run can be found in:
[1] npm ERR!     /root/.npm/_logs/2022-01-25T22_04_21_667Z-debug.log
[1] npm run start:dev exited with code 2
#
```
and then it just hangs.
I was expecting to configure it with a port and then look there in by browser?

I saw something about appending to `zigbee2mqtt/data/configuration.yaml` the following and restart it:
```
frontend:
  port:8009
```
but it's unclear how that's relevant of how to notify `zigbee2mqtt-frontend` to use port `8009`.

Then I'll be wanting to create a `systemd` service for it by creating `/etc/systemd/system/zigbee2mqtt-frontend.service` and
```
# mv /root/zigbee2mqtt-frontend /opt/zigbee2mqtt-frontend
# systemctl daemon-reload
# systemctl start zigbee2mqtt-frontend
# systemctl enable zigbee2mqtt-frontend
```

**Comment by nurikk** [comment]
Hello, what are you trying to achieve?

**Comment by rwb196884** [comment]
I have `zigbee2mqtt` running and was under the impression that this was a web-based UI for it that could help me see how it's configured and what it's doing. Therefore I wanted to install and run it. Is this not so?

**Comment by nurikk** [comment]
You don't need to run separately, frontend is bundled in your z2m installation. Make sure that you're using latest version and enable fronted in your configuration.yaml

More details [here](https://www.zigbee2mqtt.io/guide/configuration/frontend.html)

**Comment by rwb196884** [comment]
So it is!
Thank you :)
