### ISSUE TITLE
Bug Changement de langue

### ISSUE THREAD

**Issue by medline2c** [nurikk/z2m-frontend#1324]
### What happened?

J'ai cliqué sur l'icône de langue pour changer la langue de Anglais vers Français

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: http://192.168.1.100:8080/#/
**Previous url**: http://192.168.1.100/


**Error type**: NotFoundError
**Error message**: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.



Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at xs (http://192.168.1.100:8080/scripts/vendor.0bec3bffaceffb8afea6.js:2:1084236)
    at Ou (http://192.168.1.100:8080/scripts/vendor.0bec3bffaceffb8afea6.js:2:1095966)
    at t.unstable_runWithPriority (http://192.168.1.100:8080/scripts/vendor.0bec3bffaceffb8afea6.js:2:1221947)
    at Vi (http://192.168.1.100:8080/scripts/vendor.0bec3bffaceffb8afea6.js:2:1039411)
    at Au (http://192.168.1.100:8080/scripts/vendor.0bec3bffaceffb8afea6.js:2:1093927)
    at gu (http://192.168.1.100:8080/scripts/vendor.0bec3bffaceffb8afea6.js:2:1090038)
    at http://192.168.1.100:8080/scripts/vendor.0bec3bffaceffb8afea6.js:2:1039634
    at t.unstable_runWithPriority (http://192.168.1.100:8080/scripts/vendor.0bec3bffaceffb8afea6.js:2:1221947)
    at Vi (http://192.168.1.100:8080/scripts/vendor.0bec3bffaceffb8afea6.js:2:1039411)
    at qi (http://192.168.1.100:8080/scripts/vendor.0bec3bffaceffb8afea6.js:2:1039579)
```

### Did you download state.json.zip?

I will attach state.json.zip
[initialState.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/8009119/initialState.json.zip)
![Capture d’écran 2022-02-06 002816](https://user-images.githubusercontent.com/71671427/152662502-27aff7b2-430e-4cbf-845e-220936371023.jpg)

**Comment by medline2c** [comment]
Peut-être un indice intéressant : j'avais la traduction automatique activée par le plugin chrome traduction de google... Si je désactive la traduction, le soucis semble ne plus se produire... hasard ou pas, à déterminer...
