### ISSUE TITLE
Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by gitFisherau** [nurikk/z2m-frontend#1325]
### What happened?

It was all working. Not sure what has happen. Most likely it started to crash after I've removed one of the devices. It was a Aqara leakage sensor which was not recognised properly.

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: http://localhost:8081/#/
**Previous url**: http://localhost:8081/


**Error type**: NotFoundError
**Error message**: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.



Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at xs (http://localhost:8081/scripts/vendor.0bec3bffaceffb8afea6.js:2:1084236)
    at Ou (http://localhost:8081/scripts/vendor.0bec3bffaceffb8afea6.js:2:1095966)
    at t.unstable_runWithPriority (http://localhost:8081/scripts/vendor.0bec3bffaceffb8afea6.js:2:1221947)
    at Vi (http://localhost:8081/scripts/vendor.0bec3bffaceffb8afea6.js:2:1039411)
    at Au (http://localhost:8081/scripts/vendor.0bec3bffaceffb8afea6.js:2:1093927)
    at gu (http://localhost:8081/scripts/vendor.0bec3bffaceffb8afea6.js:2:1090038)
    at http://localhost:8081/scripts/vendor.0bec3bffaceffb8afea6.js:2:1039634
    at t.unstable_runWithPriority (http://localhost:8081/scripts/vendor.0bec3bffaceffb8afea6.js:2:1221947)
    at Vi (http://localhost:8081/scripts/vendor.0bec3bffaceffb8afea6.js:2:1039411)
    at qi (http://localhost:8081/scripts/vendor.0bec3bffaceffb8afea6.js:2:1039579)
```
[initialState.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/8010142/initialState.json.zip)

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by terryhonn** [comment]
Also receiving this, attaching initialState.json.zip
[initialState.json (3).zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/8134785/initialState.json.3.zip)
p
