### ISSUE TITLE
New issue trying to get the Heimann HM1RC-2-E remote to work

### ISSUE THREAD

**Issue by akala57** [nurikk/z2m-frontend#1363]
### What happened?

Heimann remote (HM1RC-2-E) still doesn't work.
Im' trying to pair it again. Successfull. However no action in "State", only :
```
{
    "battery": 40,
    "linkquality": 143
}
```
Clicked on "Scene" and always see the bug message.
[initialState.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/8101899/initialState.json.zip)
I'm using Brave borwser [Version 1.35.100 Chromium: 98.0.4758.87 (Build officiel) (64 bits)](https://brave.com/latest/).

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: http://192.168.1.10:8080/#/device/0xec1bbdfffe0fa7f3/scene
**Previous url**: whatever


**Error type**: TypeError
**Error message**: a.scenes is not iterable
TypeError
a.scenes is not iterable
TypeError: a.scenes is not iterable
    at http://192.168.1.10:8080/main.31d06157e871ccd80525.js:1:67752
    at Array.forEach (<anonymous>)
    at Wa (http://192.168.1.10:8080/main.31d06157e871ccd80525.js:1:67716)
    at Za (http://192.168.1.10:8080/main.31d06157e871ccd80525.js:1:66951)
    at aa (http://192.168.1.10:8080/scripts/vendor.0bec3bffaceffb8afea6.js:2:1053712)
    at Vs (http://192.168.1.10:8080/scripts/vendor.0bec3bffaceffb8afea6.js:2:1105761)
    at ku (http://192.168.1.10:8080/scripts/vendor.0bec3bffaceffb8afea6.js:2:1093035)
    at Iu (http://192.168.1.10:8080/scripts/vendor.0bec3bffaceffb8afea6.js:2:1092963)
    at Eu (http://192.168.1.10:8080/scripts/vendor.0bec3bffaceffb8afea6.js:2:1092826)
    at gu (http://192.168.1.10:8080/scripts/vendor.0bec3bffaceffb8afea6.js:2:1089813)


TypeError: a.scenes is not iterable
    at http://192.168.1.10:8080/main.31d06157e871ccd80525.js:1:67752
    at Array.forEach (<anonymous>)
    at Wa (http://192.168.1.10:8080/main.31d06157e871ccd80525.js:1:67716)
    at Za (http://192.168.1.10:8080/main.31d06157e871ccd80525.js:1:66951)
    at aa (http://192.168.1.10:8080/scripts/vendor.0bec3bffaceffb8afea6.js:2:1053712)
    at Vs (http://192.168.1.10:8080/scripts/vendor.0bec3bffaceffb8afea6.js:2:1105761)
    at ku (http://192.168.1.10:8080/scripts/vendor.0bec3bffaceffb8afea6.js:2:1093035)
    at Iu (http://192.168.1.10:8080/scripts/vendor.0bec3bffaceffb8afea6.js:2:1092963)
    at Eu (http://192.168.1.10:8080/scripts/vendor.0bec3bffaceffb8afea6.js:2:1092826)
    at gu (http://192.168.1.10:8080/scripts/vendor.0bec3bffaceffb8afea6.js:2:1089813)
```

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by nurikk** [comment]
Hi, are you using latest dev version? Did you run `npm ci` ?

**Comment by nurikk** [comment]
Fixed
