### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Kresna314** [nurikk/z2m-frontend#1403]
### What happened?

NotFoundError
Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node
[initialState.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/8237597/initialState.json.zip)
.

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

**Error type**: NotFoundError
**Error message**: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at xs (http://192.168.0.87:8123/api/hassio_ingress/VFm_Y9DtqkyAKX4ji-MqvYiKNC_98DJHKFTOEBhB04U/scripts/vendor.955a3db7cc8bf0901cb4.js:2:1108429)
    at Ou (http://192.168.0.87:8123/api/hassio_ingress/VFm_Y9DtqkyAKX4ji-MqvYiKNC_98DJHKFTOEBhB04U/scripts/vendor.955a3db7cc8bf0901cb4.js:2:1120159)
    at t.unstable_runWithPriority (http://192.168.0.87:8123/api/hassio_ingress/VFm_Y9DtqkyAKX4ji-MqvYiKNC_98DJHKFTOEBhB04U/scripts/vendor.955a3db7cc8bf0901cb4.js:2:1239727)
    at Vi (http://192.168.0.87:8123/api/hassio_ingress/VFm_Y9DtqkyAKX4ji-MqvYiKNC_98DJHKFTOEBhB04U/scripts/vendor.955a3db7cc8bf0901cb4.js:2:1063604)
    at Au (http://192.168.0.87:8123/api/hassio_ingress/VFm_Y9DtqkyAKX4ji-MqvYiKNC_98DJHKFTOEBhB04U/scripts/vendor.955a3db7cc8bf0901cb4.js:2:1118120)
    at gu (http://192.168.0.87:8123/api/hassio_ingress/VFm_Y9DtqkyAKX4ji-MqvYiKNC_98DJHKFTOEBhB04U/scripts/vendor.955a3db7cc8bf0901cb4.js:2:1114231)
    at http://192.168.0.87:8123/api/hassio_ingress/VFm_Y9DtqkyAKX4ji-MqvYiKNC_98DJHKFTOEBhB04U/scripts/vendor.955a3db7cc8bf0901cb4.js:2:1063827
    at t.unstable_runWithPriority (http://192.168.0.87:8123/api/hassio_ingress/VFm_Y9DtqkyAKX4ji-MqvYiKNC_98DJHKFTOEBhB04U/scripts/vendor.955a3db7cc8bf0901cb4.js:2:1239727)
    at Vi (http://192.168.0.87:8123/api/hassio_ingress/VFm_Y9DtqkyAKX4ji-MqvYiKNC_98DJHKFTOEBhB04U/scripts/vendor.955a3db7cc8bf0901cb4.js:2:1063604)
    at qi (http://192.168.0.87:8123/api/hassio_ingress/VFm_Y9DtqkyAKX4ji-MqvYiKNC_98DJHKFTOEBhB04U/scripts/vendor.955a3db7cc8bf0901cb4.js:2:1063772)
```


### Did you download state.json.zip?

I will attach state.json.zip

**Comment by nurikk** [comment]
Hi, try to switch to the latest dev branch

https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html#switch-to-the-dev-branch
