### ISSUE TITLE
TS0215_sos 

### ISSUE THREAD

**Issue by wojteksolo** [nurikk/z2m-frontend#1530]
### What happened?

[initialState.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/9312651/initialState.json.zip)
![screenshot](https://user-images.githubusercontent.com/76619236/184259487-3a5ed0ce-dd08-4978-af5a-1dda001716b7.png)

I'm trying to add TuYa TS0215A_sos to Z2M by following the instructions from https://www.zigbee2mqtt.io/advanced/support-new-devices/02_support_new_tuya_devices.html#instructions

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: http://192.168.1.20:8123/api/hassio_ingress/OINwaL3YaFKzcCRR1jYrvOIrODKi0KqPqZ5nFtXMLZU/#/device/0xa4c1381061c6c3c1/exposes
**Previous url**: http://192.168.1.20:8123/45df7312_zigbee2mqtt


**Error type**: TypeError
**Error message**: Cannot read properties of undefined (reading 'length')



TypeError: Cannot read properties of undefined (reading 'length')
    at fKe (http://192.168.1.20:8123/api/hassio_ingress/OINwaL3YaFKzcCRR1jYrvOIrODKi0KqPqZ5nFtXMLZU/assets/index.3f63cdfc.js:85:189284)
    at ix (http://192.168.1.20:8123/api/hassio_ingress/OINwaL3YaFKzcCRR1jYrvOIrODKi0KqPqZ5nFtXMLZU/assets/index.3f63cdfc.js:33:53172)
    at M7 (http://192.168.1.20:8123/api/hassio_ingress/OINwaL3YaFKzcCRR1jYrvOIrODKi0KqPqZ5nFtXMLZU/assets/index.3f63cdfc.js:37:8838)
    at D7 (http://192.168.1.20:8123/api/hassio_ingress/OINwaL3YaFKzcCRR1jYrvOIrODKi0KqPqZ5nFtXMLZU/assets/index.3f63cdfc.js:37:955)
    at KMe (http://192.168.1.20:8123/api/hassio_ingress/OINwaL3YaFKzcCRR1jYrvOIrODKi0KqPqZ5nFtXMLZU/assets/index.3f63cdfc.js:37:881)
    at em (http://192.168.1.20:8123/api/hassio_ingress/OINwaL3YaFKzcCRR1jYrvOIrODKi0KqPqZ5nFtXMLZU/assets/index.3f63cdfc.js:37:732)
    at Vk (http://192.168.1.20:8123/api/hassio_ingress/OINwaL3YaFKzcCRR1jYrvOIrODKi0KqPqZ5nFtXMLZU/assets/index.3f63cdfc.js:35:10926)
    at http://192.168.1.20:8123/api/hassio_ingress/OINwaL3YaFKzcCRR1jYrvOIrODKi0KqPqZ5nFtXMLZU/assets/index.3f63cdfc.js:33:38960
    at e.unstable_runWithPriority (http://192.168.1.20:8123/api/hassio_ingress/OINwaL3YaFKzcCRR1jYrvOIrODKi0KqPqZ5nFtXMLZU/assets/index.3f63cdfc.js:22:3813)
    at Xl (http://192.168.1.20:8123/api/hassio_ingress/OINwaL3YaFKzcCRR1jYrvOIrODKi0KqPqZ5nFtXMLZU/assets/index.3f63cdfc.js:33:38737)
```

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by wojteksolo** [comment]
With the following external converter file everything works::

const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    fingerprint: [{modelID: 'TS0215A', manufacturerName: '_TZ3000_2izubafb'}],
    zigbeeModel: ['TS0215A'],
    model: 'TS0215A_sos',
    vendor: 'TuYa',
    description: 'SOS button',
    fromZigbee: [fz.command_emergency, fz.battery],
    toZigbee: [],
    configure: async (device, coordinatorEndpoint, logger) => {
        const endpoint = device.getEndpoint(1);
        await reporting.bind(endpoint, coordinatorEndpoint, ['genPowerCfg', 'genTime', 'genBasic', 'ssIasAce', 'ssIasZone']);
    },
    exposes: [e.battery(), e.action(['emergency']), e.linkquality()],
};

module.exports = definition;

**Comment by wojteksolo** [comment]
Update: Action and linkquality work, but unfortunately battery is always null.
