### ISSUE TITLE
I've found a bug - congratulations to me!

### ISSUE THREAD

**Issue by beachref** [nurikk/z2m-frontend#1566]
### What happened?

I was clicking around with my Ikea dimmer, and suddenly Zigbee2MQTT tells me to submit this report...
[initialState.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/9662006/initialState.json.zip)
![image](https://user-images.githubusercontent.com/76774144/192702642-6e64a6a6-b9cd-470f-874b-5b2a17e4c4ea.png)

TypeError
Cannot read properties of undefined (reading 'toLowerCase')
TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at http://192.168.0.75:9110/assets/index.a9c7b1d4.js:88:68307
    at Array.filter (<anonymous>)
    at aht.render (http://192.168.0.75:9110/assets/index.a9c7b1d4.js:88:68259)
    at RT (http://192.168.0.75:9110/assets/index.a9c7b1d4.js:33:65728)
    at gF (http://192.168.0.75:9110/assets/index.a9c7b1d4.js:33:65525)
    at L7 (http://192.168.0.75:9110/assets/index.a9c7b1d4.js:37:9805)
    at M7 (http://192.168.0.75:9110/assets/index.a9c7b1d4.js:37:955)
    at XMe (http://192.168.0.75:9110/assets/index.a9c7b1d4.js:37:881)
    at ef (http://192.168.0.75:9110/assets/index.a9c7b1d4.js:37:732)
    at VT (http://192.168.0.75:9110/assets/index.a9c7b1d4.js:35:10926)

### What browsers are you seeing the problem on?

Microsoft Edge

### Relevant stacktrace

```shell
**Current url**: http://192.168.0.75:9110/#/logs
**Previous url**: 


**Error type**: TypeError
**Error message**: Cannot read properties of undefined (reading 'toLowerCase')



TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at http://192.168.0.75:9110/assets/index.a9c7b1d4.js:88:68307
    at Array.filter (<anonymous>)
    at aht.render (http://192.168.0.75:9110/assets/index.a9c7b1d4.js:88:68259)
    at RT (http://192.168.0.75:9110/assets/index.a9c7b1d4.js:33:65728)
    at gF (http://192.168.0.75:9110/assets/index.a9c7b1d4.js:33:65525)
    at L7 (http://192.168.0.75:9110/assets/index.a9c7b1d4.js:37:9805)
    at M7 (http://192.168.0.75:9110/assets/index.a9c7b1d4.js:37:955)
    at XMe (http://192.168.0.75:9110/assets/index.a9c7b1d4.js:37:881)
    at ef (http://192.168.0.75:9110/assets/index.a9c7b1d4.js:37:732)
    at VT (http://192.168.0.75:9110/assets/index.a9c7b1d4.js:35:10926)
```

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by beachref** [comment]
[initialState.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/9662071/initialState.json.zip)
