### ISSUE TITLE
[Bug]: Homeassistant URL syntax ceck missing, leading to HA Exeption in async_discover

### ISSUE THREAD

**Issue by TBobsin** [nurikk/z2m-frontend#1593]
### What happened?

Hello,
i have (accidental) configured an typo in the URL field. http::// (two ::) 

Witch field:
URL Field 
URL on which the frontend can be reached, currently only used for the Home Assistant device configuration page

or in config File
> frontend:
    url: http ...

Following Problems:

- **no autodiscovery in HA**  (
because error message in HA core log:
Exception in async_discover when dispatching 'mqtt_discovery_new_device_automation_mqtt': ({'automation_type': 'trigger', 'device': {'configuration_url': 'https:://
	

**Solution**: please check the syntax 

Zigbee2MQTT Version    [1.28.1] commit: [48117fd]
Home Assistant 2022.11.1 Supervisor 2022.10.2 Operating System 9.3 Frontend 20221102.1 - latest 

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Relevant stacktrace

```shell
not Available
```

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by TBobsin** [comment]
in Version 1.29 the error is still present.

resulting log from Hom-eassistant.log
`2023-01-05 09:08:22.955 ERROR (MainThread) [homeassistant.util.logging] Exception in async_discover when dispatching 'mqtt_discovery_new_update_mqtt': ({'availability': [{'topic': 'zigbee2mqtt/bridge/state', 'value_template': '{{ value_json.state }}'}, {'topic': 'zigbee2mqtt/et2-ha-da81/availability', 'value_template': '{{ value_json.state }}'}], 'availability_mode': 'all', 'command_topic': 'zigbee2mqtt/bridge/request/device/ota_update/update', 'device': {'configuration_url': 'http:://pi-alarm:8088/#/device/0xec1bbdfffe33da81/info', 'identifiers': ['zigbee2mqtt_0xec1bbdfffe33da81'], 'manufacturer': 'IKEA', 'model': 'TRADFRI LED bulb E12/E14/E17 400 lumen, dimmable warm white, chandelier opal (LED1649C5)', 'name': 'et2-ha-da81', 'sw_version': '2.3.094'}, 'device_class': 'firmware', 'entity_picture': 'https://github.com/Koenkk/zigbee2mqtt/raw/master/images/logo.png', 'json_attributes_topic': 'zigbee2mqtt/et2-ha-da81', 'latest_version_template': "{{ value_json['update']['latest_version'] }}", 'latest_version_topic': 'zigbee2mqtt/et2-ha-da81', 'name': 'et2-ha-da81', 'payload_install': '{"id": "0xec1bbdfffe33da81"}', 'state_topic': 'zigbee2mqtt/et2-ha-da81', 'unique_id': '0xec1bbdfffe33da81_update_zigbee2mqtt', 'value_template': "{{ value_json['update']['installed_version'] }}", 'platform': 'mqtt'},)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 328, in async_discover
    config: DiscoveryInfoType = discovery_schema(discovery_payload)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 232, in __call__
    return self._exec((Schema(val) for val in self.validators), v)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 355, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 351, in _exec
    v = func(v)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 818, in validate_callable
    return schema(data)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 595, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 433, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: expected a URL for dictionary value @ data['device']['configuration_url']`
