### ISSUE TITLE
Error no encontrado

### ISSUE THREAD

**Issue by avm162** [nurikk/z2m-frontend#1605]
### What happened?

Saltó este error al eliminar un dispositivo que no se había emparejado correctamente.

No se pudo ejecutar 'removeChild' en 'Nodo': el nodo que se eliminará no es un elemento secundario de este nodo.
Error: no se pudo ejecutar 'removeChild' en 'Nodo': el nodo que se eliminará no es un elemento secundario de este nodo.
    en O7 (http://192.168.1.100:8080/assets/index.521d5d7a.js:35:5613)
    en CRE (http://192.168.1.100:8080/assets/index.521d5d7a.js:37:3888)
    en e.unstable_runWithPriority (http://192.168.1.100:8080/assets/index.521d5d7a.js:22:3813)
    a usted (http://192.168.1.100:8080/assets/index.521d5d7a.js:33:38737)
    en wl (http://192.168.1.100:8080/assets/index.521d5d7a.js:37:1838)
    en nC (http://192.168.1.100:8080/assets/index.521d5d7a.js:35:11143)
    en http://192.168.1.100:8080/assets/index.521d5d7a.js:33:38960
    en e.unstable_runWithPriority (http://192.168.1.100:8080/assets/index.521d5d7a.js:22:3813)
    a usted (http://192.168.1.100:8080/assets/index.521d5d7a.js:33:38737)
    en u7 (http://192.168.1.100:8080/assets/index.521d5d7a.js:33:38906)

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: http://192.168.1.100:8080/#/
**Previous url**: 


**Error type**: NotFoundError
**Error message**: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.



Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at O7 (http://192.168.1.100:8080/assets/index.521d5d7a.js:35:5613)
    at CRe (http://192.168.1.100:8080/assets/index.521d5d7a.js:37:3888)
    at e.unstable_runWithPriority (http://192.168.1.100:8080/assets/index.521d5d7a.js:22:3813)
    at tu (http://192.168.1.100:8080/assets/index.521d5d7a.js:33:38737)
    at wl (http://192.168.1.100:8080/assets/index.521d5d7a.js:37:1838)
    at nC (http://192.168.1.100:8080/assets/index.521d5d7a.js:35:11143)
    at http://192.168.1.100:8080/assets/index.521d5d7a.js:33:38960
    at e.unstable_runWithPriority (http://192.168.1.100:8080/assets/index.521d5d7a.js:22:3813)
    at tu (http://192.168.1.100:8080/assets/index.521d5d7a.js:33:38737)
    at u7 (http://192.168.1.100:8080/assets/index.521d5d7a.js:33:38906)
```

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by avm162** [comment]
[initialState.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/9964282/initialState.json.zip)
