### ISSUE TITLE
[Bug]: argument of type 'float' is not iterable

### ISSUE THREAD

**Issue by drjjr2** [nurikk/z2m-frontend#1620]
### What happened?

I am seeing lots of messages in the log like this:
```
2022-12-03 08:39:20.715 ERROR (MainThread) [homeassistant.util.logging] Exception in handle_state_message_received when handling msg on 'zigbee2mqtt/Upstairs Christmas Lights': '{"last_seen":"2022-12-03T08:39:20-06:00","linkquality":112,"state":"ON","update":{"installed_version":"2.1","state":"available"},"update_available":null}'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 44, in wrapper
    msg_callback(msg)
  File "/usr/src/homeassistant/homeassistant/components/mqtt/update.py", line 191, in handle_state_message_received
    if "installed_version" in json_payload:
TypeError: argument of type 'float' is not iterable
```

### What browsers are you seeing the problem on?

Chrome

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by drjjr2** [comment]
[state.json (2).zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/10146727/state.json.2.zip)

**Comment by nurikk** [comment]
Hello, it’s not frontend issue. Please seek help from homeassistant team

**Comment by drjjr2** [comment]
Heard that. Thank you.
