### ISSUE TITLE
[Bug]: Herdsman fails to start

### ISSUE THREAD

**Issue by MrGibbage** [nurikk/z2m-frontend#1645]
### What happened?

Zigbee2Mqtt Edge version
My Sonoff 3 is installed (raspian) and the OS sees the device
➜  ~ ls /dev/serial/by-id -l
total 0
lrwxrwxrwx    1 root     root            13 Jun  2  2022 usb-0658_0200-if00 -> ../../ttyACM0
lrwxrwxrwx    1 root     root            13 Jun  2  2022 usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_7ecfd66fd69cec11808f634d73138bba-if00-port0 -> ../../ttyUSB0
➜  ~

I have tried using the long "by-id" name and the short ttyUSB0, and I always get the same error:

error 2023-01-10 20:26:34: Error while starting zigbee-herdsman
error 2023-01-10 20:26:34: Failed to start zigbee

This was working two days ago, but I rebooted and now it's not. I don't remember what I had in the config before, but this is what I have in there now:

```
data_path: /config/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: "-d -d"
  log: true
mqtt:
  base_topic: zigbee2mqtt
  user: addons
  password: pass
  server: mqtt://core-mosquitto:1883
serial:
  port: >-
    /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_7ecfd66fd69cec11808f634d73138bba-if00-port0
devices:
  - devices.yaml
groups:
  - groups.yaml
homeassistant: true
permit_join: false
advanced:
  log_level: debug
  timestamp_format: YYYY-MM-DD HH:mm:ss
  log_directory: data/log/%TIMESTAMP%
  log_file: log.txt
  log_rotation: true
  log_output:
    - console
    - file
    - syslog
  pan_id: 18553
  channel: 15
  network_key:
    - 78
    - 75
    - 156
    - 219
    - 70
    - 23
    - 218
    - 207
    - 135
    - 39
    - 190
    - 157
    - 84
    - 73
    - 14
    - 168
  availability_blocklist: []
  availability_passlist: []
  log_syslog:
    app_name: Zigbee2MQTT
    eol: /n
    host: localhost
    localhost: localhost
    path: /dev/log
    pid: process.pid
    port: 123
    protocol: tcp4
    type: "5424"
  transmit_power: 9
  last_seen: ISO_8601_local
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
device_options:
  legacy: false
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
availability: true

```

And I have also tried

serial:
  port: /dev/ttyUSB0

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
debug 2023-01-10 20:26:14: Loaded state from file /config/zigbee2mqtt/state.json
info  2023-01-10 20:26:14: Logging to console and directory: '/config/zigbee2mqtt/log/2023-01-10.20-26-14' filename: log.txt
debug 2023-01-10 20:26:14: Removing old log directory '/config/zigbee2mqtt/log/2023-01-10.18-11-55'
info  2023-01-10 20:26:14: Starting Zigbee2MQTT version 1.28.4-dev (commit #58445a2)
info  2023-01-10 20:26:14: Starting zigbee-herdsman (0.14.82)
debug 2023-01-10 20:26:14: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/config/zigbee2mqtt/coordinator_backup.json","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","databasePath":"/config/zigbee2mqtt/database.db","network":{"channelList":[15],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":18553},"serialPort":{"path":"/dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_7ecfd66fd69cec11808f634d73138bba-if00-port0"}}'
error 2023-01-10 20:26:34: Error while starting zigbee-herdsman
error 2023-01-10 20:26:34: Failed to start zigbee
error 2023-01-10 20:26:34: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
error 2023-01-10 20:26:34: Exiting...
error 2023-01-10 20:26:35: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:103:27)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
    at Zigbee.start (/app/lib/zigbee.ts:58:27)
    at Controller.start (/app/lib/controller.ts:101:27)
    at start (/app/index.js:107:5)
```
```


### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by MrGibbage** [comment]
Cancel this. It started working today. No idea why.
