### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by stefancn** [nurikk/z2m-frontend#1654]
### What happened?

1) The configuration shown on the addon's configuration page is not saved in /config/zigbee2mqtt/configuration.yaml

2) ... and it refuses to start

Btw.  I have Skyconnect adapter and the Zigbee2MQTT version: 1.29.2-1 

and:

Home Assistant 2023.1.4
Supervisor 2022.12.1
Operating System 9.4
Frontend 20230110.0 - latest

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
Zigbee2MQTT:info  2023-01-15 16:17:29: Starting Zigbee2MQTT version 1.29.2 (commit #unknown)
Zigbee2MQTT:info  2023-01-15 16:17:29: Starting zigbee-herdsman (0.14.83-hotfix.0)
Zigbee2MQTT:error 2023-01-15 16:18:32: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2023-01-15 16:18:32: Failed to start zigbee
Zigbee2MQTT:error 2023-01-15 16:18:32: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2023-01-15 16:18:32: Exiting...
Zigbee2MQTT:error 2023-01-15 16:18:33: Error: Failure send setConfigurationValue:{"type":"Buffer","data":[1,0,1,83,0,29,50,0]}
    at /app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/ezsp.ts:516:23
    at Queue.executeNext (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:32:32)
```

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by stefancn** [comment]
Hi ... I'm so sorry,  I found out that the system had the std. driver running for the USB Skyconnect module.  Disable that, restarted the HA, and started the Z2M ,  and violaa ... system up and running.  Even OTA for IKEA Tradfri .. works.

Regards ...

/S
