### ISSUE TITLE
[Bug]: Error: ENOENT: no such file or directory, open '/config/zigbee2mqtt/.yaml'

### ISSUE THREAD

**Issue by jaaphummel** [nurikk/z2m-frontend#1667]
### What happened?

While adding a device, somehow mqtt failed, and since then i get this error.
It should probably be : open '/config/zigbee2mqtt/**configuration**.yaml' instead of open '/config/zigbee2mqtt/.yaml' but i cannot find anything in the config file or something to edit this.

Am i missing something?

Thanks in advance

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Relevant stacktrace

```shell
2023-02-02T20:11:56.314Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,14,69,132,0,0,0,0,0,8,8,4,1,5,0,0,0,0,207]
2023-02-02T20:11:56.314Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 14 - 2 - 5 - 132 - [0,0,0,0,0,8,8,4,1,5,0,0,0,0] - 207
2023-02-02T20:11:56.314Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- ZDO - simpleDescRsp - {"srcaddr":0,"status":0,"nwkaddr":0,"len":8,"endpoint":8,"profileid":260,"deviceid":5,"deviceversion":0,"numinclusters":0,"inclusterlist":[],"numoutclusters":0,"outclusterlist":[]}
2023-02-02T20:11:56.316Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2023-02-02T20:11:56.318Z zigbee-herdsman:adapter:zStack:znp:SREQ --> ZDO - simpleDescReq - {"dstaddr":0,"nwkaddrofinterest":0,"endpoint":6}
2023-02-02T20:11:56.319Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,5,37,4,0,0,0,0,6,34]
2023-02-02T20:11:56.325Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,101,4,0,96]
2023-02-02T20:11:56.326Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,101,4,0,96]
2023-02-02T20:11:56.328Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 5 - 4 - [0] - 96
2023-02-02T20:11:56.329Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- ZDO - simpleDescReq - {"status":0}
2023-02-02T20:11:56.331Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2023-02-02T20:11:56.334Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,14,69,132,0,0,0,0,0,8,6,9,1,5,0,0,0,0,204]
2023-02-02T20:11:56.336Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,14,69,132,0,0,0,0,0,8,6,9,1,5,0,0,0,0,204]
2023-02-02T20:11:56.336Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 14 - 2 - 5 - 132 - [0,0,0,0,0,8,6,9,1,5,0,0,0,0] - 204
2023-02-02T20:11:56.338Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- ZDO - simpleDescRsp - {"srcaddr":0,"status":0,"nwkaddr":0,"len":8,"endpoint":6,"profileid":265,"deviceid":5,"deviceversion":0,"numinclusters":0,"inclusterlist":[],"numoutclusters":0,"outclusterlist":[]}
2023-02-02T20:11:56.340Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2023-02-02T20:11:56.341Z zigbee-herdsman:adapter:zStack:znp:SREQ --> ZDO - simpleDescReq - {"dstaddr":0,"nwkaddrofinterest":0,"endpoint":5}
2023-02-02T20:11:56.342Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,5,37,4,0,0,0,0,5,33]
2023-02-02T20:11:56.347Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,101,4,0,96]
2023-02-02T20:11:56.347Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,101,4,0,96]
2023-02-02T20:11:56.349Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 5 - 4 - [0] - 96
2023-02-02T20:11:56.350Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- ZDO - simpleDescReq - {"status":0}
2023-02-02T20:11:56.351Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2023-02-02T20:11:56.353Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,14,69,132,0,0,0,0,0,8,5,8,1,5,0,0,0,0,206]
2023-02-02T20:11:56.353Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,14,69,132,0,0,0,0,0,8,5,8,1,5,0,0,0,0,206]
2023-02-02T20:11:56.354Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 14 - 2 - 5 - 132 - [0,0,0,0,0,8,5,8,1,5,0,0,0,0] - 206
2023-02-02T20:11:56.356Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- ZDO - simpleDescRsp - {"srcaddr":0,"status":0,"nwkaddr":0,"len":8,"endpoint":5,"profileid":264,"deviceid":5,"deviceversion":0,"numinclusters":0,"inclusterlist":[],"numoutclusters":0,"outclusterlist":[]}
2023-02-02T20:11:56.357Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2023-02-02T20:11:56.358Z zigbee-herdsman:adapter:zStack:znp:SREQ --> ZDO - simpleDescReq - {"dstaddr":0,"nwkaddrofinterest":0,"endpoint":4}
2023-02-02T20:11:56.359Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,5,37,4,0,0,0,0,4,32]
2023-02-02T20:11:56.364Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,101,4,0,96]
2023-02-02T20:11:56.364Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,101,4,0,96]
2023-02-02T20:11:56.366Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 5 - 4 - [0] - 96
2023-02-02T20:11:56.367Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- ZDO - simpleDescReq - {"status":0}
2023-02-02T20:11:56.367Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2023-02-02T20:11:56.372Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,14,69,132,0,0,0,0,0,8,4,7,1,5,0,0,0,0,192]
2023-02-02T20:11:56.373Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,14,69,132,0,0,0,0,0,8,4,7,1,5,0,0,0,0,192]
2023-02-02T20:11:56.373Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 14 - 2 - 5 - 132 - [0,0,0,0,0,8,4,7,1,5,0,0,0,0] - 192
2023-02-02T20:11:56.375Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- ZDO - simpleDescRsp - {"srcaddr":0,"status":0,"nwkaddr":0,"len":8,"endpoint":4,"profileid":263,"deviceid":5,"deviceversion":0,"numinclusters":0,"inclusterlist":[],"numoutclusters":0,"outclusterlist":[]}
2023-02-02T20:11:56.376Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2023-02-02T20:11:56.378Z zigbee-herdsman:adapter:zStack:znp:SREQ --> ZDO - simpleDescReq - {"dstaddr":0,"nwkaddrofinterest":0,"endpoint":3}
2023-02-02T20:11:56.379Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,5,37,4,0,0,0,0,3,39]
2023-02-02T20:11:56.383Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,101,4,0,96]
2023-02-02T20:11:56.385Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,101,4,0,96]
2023-02-02T20:11:56.385Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 5 - 4 - [0] - 96
2023-02-02T20:11:56.386Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- ZDO - simpleDescReq - {"status":0}
2023-02-02T20:11:56.388Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2023-02-02T20:11:56.390Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,14,69,132,0,0,0,0,0,8,3,4,1,5,0,0,0,0,196]
2023-02-02T20:11:56.390Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,14,69,132,0,0,0,0,0,8,3,4,1,5,0,0,0,0,196]
2023-02-02T20:11:56.391Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 14 - 2 - 5 - 132 - [0,0,0,0,0,8,3,4,1,5,0,0,0,0] - 196
2023-02-02T20:11:56.392Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- ZDO - simpleDescRsp - {"srcaddr":0,"status":0,"nwkaddr":0,"len":8,"endpoint":3,"profileid":260,"deviceid":5,"deviceversion":0,"numinclusters":0,"inclusterlist":[],"numoutclusters":0,"outclusterlist":[]}
2023-02-02T20:11:56.394Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2023-02-02T20:11:56.395Z zigbee-herdsman:adapter:zStack:znp:SREQ --> ZDO - simpleDescReq - {"dstaddr":0,"nwkaddrofinterest":0,"endpoint":2}
2023-02-02T20:11:56.396Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,5,37,4,0,0,0,0,2,38]
2023-02-02T20:11:56.402Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,101,4,0,96]
2023-02-02T20:11:56.403Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,101,4,0,96]
2023-02-02T20:11:56.403Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 5 - 4 - [0] - 96
2023-02-02T20:11:56.403Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- ZDO - simpleDescReq - {"status":0}
2023-02-02T20:11:56.404Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2023-02-02T20:11:56.405Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,14,69,132,0,0,0,0,0,8,2,1,1,5,0,0,0,0,192]
2023-02-02T20:11:56.407Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,14,69,132,0,0,0,0,0,8,2,1,1,5,0,0,0,0,192]
2023-02-02T20:11:56.410Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 14 - 2 - 5 - 132 - [0,0,0,0,0,8,2,1,1,5,0,0,0,0] - 192
2023-02-02T20:11:56.412Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- ZDO - simpleDescRsp - {"srcaddr":0,"status":0,"nwkaddr":0,"len":8,"endpoint":2,"profileid":257,"deviceid":5,"deviceversion":0,"numinclusters":0,"inclusterlist":[],"numoutclusters":0,"outclusterlist":[]}
2023-02-02T20:11:56.414Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2023-02-02T20:11:56.415Z zigbee-herdsman:adapter:zStack:znp:SREQ --> ZDO - simpleDescReq - {"dstaddr":0,"nwkaddrofinterest":0,"endpoint":1}
2023-02-02T20:11:56.417Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,5,37,4,0,0,0,0,1,37]
2023-02-02T20:11:56.421Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,101,4,0,96]
2023-02-02T20:11:56.422Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,101,4,0,96]
2023-02-02T20:11:56.423Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 5 - 4 - [0] - 96
2023-02-02T20:11:56.425Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- ZDO - simpleDescReq - {"status":0}
2023-02-02T20:11:56.425Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2023-02-02T20:11:56.428Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,14,69,132,0,0,0,0,0,8,1,4,1,5,0,0,0,0,198]
2023-02-02T20:11:56.428Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,14,69,132,0,0,0,0,0,8,1,4,1,5,0,0,0,0,198]
2023-02-02T20:11:56.429Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 14 - 2 - 5 - 132 - [0,0,0,0,0,8,1,4,1,5,0,0,0,0] - 198
2023-02-02T20:11:56.430Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- ZDO - simpleDescRsp - {"srcaddr":0,"status":0,"nwkaddr":0,"len":8,"endpoint":1,"profileid":260,"deviceid":5,"deviceversion":0,"numinclusters":0,"inclusterlist":[],"numoutclusters":0,"outclusterlist":[]}
2023-02-02T20:11:56.430Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
Zigbee2MQTT:info  2023-02-02 21:11:56: zigbee-herdsman started (resumed)
Zigbee2MQTT:info  2023-02-02 21:11:56: Coordinator firmware version: '{"meta":{"maintrel":1,"majorrel":2,"minorrel":7,"product":1,"revision":20210708,"transportrev":2},"type":"zStack3x0"}'
2023-02-02T20:11:56.447Z zigbee-herdsman:adapter:zStack:znp:SREQ --> ZDO - extNwkInfo - {}
2023-02-02T20:11:56.448Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,0,37,80,117]
2023-02-02T20:11:56.453Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,24,101,80,0,0,9,98,26,0,0,111,20,126,37,0,75,18,0,0,0,0,0,0,0,0,0,11,46]
2023-02-02T20:11:56.454Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,24,101,80,0,0,9,98,26,0,0,111,20,126,37,0,75,18,0,0,0,0,0,0,0,0,0,11,46]
2023-02-02T20:11:56.455Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 24 - 3 - 5 - 80 - [0,0,9,98,26,0,0,111,20,126,37,0,75,18,0,0,0,0,0,0,0,0,0,11] - 46
2023-02-02T20:11:56.457Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- ZDO - extNwkInfo - {"shortaddr":0,"devstate":9,"panid":6754,"parentaddr":0,"extendedpanid":"0x00124b00257e146f","parentextaddr":"0x0000000000000000","channel":11}
2023-02-02T20:11:56.457Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
Zigbee2MQTT:debug 2023-02-02 21:11:56: Zigbee network parameters: {"channel":11,"extendedPanID":"0x00124b00257e146f","panID":6754}
Zigbee2MQTT:error 2023-02-02 21:11:56: Failed to start zigbee
Zigbee2MQTT:error 2023-02-02 21:11:56: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2023-02-02 21:11:56: Exiting...
Zigbee2MQTT:error 2023-02-02 21:11:56: Error: ENOENT: no such file or directory, open '/config/zigbee2mqtt/.yaml'
    at Object.openSync (node:fs:594:3)
    at Object.readFileSync (node:fs:462:35)
    at read (/app/lib/util/yaml.ts:7:29)
    at Object.updateIfChanged (/app/lib/util/yaml.ts:29:21)
    at write (/app/lib/util/settings.ts:225:22)
    at Object.addDevice (/app/lib/util/settings.ts:555:5)
    at Device.ensureInSettings (/app/lib/model/device.ts:41:22)
    at Zigbee.resolveDevice (/app/lib/zigbee.ts:234:20)
    at /app/lib/zigbee.ts:276:30
    at Array.map (<anonymous>)
```

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by jaaphummel** [comment]
Reinstall mqtt broker and and 2mqtt fixed it.. no clue to why the error camera up
