### ISSUE TITLE
bug bug

### ISSUE THREAD

**Issue by amgstone** [nurikk/z2m-frontend#1692]
### What happened?

[initialState.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/10959640/initialState.json.zip)

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: http://192.168.31.253:8080/#/
**Previous url**: 


**Error type**: NotFoundError
**Error message**: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.



Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at z7 (http://192.168.31.253:8080/assets/index.1a2b4112.js:35:5613)
    at RRe (http://192.168.31.253:8080/assets/index.1a2b4112.js:37:3888)
    at e.unstable_runWithPriority (http://192.168.31.253:8080/assets/index.1a2b4112.js:22:3813)
    at tu (http://192.168.31.253:8080/assets/index.1a2b4112.js:33:38737)
    at wl (http://192.168.31.253:8080/assets/index.1a2b4112.js:37:1838)
    at oC (http://192.168.31.253:8080/assets/index.1a2b4112.js:35:11143)
    at http://192.168.31.253:8080/assets/index.1a2b4112.js:33:38960
    at e.unstable_runWithPriority (http://192.168.31.253:8080/assets/index.1a2b4112.js:22:3813)
    at tu (http://192.168.31.253:8080/assets/index.1a2b4112.js:33:38737)
    at f7 (http://192.168.31.253:8080/assets/index.1a2b4112.js:33:38906)
```

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by amgstone** [comment]
Ьь.




















пт, 19 трав. 2023, 12:05 дп користувач stale[bot] ***@***.***>
пише:
