### ISSUE TITLE
[Bug]: Dev Console Does Not Allow The Use Of Cluster Name For Commands

### ISSUE THREAD

**Issue by danieledwardgeorgehitchcock** [nurikk/z2m-frontend#1701]
### What happened?

In the dev console (commands section), the Cluster input box does not allow for the cluster name to be used. This presents an issue whereby, there are cases where manufacturers can implement their own cluster specification that overlaps others. An example of this is the `manuSpecificUbisisDeviceSetup` cluster clashing with `manuSpecificAssaDoorLock`. I originally raised this in the Zigbee Herdsman project see here: Koenkk/zigbee-herdsman#686 however, it appears that Zigbee Herdsman (and therefore Zigbee2MQTT) does allow for cluster names to be specified in replacement of ID's (same too with the command itself)

There are 2 ways that this could potentially be resolved. 1) allow for text names of clusters to be entered into the cluster input box 2) copy the dropdown list with enumerated clusters from the attributes section above it.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Relevant stacktrace

```shell
Zigbee2MQTT:debug 2023-03-28 07:33:45: Received MQTT message on 'zigbee2mqtt/0x000d6f0011141333/1/set' with data '{"command":{"cluster":64512,"command":18,"payload":{}}}'
Zigbee2MQTT:debug 2023-03-28 07:33:45: Publishing 'set' 'command' to '0x000d6f0011141333'
Zigbee2MQTT:error 2023-03-28 07:33:45: Publish 'set' 'command' to '0x000d6f0011141333' failed: 'Error: Cluster 'manuSpecificUbisysDeviceSetup' has no command '18''
Zigbee2MQTT:debug 2023-03-28 07:33:46: Error: Cluster 'manuSpecificUbisysDeviceSetup' has no command '18'
    at Object.getCommand (/app/node_modules/zigbee-herdsman/src/zcl/utils.ts:114:19)
    at Endpoint.command (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:781:33)
    at Object.convertSet (/app/node_modules/zigbee-herdsman-converters/converters/toZigbee.js:54:26)
    at Publish.onMQTTMessage (/app/lib/extension/publish.ts:247:52)
    at EventEmitter.emit (node:events:525:35)
    at EventBus.emitMQTTMessage (/app/lib/eventBus.ts:109:22)
    at MQTT.onMessage (/app/lib/mqtt.ts:140:27)
    at WebSocket.<anonymous> (/app/lib/extension/frontend.ts:126:27)
    at WebSocket.emit (node:events:513:28)
    at Receiver.receiverOnMessage (/app/node_modules/ws/lib/websocket.js:1184:20)
```

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by danieledwardgeorgehitchcock** [comment]
Bump...

**Comment by danieledwardgeorgehitchcock** [comment]
Bump...

**Comment by danieledwardgeorgehitchcock** [comment]
Bump...
