### ISSUE TITLE
unknown tag !<!include> 

### ISSUE THREAD

**Issue by Bellavista** [nurikk/z2m-frontend#1703]
### What happened?

Hi all
I do not undstend "unknown tag !<!include>"
can someone help me

[00:06:17] INFO: Preparing to start...
[00:06:18] INFO: Socat not enabled
[00:06:19] INFO: Zigbee Herdsman debug logging enabled
[00:06:21] INFO: Starting Zigbee2MQTT...
/app/node_modules/js-yaml/lib/loader.js:183
  return new YAMLException(message, mark);
         ^
YAMLException: unknown tag !<!include> (8:38)
 5 |  ... ita l'integrazione AUTOMAZIONI
 6 |  ... stazioni->Automazioni
 7 |  ...  compreso nel meta-componente default_config:
 8 |  ... tion: !include automations.yaml
-----------------------------------------^
 9 |  ... mation: !include_dir_merge_list automations
 10 |  ... ncludi la directory non riesce a gestire le automazioni in auto ...
    at generateError (/app/node_modules/js-yaml/lib/loader.js:183:10)
    at throwError (/app/node_modules/js-yaml/lib/loader.js:187:9)
    at composeNode (/app/node_modules/js-yaml/lib/loader.js:1521:7)
    at readBlockMapping (/app/node_modules/js-yaml/lib/loader.js:1164:11)
    at composeNode (/app/node_modules/js-yaml/lib/loader.js:1441:12)
    at readDocument (/app/node_modules/js-yaml/lib/loader.js:1625:3)
    at loadDocuments (/app/node_modules/js-yaml/lib/loader.js:1688:5)
    at Object.load (/app/node_modules/js-yaml/lib/loader.js:1714:19)
    at Object.read (/app/lib/util/yaml.ts:7:21)
    at read (/app/lib/util/settings.ts:328:20)

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
data_path: /config/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: "-d -d"
  log: false
mqtt:
  server: mqtt://192.168.1.10:1883
  user: xyxyxxy
  password: xyxyxy
serial:
  port: /dev/ttyACM0
  adapter: deconz
zigbee_herdsman_debug: true
```

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by Bellavista** [comment]
Configurator.yaml was wrong
