### ISSUE TITLE
Bug in Touchlink menu

### ISSUE THREAD

**Issue by AHDPEI1** [nurikk/z2m-frontend#1715]
### What happened?

![image](https://user-images.githubusercontent.com/125581349/232878631-e6c1c36f-aa4d-4c89-95cb-7cddf720d14b.png)
[initialState.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/11265380/initialState.json.zip)

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: http://192.168.0.17:8090/#/touchlink
**Previous url**: http://192.168.0.17:8090/#/ota


**Error type**: TypeError
**Error message**: Cannot read properties of undefined (reading 'length')



TypeError: Cannot read properties of undefined (reading 'length')
    at lgt.render (http://192.168.0.17:8090/assets/index.84e4b11c.js:95:176720)
    at Vk (http://192.168.0.17:8090/assets/index.84e4b11c.js:33:65728)
    at y3 (http://192.168.0.17:8090/assets/index.84e4b11c.js:33:65525)
    at j9 (http://192.168.0.17:8090/assets/index.84e4b11c.js:37:9805)
    at z9 (http://192.168.0.17:8090/assets/index.84e4b11c.js:37:955)
    at kRe (http://192.168.0.17:8090/assets/index.84e4b11c.js:37:881)
    at ch (http://192.168.0.17:8090/assets/index.84e4b11c.js:37:732)
    at nC (http://192.168.0.17:8090/assets/index.84e4b11c.js:35:10926)
    at http://192.168.0.17:8090/assets/index.84e4b11c.js:33:38960
    at e.unstable_runWithPriority (http://192.168.0.17:8090/assets/index.84e4b11c.js:22:3813)
```

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by nurikk** [comment]
Hi! Can you try to reproduce on latest z2m dev version?
