### ISSUE TITLE
problema zigbee2mqtt

### ISSUE THREAD

**Issue by kalixoel** [nurikk/z2m-frontend#1739]
### What happened?

Hello, you've found a bug. Congratulations!
Calm down
Click here, and save this file
Raise a github issue, attach previously downloaded file
Take a screenshot of this page and attach to the issue
In the github issue write detailed description for the issue, how this happened? Steps to reproduce
NotFoundError
Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at z7 (https://z9w2yg8utjt1fmt1z0mzbefteplkyccd.ui.nabu.casa/api/hassio_ingress/Yz0JXbkzfySiV3Uo9qu3L_xdeHi732r5z3LxkF3ohGE/assets/index.c0cc3410.js:35:5613)
    at RRe (https://z9w2yg8utjt1fmt1z0mzbefteplkyccd.ui.nabu.casa/api/hassio_ingress/Yz0JXbkzfySiV3Uo9qu3L_xdeHi732r5z3LxkF3ohGE/assets/index.c0cc3410.js:37:3888)
    at e.unstable_runWithPriority (https://z9w2yg8utjt1fmt1z0mzbefteplkyccd.ui.nabu.casa/api/hassio_ingress/Yz0JXbkzfySiV3Uo9qu3L_xdeHi732r5z3LxkF3ohGE/assets/index.c0cc3410.js:22:3813)
    at tu (https://z9w2yg8utjt1fmt1z0mzbefteplkyccd.ui.nabu.casa/api/hassio_ingress/Yz0JXbkzfySiV3Uo9qu3L_xdeHi732r5z3LxkF3ohGE/assets/index.c0cc3410.js:33:38737)
    at wl (https://z9w2yg8utjt1fmt1z0mzbefteplkyccd.ui.nabu.casa/api/hassio_ingress/Yz0JXbkzfySiV3Uo9qu3L_xdeHi732r5z3LxkF3ohGE/assets/index.c0cc3410.js:37:1838)
    at sC (https://z9w2yg8utjt1fmt1z0mzbefteplkyccd.ui.nabu.casa/api/hassio_ingress/Yz0JXbkzfySiV3Uo9qu3L_xdeHi732r5z3LxkF3ohGE/assets/index.c0cc3410.js:35:11143)
    at https://z9w2yg8utjt1fmt1z0mzbefteplkyccd.ui.nabu.casa/api/hassio_ingress/Yz0JXbkzfySiV3Uo9qu3L_xdeHi732r5z3LxkF3ohGE/assets/index.c0cc3410.js:33:38960
    at e.unstable_runWithPriority (https://z9w2yg8utjt1fmt1z0mzbefteplkyccd.ui.nabu.casa/api/hassio_ingress/Yz0JXbkzfySiV3Uo9qu3L_xdeHi732r5z3LxkF3ohGE/assets/index.c0cc3410.js:22:3813)
    at tu (https://z9w2yg8utjt1fmt1z0mzbefteplkyccd.ui.nabu.casa/api/hassio_ingress/Yz0JXbkzfySiV3Uo9qu3L_xdeHi732r5z3LxkF3ohGE/assets/index.c0cc3410.js:33:38737)
    at f7 (https://z9w2yg8utjt1fmt1z0mzbefteplkyccd.ui.nabu.casa/api/hassio_ingress/Yz0JXbkzfySiV3Uo9qu3L_xdeHi732r5z3LxkF3ohGE/assets/index.c0cc3410.js:33:38906)

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: https://z9w2yg8utjt1fmt1z0mzbefteplkyccd.ui.nabu.casa/api/hassio_ingress/Yz0JXbkzfySiV3Uo9qu3L_xdeHi732r5z3LxkF3ohGE/#/
**Previous url**: https://z9w2yg8utjt1fmt1z0mzbefteplkyccd.ui.nabu.casa/45df7312_zigbee2mqtt


**Error type**: NotFoundError
**Error message**: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.



Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at z7 (https://z9w2yg8utjt1fmt1z0mzbefteplkyccd.ui.nabu.casa/api/hassio_ingress/Yz0JXbkzfySiV3Uo9qu3L_xdeHi732r5z3LxkF3ohGE/assets/index.c0cc3410.js:35:5613)
    at RRe (https://z9w2yg8utjt1fmt1z0mzbefteplkyccd.ui.nabu.casa/api/hassio_ingress/Yz0JXbkzfySiV3Uo9qu3L_xdeHi732r5z3LxkF3ohGE/assets/index.c0cc3410.js:37:3888)
    at e.unstable_runWithPriority (https://z9w2yg8utjt1fmt1z0mzbefteplkyccd.ui.nabu.casa/api/hassio_ingress/Yz0JXbkzfySiV3Uo9qu3L_xdeHi732r5z3LxkF3ohGE/assets/index.c0cc3410.js:22:3813)
    at tu (https://z9w2yg8utjt1fmt1z0mzbefteplkyccd.ui.nabu.casa/api/hassio_ingress/Yz0JXbkzfySiV3Uo9qu3L_xdeHi732r5z3LxkF3ohGE/assets/index.c0cc3410.js:33:38737)
    at wl (https://z9w2yg8utjt1fmt1z0mzbefteplkyccd.ui.nabu.casa/api/hassio_ingress/Yz0JXbkzfySiV3Uo9qu3L_xdeHi732r5z3LxkF3ohGE/assets/index.c0cc3410.js:37:1838)
    at sC (https://z9w2yg8utjt1fmt1z0mzbefteplkyccd.ui.nabu.casa/api/hassio_ingress/Yz0JXbkzfySiV3Uo9qu3L_xdeHi732r5z3LxkF3ohGE/assets/index.c0cc3410.js:35:11143)
    at https://z9w2yg8utjt1fmt1z0mzbefteplkyccd.ui.nabu.casa/api/hassio_ingress/Yz0JXbkzfySiV3Uo9qu3L_xdeHi732r5z3LxkF3ohGE/assets/index.c0cc3410.js:33:38960
    at e.unstable_runWithPriority (https://z9w2yg8utjt1fmt1z0mzbefteplkyccd.ui.nabu.casa/api/hassio_ingress/Yz0JXbkzfySiV3Uo9qu3L_xdeHi732r5z3LxkF3ohGE/assets/index.c0cc3410.js:22:3813)
    at tu (https://z9w2yg8utjt1fmt1z0mzbefteplkyccd.ui.nabu.casa/api/hassio_ingress/Yz0JXbkzfySiV3Uo9qu3L_xdeHi732r5z3LxkF3ohGE/assets/index.c0cc3410.js:33:38737)
    at f7 (https://z9w2yg8utjt1fmt1z0mzbefteplkyccd.ui.nabu.casa/api/hassio_ingress/Yz0JXbkzfySiV3Uo9qu3L_xdeHi732r5z3LxkF3ohGE/assets/index.c0cc3410.js:33:38906)
```

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by kalixoel** [comment]
[initialState.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/11523869/initialState.json.zip)
