### ISSUE TITLE
Bug report after updating zigbee2mqtt

### ISSUE THREAD

**Issue by Neltarionko** [nurikk/z2m-frontend#1752]
### What happened?

![image](https://github.com/nurikk/zigbee2mqtt-frontend/assets/23694780/88077eed-d77c-4f13-aabf-46c1033c9883)
[initialState.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/11981772/initialState.json.zip)
[state.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/11981822/state.json.zip)

I updated from 1.31 to 1.32 and see this error page.

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: http://demo.emelya.tech/api/hassio_ingress/uMi9KAQK7IrpjndqIroe8ytdK7WqL9fTzN_9wQeUY2c/#/
**Previous url**: http://demo.emelya.tech/45df7312_zigbee2mqtt


**Error type**: Error
**Error message**: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B0%2C%201%2C%202%2C%203%2C%204%2C%205%2C%206%2C%207%2C%208%2C%209%2C%2010%2C%2011%2C%2012%2C%2013%2C%2014%2C%2015%2C%2016%2C%2017%2C%2018%2C%2019%2C%2020%2C%2021%2C%2022%2C%2023%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.



Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B0%2C%201%2C%202%2C%203%2C%204%2C%205%2C%206%2C%207%2C%208%2C%209%2C%2010%2C%2011%2C%2012%2C%2013%2C%2014%2C%2015%2C%2016%2C%2017%2C%2018%2C%2019%2C%2020%2C%2021%2C%2022%2C%2023%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at ev (http://demo.emelya.tech/api/hassio_ingress/uMi9KAQK7IrpjndqIroe8ytdK7WqL9fTzN_9wQeUY2c/assets/index.edc783e1.js:33:45307)
    at d (http://demo.emelya.tech/api/hassio_ingress/uMi9KAQK7IrpjndqIroe8ytdK7WqL9fTzN_9wQeUY2c/assets/index.edc783e1.js:33:46936)
    at p (http://demo.emelya.tech/api/hassio_ingress/uMi9KAQK7IrpjndqIroe8ytdK7WqL9fTzN_9wQeUY2c/assets/index.edc783e1.js:33:48043)
    at http://demo.emelya.tech/api/hassio_ingress/uMi9KAQK7IrpjndqIroe8ytdK7WqL9fTzN_9wQeUY2c/assets/index.edc783e1.js:33:50146
    at Ba (http://demo.emelya.tech/api/hassio_ingress/uMi9KAQK7IrpjndqIroe8ytdK7WqL9fTzN_9wQeUY2c/assets/index.edc783e1.js:33:61196)
    at G7 (http://demo.emelya.tech/api/hassio_ingress/uMi9KAQK7IrpjndqIroe8ytdK7WqL9fTzN_9wQeUY2c/assets/index.edc783e1.js:37:10528)
    at W7 (http://demo.emelya.tech/api/hassio_ingress/uMi9KAQK7IrpjndqIroe8ytdK7WqL9fTzN_9wQeUY2c/assets/index.edc783e1.js:37:955)
    at ORe (http://demo.emelya.tech/api/hassio_ingress/uMi9KAQK7IrpjndqIroe8ytdK7WqL9fTzN_9wQeUY2c/assets/index.edc783e1.js:37:881)
    at dh (http://demo.emelya.tech/api/hassio_ingress/uMi9KAQK7IrpjndqIroe8ytdK7WqL9fTzN_9wQeUY2c/assets/index.edc783e1.js:37:732)
    at sC (http://demo.emelya.tech/api/hassio_ingress/uMi9KAQK7IrpjndqIroe8ytdK7WqL9fTzN_9wQeUY2c/assets/index.edc783e1.js:35:10926)
```

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by Neltarionko** [comment]
Have noticed that reseting coordinator helps for a while, but effect is temporary.
