### ISSUE TITLE
Zigbee2mqtt Bug while opining integration

### ISSUE THREAD

**Issue by Jokanaan78** [nurikk/z2m-frontend#1755]
### What happened?

Error while opening zigbee2mqtt integration inside HA

### What browsers are you seeing the problem on?

Microsoft Edge

### Relevant stacktrace

```shell
**Current url**: http://homeassistant.local:8123/api/hassio_ingress/1XeJqOTwDPEF1fqjma5paL-MWJOOehneZwat2ZGfOmo/#/
**Previous url**: http://homeassistant.local:8123/45df7312_zigbee2mqtt


**Error type**: Error
**Error message**: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B0%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.



Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B0%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at ev (http://homeassistant.local:8123/api/hassio_ingress/1XeJqOTwDPEF1fqjma5paL-MWJOOehneZwat2ZGfOmo/assets/index.edc783e1.js:33:45307)
    at d (http://homeassistant.local:8123/api/hassio_ingress/1XeJqOTwDPEF1fqjma5paL-MWJOOehneZwat2ZGfOmo/assets/index.edc783e1.js:33:46936)
    at p (http://homeassistant.local:8123/api/hassio_ingress/1XeJqOTwDPEF1fqjma5paL-MWJOOehneZwat2ZGfOmo/assets/index.edc783e1.js:33:48043)
    at http://homeassistant.local:8123/api/hassio_ingress/1XeJqOTwDPEF1fqjma5paL-MWJOOehneZwat2ZGfOmo/assets/index.edc783e1.js:33:50146
    at Ba (http://homeassistant.local:8123/api/hassio_ingress/1XeJqOTwDPEF1fqjma5paL-MWJOOehneZwat2ZGfOmo/assets/index.edc783e1.js:33:61196)
    at G7 (http://homeassistant.local:8123/api/hassio_ingress/1XeJqOTwDPEF1fqjma5paL-MWJOOehneZwat2ZGfOmo/assets/index.edc783e1.js:37:10528)
    at W7 (http://homeassistant.local:8123/api/hassio_ingress/1XeJqOTwDPEF1fqjma5paL-MWJOOehneZwat2ZGfOmo/assets/index.edc783e1.js:37:955)
    at ORe (http://homeassistant.local:8123/api/hassio_ingress/1XeJqOTwDPEF1fqjma5paL-MWJOOehneZwat2ZGfOmo/assets/index.edc783e1.js:37:881)
    at dh (http://homeassistant.local:8123/api/hassio_ingress/1XeJqOTwDPEF1fqjma5paL-MWJOOehneZwat2ZGfOmo/assets/index.edc783e1.js:37:732)
    at sC (http://homeassistant.local:8123/api/hassio_ingress/1XeJqOTwDPEF1fqjma5paL-MWJOOehneZwat2ZGfOmo/assets/index.edc783e1.js:35:10926)
```

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by Jokanaan78** [comment]
[initialState.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/12048321/initialState.json.zip)

**Comment by Jokanaan78** [comment]
![image](https://github.com/nurikk/zigbee2mqtt-frontend/assets/85512877/fc353cb6-eb07-448d-81d4-951d96ad7104)
