### ISSUE TITLE
Bug zigbee2mqtt

### ISSUE THREAD

**Issue by Doudou-zz** [nurikk/z2m-frontend#1818]
### What happened?

in the OTA page

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: http://192.168.2.2:8080/#/ota
**Previous url**: 


**Error type**: NotFoundError
**Error message**: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.



Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at vq (http://192.168.2.2:8080/assets/index.a9a9dba6.js:35:5613)
    at mNe (http://192.168.2.2:8080/assets/index.a9a9dba6.js:37:3888)
    at e.unstable_runWithPriority (http://192.168.2.2:8080/assets/index.a9a9dba6.js:22:3813)
    at au (http://192.168.2.2:8080/assets/index.a9a9dba6.js:33:38737)
    at Al (http://192.168.2.2:8080/assets/index.a9a9dba6.js:37:1838)
    at zC (http://192.168.2.2:8080/assets/index.a9a9dba6.js:35:11143)
    at http://192.168.2.2:8080/assets/index.a9a9dba6.js:33:38960
    at e.unstable_runWithPriority (http://192.168.2.2:8080/assets/index.a9a9dba6.js:22:3813)
    at au (http://192.168.2.2:8080/assets/index.a9a9dba6.js:33:38737)
    at ZG (http://192.168.2.2:8080/assets/index.a9a9dba6.js:33:38906)
```

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by Doudou-zz** [comment]
[initialState.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/13039955/initialState.json.zip)
![Capture d’écran 2023-10-19 102813](https://github.com/nurikk/zigbee2mqtt-frontend/assets/148436759/777ebb66-ec93-44e2-80f4-f43f4a1cb061)
