### ISSUE TITLE
Zigbee2MQTT bug found

### ISSUE THREAD

**Issue by rc60** [nurikk/z2m-frontend#1824]
### What happened?

On entry to Zigbee2MQTT admin page this bug notification pops up.

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: http://192.168.1.23:8123/api/hassio_ingress/a1ACshgTq95VQky_nkC0QMQiDXJpwQXd82Lmx3VTsc8/#/
**Previous url**: http://192.168.1.23:8123/45df7312_zigbee2mqtt/ingress


**Error type**: NotFoundError
**Error message**: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.



Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at vq (http://192.168.1.23:8123/api/hassio_ingress/a1ACshgTq95VQky_nkC0QMQiDXJpwQXd82Lmx3VTsc8/assets/index.a9a9dba6.js:35:5613)
    at mNe (http://192.168.1.23:8123/api/hassio_ingress/a1ACshgTq95VQky_nkC0QMQiDXJpwQXd82Lmx3VTsc8/assets/index.a9a9dba6.js:37:3888)
    at e.unstable_runWithPriority (http://192.168.1.23:8123/api/hassio_ingress/a1ACshgTq95VQky_nkC0QMQiDXJpwQXd82Lmx3VTsc8/assets/index.a9a9dba6.js:22:3813)
    at au (http://192.168.1.23:8123/api/hassio_ingress/a1ACshgTq95VQky_nkC0QMQiDXJpwQXd82Lmx3VTsc8/assets/index.a9a9dba6.js:33:38737)
    at Al (http://192.168.1.23:8123/api/hassio_ingress/a1ACshgTq95VQky_nkC0QMQiDXJpwQXd82Lmx3VTsc8/assets/index.a9a9dba6.js:37:1838)
    at zC (http://192.168.1.23:8123/api/hassio_ingress/a1ACshgTq95VQky_nkC0QMQiDXJpwQXd82Lmx3VTsc8/assets/index.a9a9dba6.js:35:11143)
    at http://192.168.1.23:8123/api/hassio_ingress/a1ACshgTq95VQky_nkC0QMQiDXJpwQXd82Lmx3VTsc8/assets/index.a9a9dba6.js:33:38960
    at e.unstable_runWithPriority (http://192.168.1.23:8123/api/hassio_ingress/a1ACshgTq95VQky_nkC0QMQiDXJpwQXd82Lmx3VTsc8/assets/index.a9a9dba6.js:22:3813)
    at au (http://192.168.1.23:8123/api/hassio_ingress/a1ACshgTq95VQky_nkC0QMQiDXJpwQXd82Lmx3VTsc8/assets/index.a9a9dba6.js:33:38737)
    at ZG (http://192.168.1.23:8123/api/hassio_ingress/a1ACshgTq95VQky_nkC0QMQiDXJpwQXd82Lmx3VTsc8/assets/index.a9a9dba6.js:33:38906)
```

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by rc60** [comment]
[initialState.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/13178929/initialState.json.zip)
<img width="1039" alt="Screenshot 2023-10-26 071533" src="https://github.com/nurikk/zigbee2mqtt-frontend/assets/576841/dcaf51b3-15fc-4a16-81c9-81a2dbeb1fac">
