### ISSUE TITLE
could not start front end

### ISSUE THREAD

**Issue by bindaz** [nurikk/z2m-frontend#1826]
when I tried to add front end port and host configurations under configuration.yaml it shows error below:

********
pi@homebridge:/opt/zigbee2mqtt $ npm start

> zigbee2mqtt@1.33.2 start
> node index.js

/opt/zigbee2mqtt/node_modules/js-yaml/lib/loader.js:183
  return new YAMLException(message, mark);
         ^
YAMLException: duplicated mapping key (10:1)

  7 |   password: xxx
  8 | serial:
  9 |   port: /dev/ttyACM0
 10 | frontend:
------^
 11 |  port: 8080
 12 |  host: 192.168.68.121
    at generateError (/opt/zigbee2mqtt/node_modules/js-yaml/lib/loader.js:183:10)
    at throwError (/opt/zigbee2mqtt/node_modules/js-yaml/lib/loader.js:187:9)
    at storeMappingPair (/opt/zigbee2mqtt/node_modules/js-yaml/lib/loader.js:358:7)
    at readBlockMapping (/opt/zigbee2mqtt/node_modules/js-yaml/lib/loader.js:1173:9)
    at composeNode (/opt/zigbee2mqtt/node_modules/js-yaml/lib/loader.js:1441:12)
    at readDocument (/opt/zigbee2mqtt/node_modules/js-yaml/lib/loader.js:1625:3)
    at loadDocuments (/opt/zigbee2mqtt/node_modules/js-yaml/lib/loader.js:1688:5)
    at Object.load (/opt/zigbee2mqtt/node_modules/js-yaml/lib/loader.js:1714:19)
    at Object.read (/opt/zigbee2mqtt/lib/util/yaml.ts:7:21)
    at read (/opt/zigbee2mqtt/lib/util/settings.ts:333:20)
pi@homebridge:/opt/zigbee2mqtt $ 
***********

Then I removed the port and host info, and run the npm start again, it shows:
**********
pi@homebridge:/opt/zigbee2mqtt $ npm start

> zigbee2mqtt@1.33.2 start
> node index.js

Zigbee2MQTT:info  2023-11-02 20:10:12: Logging to console and directory: '/opt/zigbee2mqtt/data/log/2023-11-02.20-10-11' filename: log.txt
Zigbee2MQTT:info  2023-11-02 20:10:12: Starting Zigbee2MQTT version 1.33.2 (commit #9996c93)
Zigbee2MQTT:info  2023-11-02 20:10:12: Starting zigbee-herdsman (0.21.0)
Zigbee2MQTT:info  2023-11-02 20:10:16: zigbee-herdsman started (resumed)
Zigbee2MQTT:info  2023-11-02 20:10:16: Coordinator firmware version: '{"meta":{"maintrel":"3 ","majorrel":"6","minorrel":"10","product":8,"revision":"6.10.3.0 build 297"},"type":"EZSP v8"}'
Zigbee2MQTT:info  2023-11-02 20:10:16: Currently 0 devices are joined:
Zigbee2MQTT:info  2023-11-02 20:10:16: Zigbee: disabling joining new devices.
Zigbee2MQTT:info  2023-11-02 20:10:16: Connecting to MQTT server at mqtt://localhost
Zigbee2MQTT:info  2023-11-02 20:10:16: Connected to MQTT server
Zigbee2MQTT:info  2023-11-02 20:10:16: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload '{"state":"online"}'
Zigbee2MQTT:info  2023-11-02 20:10:18: Started frontend on port 0.0.0.0:8080
Zigbee2MQTT:info  2023-11-02 20:10:18: Zigbee2MQTT started!
*********
However, I still cannot get into front end page by entering 0.0.0.0:8080

Please help, thank you!

**Comment by bindaz** [comment]
it's resolved by correcting configuration.yaml
