### ISSUE TITLE
erreur sur zigbee2mqtt

### ISSUE THREAD

**Issue by nicoto94** [nurikk/z2m-frontend#1831]
### What happened?

un bug trouvé

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: http://192.168.1.12:8080/#/ota
**Previous url**: http://192.168.1.12/


**Error type**: NotFoundError
**Error message**: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.



Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at vq (http://192.168.1.12:8080/assets/index.a9a9dba6.js:35:5613)
    at mNe (http://192.168.1.12:8080/assets/index.a9a9dba6.js:37:3888)
    at e.unstable_runWithPriority (http://192.168.1.12:8080/assets/index.a9a9dba6.js:22:3813)
    at au (http://192.168.1.12:8080/assets/index.a9a9dba6.js:33:38737)
    at Al (http://192.168.1.12:8080/assets/index.a9a9dba6.js:37:1838)
    at zC (http://192.168.1.12:8080/assets/index.a9a9dba6.js:35:11143)
    at http://192.168.1.12:8080/assets/index.a9a9dba6.js:33:38960
    at e.unstable_runWithPriority (http://192.168.1.12:8080/assets/index.a9a9dba6.js:22:3813)
    at au (http://192.168.1.12:8080/assets/index.a9a9dba6.js:33:38737)
    at ZG (http://192.168.1.12:8080/assets/index.a9a9dba6.js:33:38906)
```

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by nicoto94** [comment]
Good evening
I haven't had any feedback regarding my bug which put my entire zigbee network out of service!
Could you help me please

**Comment by nicoto94** [comment]
help, help !

**Comment by mundschenk-at** [comment]
You didn't describe what steps lead to the bug or what the actual symptoms were.

**Comment by nicoto94** [comment]
a user helped me out or the fact that I was not able to answer the cause and resolution of the problem
