### ISSUE TITLE
 Hello, you've found a bug. Congratulations

### ISSUE THREAD

**Issue by PerHag** [nurikk/z2m-frontend#1861]
### What happened?

If I write "Sam" (like samsung) in the search field on the device page and then go to Dashboard then I get error. Of i empry the search field then i can go to the dashboard side.
If i go to dashboard side and write anything i het error

On the dashboard side I can read
Hello, you've found a bug. Congratulations!
TypeError
m.toLowerCase is not a function

Samsung mobile A52
Home assistant app not browser

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: http://192.168.1.229:8123/api/hassio_ingress/MrVuZdVVjOlQG9AnxyQtJ7HWsRPhaxdwLDFtzXZHCSw/#/dashboard
**Previous url**: http://192.168.1.229:8123/45df7312_zigbee2mqtt


**Error type**: TypeError
**Error message**: m.toLowerCase is not a function



TypeError: m.toLowerCase is not a function
    at http://192.168.1.229:8123/api/hassio_ingress/MrVuZdVVjOlQG9AnxyQtJ7HWsRPhaxdwLDFtzXZHCSw/assets/index-89f5fdf3.js:99:5680
    at Array.map (<anonymous>)
    at http://192.168.1.229:8123/api/hassio_ingress/MrVuZdVVjOlQG9AnxyQtJ7HWsRPhaxdwLDFtzXZHCSw/assets/index-89f5fdf3.js:99:5671
    at http://192.168.1.229:8123/api/hassio_ingress/MrVuZdVVjOlQG9AnxyQtJ7HWsRPhaxdwLDFtzXZHCSw/assets/index-89f5fdf3.js:99:3159
    at Ykt (http://192.168.1.229:8123/api/hassio_ingress/MrVuZdVVjOlQG9AnxyQtJ7HWsRPhaxdwLDFtzXZHCSw/assets/index-89f5fdf3.js:99:2959)
    at a1t (http://192.168.1.229:8123/api/hassio_ingress/MrVuZdVVjOlQG9AnxyQtJ7HWsRPhaxdwLDFtzXZHCSw/assets/index-89f5fdf3.js:99:3130)
    at h1t (http://192.168.1.229:8123/api/hassio_ingress/MrVuZdVVjOlQG9AnxyQtJ7HWsRPhaxdwLDFtzXZHCSw/assets/index-89f5fdf3.js:99:5589)
    at y2 (http://192.168.1.229:8123/api/hassio_ingress/MrVuZdVVjOlQG9AnxyQtJ7HWsRPhaxdwLDFtzXZHCSw/assets/index-89f5fdf3.js:41:19551)
    at l9 (http://192.168.1.229:8123/api/hassio_ingress/MrVuZdVVjOlQG9AnxyQtJ7HWsRPhaxdwLDFtzXZHCSw/assets/index-89f5fdf3.js:43:44101)
    at i9 (http://192.168.1.229:8123/api/hassio_ingress/MrVuZdVVjOlQG9AnxyQtJ7HWsRPhaxdwLDFtzXZHCSw/assets/index-89f5fdf3.js:43:39819)
```

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by nurikk** [comment]
Hi!
Can you attach complete state.json file from `Settings -> Tools -> Download state` ?
