### ISSUE TITLE
Error when typing new device name in drop down list

### ISSUE THREAD

**Issue by Drewskieza** [nurikk/z2m-frontend#1903]
[###]What happened?

Opened a device
Clicked on the drop down list for device name and started typing

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: http://192.168.1.220:8123/api/hassio_ingress/FlM6rVCroTtNd0djUuWXIrV8QmxpVY_pSaijoY6zlNg/#/device/0x00158d00094204eb/exposes
**Previous url**: http://192.168.1.220:8123/45df7312_zigbee2mqtt


**Error type**: TypeError
**Error message**: Cannot read properties of undefined (reading 'toLowerCase')



TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at http://192.168.1.220:8123/api/hassio_ingress/FlM6rVCroTtNd0djUuWXIrV8QmxpVY_pSaijoY6zlNg/assets/index-83109297.js:1057:45714
    at Array.filter (<anonymous>)
    at http://192.168.1.220:8123/api/hassio_ingress/FlM6rVCroTtNd0djUuWXIrV8QmxpVY_pSaijoY6zlNg/assets/index-83109297.js:1057:45662
    at d2 (http://192.168.1.220:8123/api/hassio_ingress/FlM6rVCroTtNd0djUuWXIrV8QmxpVY_pSaijoY6zlNg/assets/index-83109297.js:41:19551)
    at YF (http://192.168.1.220:8123/api/hassio_ingress/FlM6rVCroTtNd0djUuWXIrV8QmxpVY_pSaijoY6zlNg/assets/index-83109297.js:43:1575)
    at Cq (http://192.168.1.220:8123/api/hassio_ingress/FlM6rVCroTtNd0djUuWXIrV8QmxpVY_pSaijoY6zlNg/assets/index-83109297.js:43:46077)
    at Sq (http://192.168.1.220:8123/api/hassio_ingress/FlM6rVCroTtNd0djUuWXIrV8QmxpVY_pSaijoY6zlNg/assets/index-83109297.js:43:39819)
    at i5e (http://192.168.1.220:8123/api/hassio_ingress/FlM6rVCroTtNd0djUuWXIrV8QmxpVY_pSaijoY6zlNg/assets/index-83109297.js:43:39745)
    at D_ (http://192.168.1.220:8123/api/hassio_ingress/FlM6rVCroTtNd0djUuWXIrV8QmxpVY_pSaijoY6zlNg/assets/index-83109297.js:43:39596)
    at tE (http://192.168.1.220:8123/api/hassio_ingress/FlM6rVCroTtNd0djUuWXIrV8QmxpVY_pSaijoY6zlNg/assets/index-83109297.js:43:35959)
```

### Did you download state.json.zip?

I will attach state.json.zip
([initialState.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/14142074/initialState.json.zip))

**Comment by marcusds** [comment]
Duplicate of #1899
