### ISSUE TITLE
Search for devices using text in the search window.

### ISSUE THREAD

**Issue by MkVsM** [nurikk/z2m-frontend#1910]
### What happened?

[initialState.json (1).zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/14152300/initialState.json.1.zip)
<img width="699" alt="image" src="https://github.com/nurikk/zigbee2mqtt-frontend/assets/124080865/6b4151f0-e8eb-41ff-baea-753187d8f1e0">
I wanted to search for the device using
<img width="173" alt="image" src="https://github.com/nurikk/zigbee2mqtt-frontend/assets/124080865/c95f82eb-46f2-4ebf-90a0-20e6d486843e">

### What browsers are you seeing the problem on?

Microsoft Edge

### Relevant stacktrace

```shell
**Current url**: http://homeassistant.local:8123/api/hassio_ingress/lNetmOPDwwraId-5jrXM0hSkJwIPeuGNw16W09WsHpU/#/device/0xa4c138d7a120d689/info
**Previous url**: http://homeassistant.local:8123/45df7312_zigbee2mqtt


**Error type**: TypeError
**Error message**: Cannot read properties of undefined (reading 'toLowerCase')



TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at http://homeassistant.local:8123/api/hassio_ingress/lNetmOPDwwraId-5jrXM0hSkJwIPeuGNw16W09WsHpU/assets/index-83109297.js:1057:45714
    at Array.filter (<anonymous>)
    at http://homeassistant.local:8123/api/hassio_ingress/lNetmOPDwwraId-5jrXM0hSkJwIPeuGNw16W09WsHpU/assets/index-83109297.js:1057:45662
    at d2 (http://homeassistant.local:8123/api/hassio_ingress/lNetmOPDwwraId-5jrXM0hSkJwIPeuGNw16W09WsHpU/assets/index-83109297.js:41:19551)
    at YF (http://homeassistant.local:8123/api/hassio_ingress/lNetmOPDwwraId-5jrXM0hSkJwIPeuGNw16W09WsHpU/assets/index-83109297.js:43:1575)
    at Cq (http://homeassistant.local:8123/api/hassio_ingress/lNetmOPDwwraId-5jrXM0hSkJwIPeuGNw16W09WsHpU/assets/index-83109297.js:43:46077)
    at Sq (http://homeassistant.local:8123/api/hassio_ingress/lNetmOPDwwraId-5jrXM0hSkJwIPeuGNw16W09WsHpU/assets/index-83109297.js:43:39819)
    at i5e (http://homeassistant.local:8123/api/hassio_ingress/lNetmOPDwwraId-5jrXM0hSkJwIPeuGNw16W09WsHpU/assets/index-83109297.js:43:39745)
    at D_ (http://homeassistant.local:8123/api/hassio_ingress/lNetmOPDwwraId-5jrXM0hSkJwIPeuGNw16W09WsHpU/assets/index-83109297.js:43:39596)
    at tE (http://homeassistant.local:8123/api/hassio_ingress/lNetmOPDwwraId-5jrXM0hSkJwIPeuGNw16W09WsHpU/assets/index-83109297.js:43:35959)
```

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by Drewskieza** [comment]
Refer to #1899
