### ISSUE TITLE
Error While filtering device from device about page

### ISSUE THREAD

**Issue by rabdalov** [nurikk/z2m-frontend#1913]
### What happened?

Error While filtering device from device about page.
Steps to reproduce:
1) in z2m page open device properties
2) click on device title
3) Type in some letter to filter device
4) error!
[initialState.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/14156240/initialState.json.zip)
![z2m_error_2024-02-04_Step_1](https://github.com/nurikk/zigbee2mqtt-frontend/assets/42087220/dc6d721d-7c8a-4e99-b156-c9f6897e77a1)
![z2m_error_2024-02-04_Step_2](https://github.com/nurikk/zigbee2mqtt-frontend/assets/42087220/7a0ee34d-790c-424c-aaa7-e6ec0af88c0d)
![z2m_error_2024-02-04_Step_3](https://github.com/nurikk/zigbee2mqtt-frontend/assets/42087220/7a49c70a-e676-4931-a80d-7f7387ebbbce)

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: https://192.168.0.10:8123/api/hassio_ingress/plmkj_PtDAtOeR6IZeZXU6DSqMErceeUFUo_LiW8p0I/#/device/0x00124b00272b8876/info
**Previous url**: https://192.168.0.10:8123/45df7312_zigbee2mqtt/ingress


**Error type**: TypeError
**Error message**: Cannot read properties of undefined (reading 'toLowerCase')



TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at https://192.168.0.10:8123/api/hassio_ingress/plmkj_PtDAtOeR6IZeZXU6DSqMErceeUFUo_LiW8p0I/assets/index-83109297.js:1057:45714
    at Array.filter (<anonymous>)
    at https://192.168.0.10:8123/api/hassio_ingress/plmkj_PtDAtOeR6IZeZXU6DSqMErceeUFUo_LiW8p0I/assets/index-83109297.js:1057:45662
    at d2 (https://192.168.0.10:8123/api/hassio_ingress/plmkj_PtDAtOeR6IZeZXU6DSqMErceeUFUo_LiW8p0I/assets/index-83109297.js:41:19551)
    at YF (https://192.168.0.10:8123/api/hassio_ingress/plmkj_PtDAtOeR6IZeZXU6DSqMErceeUFUo_LiW8p0I/assets/index-83109297.js:43:1575)
    at Cq (https://192.168.0.10:8123/api/hassio_ingress/plmkj_PtDAtOeR6IZeZXU6DSqMErceeUFUo_LiW8p0I/assets/index-83109297.js:43:46077)
    at Sq (https://192.168.0.10:8123/api/hassio_ingress/plmkj_PtDAtOeR6IZeZXU6DSqMErceeUFUo_LiW8p0I/assets/index-83109297.js:43:39819)
    at i5e (https://192.168.0.10:8123/api/hassio_ingress/plmkj_PtDAtOeR6IZeZXU6DSqMErceeUFUo_LiW8p0I/assets/index-83109297.js:43:39745)
    at D_ (https://192.168.0.10:8123/api/hassio_ingress/plmkj_PtDAtOeR6IZeZXU6DSqMErceeUFUo_LiW8p0I/assets/index-83109297.js:43:39596)
    at tE (https://192.168.0.10:8123/api/hassio_ingress/plmkj_PtDAtOeR6IZeZXU6DSqMErceeUFUo_LiW8p0I/assets/index-83109297.js:43:35959)
```

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by acaminiti** [comment]
Found the same issue, but I sadly opened  it in the wrong [repository](https://github.com/Koenkk/zigbee2mqtt/issues/21218).
