### ISSUE TITLE
BUG NotFoundError Failed to execute 'removeChild' 

### ISSUE THREAD

**Issue by Fiesta77** [nurikk/z2m-frontend#1920]
### What happened?

when I am on Zigbee2mqtt I have the message that appears every minute
NotFoundError
Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at e9 (http://192.168.0.99:8080/assets/index-adb29eee.js:43:26115)
    at ls (http://192.168.0.99:8080/assets/index-adb29eee.js:43:25802)
    at e9 (http://192.168.0.99:8080/assets/index-adb29eee.js:43:26551)
    at ls (http://192.168.0.99:8080/assets/index-adb29eee.js:43:25802)
    at e9 (http://192.168.0.99:8080/assets/index-adb29eee.js:43:26551)
    at oi (http://192.168.0.99:8080/assets/index-adb29eee.js:43:27408)
    at t9 (http://192.168.0.99:8080/assets/index-adb29eee.js:43:27868)
    at oi (http://192.168.0.99:8080/assets/index-adb29eee.js:43:27558)
    at t9 (http://192.168.0.99:8080/assets/index-adb29eee.js:43:30609)
    at oi (http://192.168.0.99:8080/assets/index-adb29eee.js:43:27558)
[initialState.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/14183728/initialState.json.zip)

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: http://192.168.0.99:8080/#/ota
**Previous url**: http://192.168.0.99/


**Error type**: NotFoundError
**Error message**: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.



Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at e9 (http://192.168.0.99:8080/assets/index-adb29eee.js:43:26115)
    at ls (http://192.168.0.99:8080/assets/index-adb29eee.js:43:25802)
    at e9 (http://192.168.0.99:8080/assets/index-adb29eee.js:43:26551)
    at ls (http://192.168.0.99:8080/assets/index-adb29eee.js:43:25802)
    at e9 (http://192.168.0.99:8080/assets/index-adb29eee.js:43:26551)
    at oi (http://192.168.0.99:8080/assets/index-adb29eee.js:43:27408)
    at t9 (http://192.168.0.99:8080/assets/index-adb29eee.js:43:27868)
    at oi (http://192.168.0.99:8080/assets/index-adb29eee.js:43:27558)
    at t9 (http://192.168.0.99:8080/assets/index-adb29eee.js:43:30609)
    at oi (http://192.168.0.99:8080/assets/index-adb29eee.js:43:27558)
```

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by Fiesta77** [comment]
1.35.2 no problème
