### ISSUE TITLE
[Bug]: Frontend is not loadiang

### ISSUE THREAD

**Issue by matthewbartos** [nurikk/z2m-frontend#1960]
### What happened?

I'm unable to load the Zigbee2MQTT UI in Home Assistant both in `1.36.0-1` and the latest `dev` branch:
```Uncaught SyntaxError: Invalid or unexpected token (at index-fb4a4614.js:1:11981)```
<img width="523" alt="image" src="https://github.com/nurikk/zigbee2mqtt-frontend/assets/1921100/fd831512-9970-4e65-ab8c-a7c935f24443">
<img width="208" alt="image" src="https://github.com/nurikk/zigbee2mqtt-frontend/assets/1921100/1c85997c-c823-4d58-b9b2-ff836c4644eb">

Tested on the latest Brave, Google Chrome, Firefox, and Safari. The Mobile Home Assistant app is not loading it as well.

I'm unable to attach the `state.json.zip` as the frontend is broken

Zigbee2MQTT is working, but the frontend is broken completely :/

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### Relevant stacktrace

```shell
Uncaught SyntaxError: Invalid or unexpected token (at index-fb4a4614.js:1:11981)
<img width="523" alt="image" src="https://github.com/nurikk/zigbee2mqtt-frontend/assets/1921100/fd831512-9970-4e65-ab8c-a7c935f24443">
```

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by matthewbartos** [comment]
Duplicate: https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/issues/444
