### ISSUE TITLE
you've found a bug. Congratulations!

### ISSUE THREAD

**Issue by Kakes** [nurikk/z2m-frontend#1966]
### What happened?

Hello, you've found a bug. Congratulations!
Calm down
[Click here, and save this file](https://bcnt0oxpgp5pjxum9281b6vilxgguddt.ui.nabu.casa/api/hassio_ingress/KHvbpxqhkuMFYzOPWwbg5YJUg6y6q2LnkZzIDb7-FdA/#)
[Raise a github issue](https://github.com/nurikk/zigbee2mqtt-frontend/issues/new?template=bug_report.yaml&stacktracke=**Current+url**%3A+https%3A%2F%2Fbcnt0oxpgp5pjxum9281b6vilxgguddt.ui.nabu.casa%2Fapi%2Fhassio_ingress%2FKHvbpxqhkuMFYzOPWwbg5YJUg6y6q2LnkZzIDb7-FdA%2F%23%2F%0A**Previous+url**%3A+https%3A%2F%2Fbcnt0oxpgp5pjxum9281b6vilxgguddt.ui.nabu.casa%2F45df7312_zigbee2mqtt%0A%0A%0A**Error+type**%3A+NotFoundError%0A**Error+message**%3A+Failed+to+execute+%27removeChild%27+on+%27Node%27%3A+The+node+to+be+removed+is+not+a+child+of+this+node.%0A%0A%0A%0AError%3A+Failed+to+execute+%27removeChild%27+on+%27Node%27%3A+The+node+to+be+removed+is+not+a+child+of+this+node.%0A++++at+hq+%28https%3A%2F%2Fbcnt0oxpgp5pjxum9281b6vilxgguddt.ui.nabu.casa%2Fapi%2Fhassio_ingress%2FKHvbpxqhkuMFYzOPWwbg5YJUg6y6q2LnkZzIDb7-FdA%2Fassets%2Findex-4b582892.js%3A43%3A26115%29%0A++++at+fs+%28https%3A%2F%2Fbcnt0oxpgp5pjxum9281b6vilxgguddt.ui.nabu.casa%2Fapi%2Fhassio_ingress%2FKHvbpxqhkuMFYzOPWwbg5YJUg6y6q2LnkZzIDb7-FdA%2Fassets%2Findex-4b582892.js%3A43%3A25802%29%0A++++at+hq+%28https%3A%2F%2Fbcnt0oxpgp5pjxum9281b6vilxgguddt.ui.nabu.casa%2Fapi%2Fhassio_ingress%2FKHvbpxqhkuMFYzOPWwbg5YJUg6y6q2LnkZzIDb7-FdA%2Fassets%2Findex-4b582892.js%3A43%3A26551%29%0A++++at+fs+%28https%3A%2F%2Fbcnt0oxpgp5pjxum9281b6vilxgguddt.ui.nabu.casa%2Fapi%2Fhassio_ingress%2FKHvbpxqhkuMFYzOPWwbg5YJUg6y6q2LnkZzIDb7-FdA%2Fassets%2Findex-4b582892.js%3A43%3A25802%29%0A++++at+hq+%28https%3A%2F%2Fbcnt0oxpgp5pjxum9281b6vilxgguddt.ui.nabu.casa%2Fapi%2Fhassio_ingress%2FKHvbpxqhkuMFYzOPWwbg5YJUg6y6q2LnkZzIDb7-FdA%2Fassets%2Findex-4b582892.js%3A43%3A26551%29%0A++++at+di+%28https%3A%2F%2Fbcnt0oxpgp5pjxum9281b6vilxgguddt.ui.nabu.casa%2Fapi%2Fhassio_ingress%2FKHvbpxqhkuMFYzOPWwbg5YJUg6y6q2LnkZzIDb7-FdA%2Fassets%2Findex-4b582892.js%3A43%3A27408%29%0A++++at+pq+%28https%3A%2F%2Fbcnt0oxpgp5pjxum9281b6vilxgguddt.ui.nabu.casa%2Fapi%2Fhassio_ingress%2FKHvbpxqhkuMFYzOPWwbg5YJUg6y6q2LnkZzIDb7-FdA%2Fassets%2Findex-4b582892.js%3A43%3A27868%29%0A++++at+di+%28https%3A%2F%2Fbcnt0oxpgp5pjxum9281b6vilxgguddt.ui.nabu.casa%2Fapi%2Fhassio_ingress%2FKHvbpxqhkuMFYzOPWwbg5YJUg6y6q2LnkZzIDb7-FdA%2Fassets%2Findex-4b582892.js%3A43%3A27558%29%0A++++at+pq+%28https%3A%2F%2Fbcnt0oxpgp5pjxum9281b6vilxgguddt.ui.nabu.casa%2Fapi%2Fhassio_ingress%2FKHvbpxqhkuMFYzOPWwbg5YJUg6y6q2LnkZzIDb7-FdA%2Fassets%2Findex-4b582892.js%3A43%3A30609%29%0A++++at+di+%28https%3A%2F%2Fbcnt0oxpgp5pjxum9281b6vilxgguddt.ui.nabu.casa%2Fapi%2Fhassio_ingress%2FKHvbpxqhkuMFYzOPWwbg5YJUg6y6q2LnkZzIDb7-FdA%2Fassets%2Findex-4b582892.js%3A43%3A27558%29), attach previously downloaded file
Take a screenshot of this page and attach to the issue
In the github issue write detailed description for the issue, how this happened? Steps to reproduce

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: https://bcnt0oxpgp5pjxum9281b6vilxgguddt.ui.nabu.casa/api/hassio_ingress/KHvbpxqhkuMFYzOPWwbg5YJUg6y6q2LnkZzIDb7-FdA/#/
**Previous url**: https://bcnt0oxpgp5pjxum9281b6vilxgguddt.ui.nabu.casa/45df7312_zigbee2mqtt


**Error type**: NotFoundError
**Error message**: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.



Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at hq (https://bcnt0oxpgp5pjxum9281b6vilxgguddt.ui.nabu.casa/api/hassio_ingress/KHvbpxqhkuMFYzOPWwbg5YJUg6y6q2LnkZzIDb7-FdA/assets/index-4b582892.js:43:26115)
    at fs (https://bcnt0oxpgp5pjxum9281b6vilxgguddt.ui.nabu.casa/api/hassio_ingress/KHvbpxqhkuMFYzOPWwbg5YJUg6y6q2LnkZzIDb7-FdA/assets/index-4b582892.js:43:25802)
    at hq (https://bcnt0oxpgp5pjxum9281b6vilxgguddt.ui.nabu.casa/api/hassio_ingress/KHvbpxqhkuMFYzOPWwbg5YJUg6y6q2LnkZzIDb7-FdA/assets/index-4b582892.js:43:26551)
    at fs (https://bcnt0oxpgp5pjxum9281b6vilxgguddt.ui.nabu.casa/api/hassio_ingress/KHvbpxqhkuMFYzOPWwbg5YJUg6y6q2LnkZzIDb7-FdA/assets/index-4b582892.js:43:25802)
    at hq (https://bcnt0oxpgp5pjxum9281b6vilxgguddt.ui.nabu.casa/api/hassio_ingress/KHvbpxqhkuMFYzOPWwbg5YJUg6y6q2LnkZzIDb7-FdA/assets/index-4b582892.js:43:26551)
    at di (https://bcnt0oxpgp5pjxum9281b6vilxgguddt.ui.nabu.casa/api/hassio_ingress/KHvbpxqhkuMFYzOPWwbg5YJUg6y6q2LnkZzIDb7-FdA/assets/index-4b582892.js:43:27408)
    at pq (https://bcnt0oxpgp5pjxum9281b6vilxgguddt.ui.nabu.casa/api/hassio_ingress/KHvbpxqhkuMFYzOPWwbg5YJUg6y6q2LnkZzIDb7-FdA/assets/index-4b582892.js:43:27868)
    at di (https://bcnt0oxpgp5pjxum9281b6vilxgguddt.ui.nabu.casa/api/hassio_ingress/KHvbpxqhkuMFYzOPWwbg5YJUg6y6q2LnkZzIDb7-FdA/assets/index-4b582892.js:43:27558)
    at pq (https://bcnt0oxpgp5pjxum9281b6vilxgguddt.ui.nabu.casa/api/hassio_ingress/KHvbpxqhkuMFYzOPWwbg5YJUg6y6q2LnkZzIDb7-FdA/assets/index-4b582892.js:43:30609)
    at di (https://bcnt0oxpgp5pjxum9281b6vilxgguddt.ui.nabu.casa/api/hassio_ingress/KHvbpxqhkuMFYzOPWwbg5YJUg6y6q2LnkZzIDb7-FdA/assets/index-4b582892.js:43:27558)
```

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by S33G** [comment]
Some similarity to this?

https://github.com/nurikk/zigbee2mqtt-frontend/issues/1956

**Comment by Kakes** [comment]
Yes it looks the same
I am not familiar with this kind of problems
sorry

Op di 2 apr 2024 om 13:16 schreef Seige ***@***.***>:
