### ISSUE TITLE
n.map is not a function TypeError: n.map is not a function

### ISSUE THREAD

**Issue by mak27arr** [nurikk/z2m-frontend#2031]
### What happened?

TypeError
n.map is not a function
TypeError: n.map is not a function
    at Ct (http://192.168.88.81:8123/api/hassio_ingress/tIsX3YRfPsV_sXJKE8rWdDBicw_WLzEhdW8g08dbrVs/assets/DashboardFeatureWrapper-fb959ba4.js:1:17943)
    at gT (http://192.168.88.81:8123/api/hassio_ingress/tIsX3YRfPsV_sXJKE8rWdDBicw_WLzEhdW8g08dbrVs/assets/index-856ac473.js:41:19531)
    at X5 (http://192.168.88.81:8123/api/hassio_ingress/tIsX3YRfPsV_sXJKE8rWdDBicw_WLzEhdW8g08dbrVs/assets/index-856ac473.js:43:44006)
    at Z5 (http://192.168.88.81:8123/api/hassio_ingress/tIsX3YRfPsV_sXJKE8rWdDBicw_WLzEhdW8g08dbrVs/assets/index-856ac473.js:43:39756)
    at ATe (http://192.168.88.81:8123/api/hassio_ingress/tIsX3YRfPsV_sXJKE8rWdDBicw_WLzEhdW8g08dbrVs/assets/index-856ac473.js:43:39682)
    at ap (http://192.168.88.81:8123/api/hassio_ingress/tIsX3YRfPsV_sXJKE8rWdDBicw_WLzEhdW8g08dbrVs/assets/index-856ac473.js:43:39534)
    at ub (http://192.168.88.81:8123/api/hassio_ingress/tIsX3YRfPsV_sXJKE8rWdDBicw_WLzEhdW8g08dbrVs/assets/index-856ac473.js:43:35900)
    at SD (http://192.168.88.81:8123/api/hassio_ingress/tIsX3YRfPsV_sXJKE8rWdDBicw_WLzEhdW8g08dbrVs/assets/index-856ac473.js:43:36704)
    at Gn (http://192.168.88.81:8123/api/hassio_ingress/tIsX3YRfPsV_sXJKE8rWdDBicw_WLzEhdW8g08dbrVs/assets/index-856ac473.js:41:3283)
    at http://192.168.88.81:8123/api/hassio_ingress/tIsX3YRfPsV_sXJKE8rWdDBicw_WLzEhdW8g08dbrVs/assets/index-856ac473.js:43:34230

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: http://192.168.88.81:8123/api/hassio_ingress/tIsX3YRfPsV_sXJKE8rWdDBicw_WLzEhdW8g08dbrVs/#/device/0x842e14fffefed988/exposes
**Previous url**: http://192.168.88.81:8123/45df7312_zigbee2mqtt


**Error type**: TypeError
**Error message**: n.map is not a function



TypeError: n.map is not a function
    at Ct (http://192.168.88.81:8123/api/hassio_ingress/tIsX3YRfPsV_sXJKE8rWdDBicw_WLzEhdW8g08dbrVs/assets/DashboardFeatureWrapper-fb959ba4.js:1:17943)
    at gT (http://192.168.88.81:8123/api/hassio_ingress/tIsX3YRfPsV_sXJKE8rWdDBicw_WLzEhdW8g08dbrVs/assets/index-856ac473.js:41:19531)
    at X5 (http://192.168.88.81:8123/api/hassio_ingress/tIsX3YRfPsV_sXJKE8rWdDBicw_WLzEhdW8g08dbrVs/assets/index-856ac473.js:43:44006)
    at Z5 (http://192.168.88.81:8123/api/hassio_ingress/tIsX3YRfPsV_sXJKE8rWdDBicw_WLzEhdW8g08dbrVs/assets/index-856ac473.js:43:39756)
    at ATe (http://192.168.88.81:8123/api/hassio_ingress/tIsX3YRfPsV_sXJKE8rWdDBicw_WLzEhdW8g08dbrVs/assets/index-856ac473.js:43:39682)
    at ap (http://192.168.88.81:8123/api/hassio_ingress/tIsX3YRfPsV_sXJKE8rWdDBicw_WLzEhdW8g08dbrVs/assets/index-856ac473.js:43:39534)
    at ub (http://192.168.88.81:8123/api/hassio_ingress/tIsX3YRfPsV_sXJKE8rWdDBicw_WLzEhdW8g08dbrVs/assets/index-856ac473.js:43:35900)
    at SD (http://192.168.88.81:8123/api/hassio_ingress/tIsX3YRfPsV_sXJKE8rWdDBicw_WLzEhdW8g08dbrVs/assets/index-856ac473.js:43:36704)
    at Gn (http://192.168.88.81:8123/api/hassio_ingress/tIsX3YRfPsV_sXJKE8rWdDBicw_WLzEhdW8g08dbrVs/assets/index-856ac473.js:41:3283)
    at http://192.168.88.81:8123/api/hassio_ingress/tIsX3YRfPsV_sXJKE8rWdDBicw_WLzEhdW8g08dbrVs/assets/index-856ac473.js:43:34230
```

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by LaurentChardin** [comment]
Hi

Can you describe on which view you were ? It seems you were on the `exposes` tab of a `device`, is that correct ? or where you trying to display the `dashboard` ?

Best,
