### ISSUE TITLE
_TZE204_o9gyszw2 2 GANGS DIMMER reporting Cluster NULL

### ISSUE THREAD

**Issue by menzbenz-jeedom** [nurikk/z2m-frontend#2034]
### What happened?

Hello, 
Recently i bought the Zigbee 2 channels Dimmer ['_TZE204_o9gyszw2'](https://www.zigbee2mqtt.io/devices/ZDMS16-2.html#avatto-zdms16-2)
I noticed that there is not cluster linked the endpoint 1 and 2 . 

![image](https://github.com/nurikk/zigbee2mqtt-frontend/assets/122239803/3271c010-b887-464c-bd2c-48751e2b2200)

And in the Dev console tab, just after choosing the end point I1, this error appears 

![image](https://github.com/nurikk/zigbee2mqtt-frontend/assets/122239803/a841e458-2ffa-400e-b1e7-24e3ba5dfea1)

Have you any idea about what happening please ? 

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: http://192.168.1.100:8080/#/device/0xa4c138b2c9d5e6c8/dev-console
**Previous url**: http://192.168.1.100/


**Error type**: TypeError
**Error message**: Cannot read properties of undefined (reading 'clusters')



TypeError: Cannot read properties of undefined (reading 'clusters')
    at zs.render (http://192.168.1.100:8080/assets/ConnectedDevicePage-096eea88.js:1:30966)
    at ab (http://192.168.1.100:8080/assets/index-3cebf61c.js:43:6186)
    at yD (http://192.168.1.100:8080/assets/index-3cebf61c.js:43:5982)
    at r3 (http://192.168.1.100:8080/assets/index-3cebf61c.js:43:44865)
    at e3 (http://192.168.1.100:8080/assets/index-3cebf61c.js:43:39756)
    at ITe (http://192.168.1.100:8080/assets/index-3cebf61c.js:43:39682)
    at ap (http://192.168.1.100:8080/assets/index-3cebf61c.js:43:39534)
    at cb (http://192.168.1.100:8080/assets/index-3cebf61c.js:43:35900)
    at CD (http://192.168.1.100:8080/assets/index-3cebf61c.js:43:36704)
    at Gn (http://192.168.1.100:8080/assets/index-3cebf61c.js:41:3283)
```

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by menzbenz-jeedom** [comment]
Hello, 
I would like to add, I tested Z2M in DEV(BETA) mode, it is not better.
Thank you

**Comment by menzbenz-jeedom** [comment]
Hello, 
Someone can help please?
Thank you
