### ISSUE TITLE
crash during interview a property 

### ISSUE THREAD

**Issue by theDontKnowGuy** [nurikk/z2m-frontend#2043]
### What happened?

Tried read a property from [TS0601_dimmer_4](https://www.zigbee2mqtt.io/devices/TS0601_dimmer_4.html#tuya-ts0601_dimmer_4)
Just selected one property from the dev tab.

<img width="1198" alt="image" src="https://github.com/nurikk/zigbee2mqtt-frontend/assets/40746333/3d4578be-11c3-4c7b-954e-2c14fe374cd3">

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: https://myhome.gideoni.com:8123/api/hassio_ingress/G9K2zP2FxsRzXzwtgVyE9oktdJXJK6I0UkNKTO12xf4/#/device/0xb0c7defffe5c6b27/dev-console
**Previous url**: https://myhome.gideoni.com:8123/45df7312_zigbee2mqtt/ingress


**Error type**: TypeError
**Error message**: Cannot read properties of undefined (reading 'clusters')



TypeError: Cannot read properties of undefined (reading 'clusters')
    at zs.render (https://myhome.gideoni.com:8123/api/hassio_ingress/G9K2zP2FxsRzXzwtgVyE9oktdJXJK6I0UkNKTO12xf4/assets/ConnectedDevicePage-096eea88.js:1:30966)
    at ab (https://myhome.gideoni.com:8123/api/hassio_ingress/G9K2zP2FxsRzXzwtgVyE9oktdJXJK6I0UkNKTO12xf4/assets/index-3cebf61c.js:43:6186)
    at yD (https://myhome.gideoni.com:8123/api/hassio_ingress/G9K2zP2FxsRzXzwtgVyE9oktdJXJK6I0UkNKTO12xf4/assets/index-3cebf61c.js:43:5982)
    at r3 (https://myhome.gideoni.com:8123/api/hassio_ingress/G9K2zP2FxsRzXzwtgVyE9oktdJXJK6I0UkNKTO12xf4/assets/index-3cebf61c.js:43:44865)
    at e3 (https://myhome.gideoni.com:8123/api/hassio_ingress/G9K2zP2FxsRzXzwtgVyE9oktdJXJK6I0UkNKTO12xf4/assets/index-3cebf61c.js:43:39756)
    at ITe (https://myhome.gideoni.com:8123/api/hassio_ingress/G9K2zP2FxsRzXzwtgVyE9oktdJXJK6I0UkNKTO12xf4/assets/index-3cebf61c.js:43:39682)
    at ap (https://myhome.gideoni.com:8123/api/hassio_ingress/G9K2zP2FxsRzXzwtgVyE9oktdJXJK6I0UkNKTO12xf4/assets/index-3cebf61c.js:43:39534)
    at cb (https://myhome.gideoni.com:8123/api/hassio_ingress/G9K2zP2FxsRzXzwtgVyE9oktdJXJK6I0UkNKTO12xf4/assets/index-3cebf61c.js:43:35900)
    at CD (https://myhome.gideoni.com:8123/api/hassio_ingress/G9K2zP2FxsRzXzwtgVyE9oktdJXJK6I0UkNKTO12xf4/assets/index-3cebf61c.js:43:36704)
    at Gn (https://myhome.gideoni.com:8123/api/hassio_ingress/G9K2zP2FxsRzXzwtgVyE9oktdJXJK6I0UkNKTO12xf4/assets/index-3cebf61c.js:41:3283)
```

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by theDontKnowGuy** [comment]
[
[Uploading Zigbee2MQTT Home Assistant.html.zip…]()
](url)
