### ISSUE TITLE
Error while select other Cluster than 1,2,3 or 242

### ISSUE THREAD

**Issue by jlmpenedo** [nurikk/z2m-frontend#2046]
### What happened?

I'm new at z2m. I was at Console tab and tried to select a cluster that was not 1,2,3 or 242. The cluster that I tried to select any other cluster like "left" then it pop-up a screen. I couldn´t download the screen asked for, the link doesn´t download anything to me.
![image](https://github.com/nurikk/zigbee2mqtt-frontend/assets/66880187/87a6ea20-fe3d-47cb-8fe6-8724b447c04d)

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: http://homeassistant.local:8123/api/hassio_ingress/O5LtmXJLZ0Njs2k3jA-wVcgoOd6P-5iR7payf8Ej4xU/#/device/0xa4c138405fb8203c/dev-console
**Previous url**: http://homeassistant.local:8123/45df7312_zigbee2mqtt/ingress


**Error type**: TypeError
**Error message**: Cannot read properties of undefined (reading 'clusters')



TypeError: Cannot read properties of undefined (reading 'clusters')
    at zs.render (http://homeassistant.local:8123/api/hassio_ingress/O5LtmXJLZ0Njs2k3jA-wVcgoOd6P-5iR7payf8Ej4xU/assets/ConnectedDevicePage-096eea88.js:1:30966)
    at ab (http://homeassistant.local:8123/api/hassio_ingress/O5LtmXJLZ0Njs2k3jA-wVcgoOd6P-5iR7payf8Ej4xU/assets/index-3cebf61c.js:43:6186)
    at yD (http://homeassistant.local:8123/api/hassio_ingress/O5LtmXJLZ0Njs2k3jA-wVcgoOd6P-5iR7payf8Ej4xU/assets/index-3cebf61c.js:43:5982)
    at r3 (http://homeassistant.local:8123/api/hassio_ingress/O5LtmXJLZ0Njs2k3jA-wVcgoOd6P-5iR7payf8Ej4xU/assets/index-3cebf61c.js:43:44865)
    at e3 (http://homeassistant.local:8123/api/hassio_ingress/O5LtmXJLZ0Njs2k3jA-wVcgoOd6P-5iR7payf8Ej4xU/assets/index-3cebf61c.js:43:39756)
    at ITe (http://homeassistant.local:8123/api/hassio_ingress/O5LtmXJLZ0Njs2k3jA-wVcgoOd6P-5iR7payf8Ej4xU/assets/index-3cebf61c.js:43:39682)
    at ap (http://homeassistant.local:8123/api/hassio_ingress/O5LtmXJLZ0Njs2k3jA-wVcgoOd6P-5iR7payf8Ej4xU/assets/index-3cebf61c.js:43:39534)
    at cb (http://homeassistant.local:8123/api/hassio_ingress/O5LtmXJLZ0Njs2k3jA-wVcgoOd6P-5iR7payf8Ej4xU/assets/index-3cebf61c.js:43:35900)
    at CD (http://homeassistant.local:8123/api/hassio_ingress/O5LtmXJLZ0Njs2k3jA-wVcgoOd6P-5iR7payf8Ej4xU/assets/index-3cebf61c.js:43:36704)
    at Gn (http://homeassistant.local:8123/api/hassio_ingress/O5LtmXJLZ0Njs2k3jA-wVcgoOd6P-5iR7payf8Ej4xU/assets/index-3cebf61c.js:41:3283)
```

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by jlmpenedo** [comment]
![image](https://github.com/nurikk/zigbee2mqtt-frontend/assets/66880187/93d72036-7df8-43da-8018-78da96822c1d)
the rigth screenshot
