### ISSUE TITLE
Frient Air Quality Sensor not supported

### ISSUE THREAD

**Issue by OHNewbee** [nurikk/z2m-frontend#2055]
### What happened?

TypeError
Cannot read properties of undefined (reading 'clusters')
TypeError: Cannot read properties of undefined (reading 'clusters')
    at zs.render (http://192.168.178.250:8081/assets/ConnectedDevicePage-096eea88.js:1:30966)
    at ab (http://192.168.178.250:8081/assets/index-3cebf61c.js:43:6186)
    at yD (http://192.168.178.250:8081/assets/index-3cebf61c.js:43:5982)
    at r3 (http://192.168.178.250:8081/assets/index-3cebf61c.js:43:44865)
    at e3 (http://192.168.178.250:8081/assets/index-3cebf61c.js:43:39756)
    at ITe (http://192.168.178.250:8081/assets/index-3cebf61c.js:43:39682)
    at ap (http://192.168.178.250:8081/assets/index-3cebf61c.js:43:39534)
    at cb (http://192.168.178.250:8081/assets/index-3cebf61c.js:43:35900)
    at CD (http://192.168.178.250:8081/assets/index-3cebf61c.js:43:36704)
    at Gn (http://192.168.178.250:8081/assets/index-3cebf61c.js:41:3283)
![Screenshot_20240623-124058](https://github.com/nurikk/zigbee2mqtt-frontend/assets/97526727/23f5fe98-665a-4bae-9c46-348ca895249a)
![Screenshot_20240623-123946](https://github.com/nurikk/zigbee2mqtt-frontend/assets/97526727/2c72e477-0e01-492d-b97a-42b7ea6bcfed)

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: http://192.168.178.250:8081/#/device/0x0015bc0036001da4/dev-console
**Previous url**: 


**Error type**: TypeError
**Error message**: Cannot read properties of undefined (reading 'clusters')



TypeError: Cannot read properties of undefined (reading 'clusters')
    at zs.render (http://192.168.178.250:8081/assets/ConnectedDevicePage-096eea88.js:1:30966)
    at ab (http://192.168.178.250:8081/assets/index-3cebf61c.js:43:6186)
    at yD (http://192.168.178.250:8081/assets/index-3cebf61c.js:43:5982)
    at r3 (http://192.168.178.250:8081/assets/index-3cebf61c.js:43:44865)
    at e3 (http://192.168.178.250:8081/assets/index-3cebf61c.js:43:39756)
    at ITe (http://192.168.178.250:8081/assets/index-3cebf61c.js:43:39682)
    at ap (http://192.168.178.250:8081/assets/index-3cebf61c.js:43:39534)
    at cb (http://192.168.178.250:8081/assets/index-3cebf61c.js:43:35900)
    at CD (http://192.168.178.250:8081/assets/index-3cebf61c.js:43:36704)
    at Gn (http://192.168.178.250:8081/assets/index-3cebf61c.js:41:3283)
```

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by OHNewbee** [comment]
ONE product must be selected for teaching. NOT all products may be selected for teaching.
