### ISSUE TITLE
Blinds failed interview

### ISSUE THREAD

**Issue by 67jeffh** [nurikk/z2m-frontend#2067]
### What happened?

Trying to pair by roller blinds they both (I have 2) failed the interview.  They worked under ZHA.

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: http://homeassistant.local:8123/api/hassio_ingress/E1KL0jCeW6NGczAaUE76y-OoFIvz9PxfoI9beiH8pyo/#/device/0xcc86ecfffebb7f02/dev-console
**Previous url**: http://homeassistant.local:8123/45df7312_zigbee2mqtt


**Error type**: TypeError
**Error message**: Cannot read properties of undefined (reading 'clusters')



TypeError: Cannot read properties of undefined (reading 'clusters')
    at zs.render (http://homeassistant.local:8123/api/hassio_ingress/E1KL0jCeW6NGczAaUE76y-OoFIvz9PxfoI9beiH8pyo/assets/ConnectedDevicePage-e3a64b21.js:1:30966)
    at ab (http://homeassistant.local:8123/api/hassio_ingress/E1KL0jCeW6NGczAaUE76y-OoFIvz9PxfoI9beiH8pyo/assets/index-e24b99e4.js:43:6186)
    at yD (http://homeassistant.local:8123/api/hassio_ingress/E1KL0jCeW6NGczAaUE76y-OoFIvz9PxfoI9beiH8pyo/assets/index-e24b99e4.js:43:5982)
    at r3 (http://homeassistant.local:8123/api/hassio_ingress/E1KL0jCeW6NGczAaUE76y-OoFIvz9PxfoI9beiH8pyo/assets/index-e24b99e4.js:43:44865)
    at e3 (http://homeassistant.local:8123/api/hassio_ingress/E1KL0jCeW6NGczAaUE76y-OoFIvz9PxfoI9beiH8pyo/assets/index-e24b99e4.js:43:39756)
    at ITe (http://homeassistant.local:8123/api/hassio_ingress/E1KL0jCeW6NGczAaUE76y-OoFIvz9PxfoI9beiH8pyo/assets/index-e24b99e4.js:43:39682)
    at ap (http://homeassistant.local:8123/api/hassio_ingress/E1KL0jCeW6NGczAaUE76y-OoFIvz9PxfoI9beiH8pyo/assets/index-e24b99e4.js:43:39534)
    at cb (http://homeassistant.local:8123/api/hassio_ingress/E1KL0jCeW6NGczAaUE76y-OoFIvz9PxfoI9beiH8pyo/assets/index-e24b99e4.js:43:35900)
    at CD (http://homeassistant.local:8123/api/hassio_ingress/E1KL0jCeW6NGczAaUE76y-OoFIvz9PxfoI9beiH8pyo/assets/index-e24b99e4.js:43:36704)
    at Gn (http://homeassistant.local:8123/api/hassio_ingress/E1KL0jCeW6NGczAaUE76y-OoFIvz9PxfoI9beiH8pyo/assets/index-e24b99e4.js:41:3283)
```

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by 67jeffh** [comment]
This is the info that is in ZHA:

Device info
TS0601
by _TZE200_zuz7f94z
Firmware: 0x00000048
Zigbee info
IEEE: 84:ba:20:ff:fe:85:d5:f8
Nwk: 0x34b1
Device Type: EndDevice
LQI: 188
RSSI: -53
Last Seen: 2024-07-26T11:47:07
Power Source: Battery or Unknown
Quirk: zhaquirks.tuya.ts0601_cover.TuyaMoesCover0601_inv_position
