### ISSUE TITLE
hue bloom zigbee2mqtt lci011

### ISSUE THREAD

**Issue by deveylder** [nurikk/z2m-frontend#2070]
### What happened?

pairing hue bloom lci011 to zigbee2mqtt (ember) not working.

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: https://ha/api/hassio_ingress/QF5lzPqBHRthOrDMrcNYXch1wrL5EhVdbM9EWBYMkBs/#/device/0x00178801001dea6c/dev-console
**Previous url**: https://ha/45df7312_zigbee2mqtt


**Error type**: TypeError
**Error message**: Cannot read properties of undefined (reading 'clusters')



TypeError: Cannot read properties of undefined (reading 'clusters')
    at zs.render (https://ha/api/hassio_ingress/QF5lzPqBHRthOrDMrcNYXch1wrL5EhVdbM9EWBYMkBs/assets/ConnectedDevicePage-e3a64b21.js:1:30966)
    at ab (https://ha/api/hassio_ingress/QF5lzPqBHRthOrDMrcNYXch1wrL5EhVdbM9EWBYMkBs/assets/index-e24b99e4.js:43:6186)
    at yD (https://ha/api/hassio_ingress/QF5lzPqBHRthOrDMrcNYXch1wrL5EhVdbM9EWBYMkBs/assets/index-e24b99e4.js:43:5982)
    at r3 (https://ha/api/hassio_ingress/QF5lzPqBHRthOrDMrcNYXch1wrL5EhVdbM9EWBYMkBs/assets/index-e24b99e4.js:43:44865)
    at e3 (https://ha/api/hassio_ingress/QF5lzPqBHRthOrDMrcNYXch1wrL5EhVdbM9EWBYMkBs/assets/index-e24b99e4.js:43:39756)
    at ITe (https://ha/api/hassio_ingress/QF5lzPqBHRthOrDMrcNYXch1wrL5EhVdbM9EWBYMkBs/assets/index-e24b99e4.js:43:39682)
    at ap (https://ha/api/hassio_ingress/QF5lzPqBHRthOrDMrcNYXch1wrL5EhVdbM9EWBYMkBs/assets/index-e24b99e4.js:43:39534)
    at cb (https://ha/api/hassio_ingress/QF5lzPqBHRthOrDMrcNYXch1wrL5EhVdbM9EWBYMkBs/assets/index-e24b99e4.js:43:35900)
    at CD (https://ha/api/hassio_ingress/QF5lzPqBHRthOrDMrcNYXch1wrL5EhVdbM9EWBYMkBs/assets/index-e24b99e4.js:43:36704)
    at Gn (https://ha/api/hassio_ingress/QF5lzPqBHRthOrDMrcNYXch1wrL5EhVdbM9EWBYMkBs/assets/index-e24b99e4.js:41:3283)
```

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by deveylder** [comment]
cannot generate "safe file"  does nothing
