### ISSUE TITLE
WHATS GOING ON?

### ISSUE THREAD

**Issue by iTMC94** [nurikk/z2m-frontend#2104]
### What happened?

<img width="1435" alt="Bildschirmfoto 2024-08-21 um 01 45 43" src="https://github.com/user-attachments/assets/3009e491-35b9-49ef-af68-ffd0a26c26de">

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: http://192.168.2.250:8123/api/hassio_ingress/23Do2nQ72PgE7EzMGKnk1rPouf_bEkU01nthtZm8mjU/#/settings/settings
**Previous url**: http://192.168.2.250:8123/hassio/addon/8c77aaed_zigbee2mqtt/info


**Error type**: TypeError
**Error message**: Cannot convert undefined or null to object



TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at r (http://192.168.2.250:8123/api/hassio_ingress/23Do2nQ72PgE7EzMGKnk1rPouf_bEkU01nthtZm8mjU/assets/index-74e84a13.js:62:9430)
    at r (http://192.168.2.250:8123/api/hassio_ingress/23Do2nQ72PgE7EzMGKnk1rPouf_bEkU01nthtZm8mjU/assets/index-74e84a13.js:62:9492)
    at P6e (http://192.168.2.250:8123/api/hassio_ingress/23Do2nQ72PgE7EzMGKnk1rPouf_bEkU01nthtZm8mjU/assets/index-74e84a13.js:62:9532)
    at Se.onSettingsSave [as onSubmit] (http://192.168.2.250:8123/api/hassio_ingress/23Do2nQ72PgE7EzMGKnk1rPouf_bEkU01nthtZm8mjU/assets/index-3a8e477d.js:1:8632)
    at e.<anonymous> (http://192.168.2.250:8123/api/hassio_ingress/23Do2nQ72PgE7EzMGKnk1rPouf_bEkU01nthtZm8mjU/assets/bootstrap-5.esm-672cb437.js:11:47737)
    at lD (http://192.168.2.250:8123/api/hassio_ingress/23Do2nQ72PgE7EzMGKnk1rPouf_bEkU01nthtZm8mjU/assets/index-74e84a13.js:41:9885)
    at zD (http://192.168.2.250:8123/api/hassio_ingress/23Do2nQ72PgE7EzMGKnk1rPouf_bEkU01nthtZm8mjU/assets/index-74e84a13.js:43:31876)
    at Q5 (http://192.168.2.250:8123/api/hassio_ingress/23Do2nQ72PgE7EzMGKnk1rPouf_bEkU01nthtZm8mjU/assets/index-74e84a13.js:43:31458)
    at Q5 (http://192.168.2.250:8123/api/hassio_ingress/23Do2nQ72PgE7EzMGKnk1rPouf_bEkU01nthtZm8mjU/assets/index-74e84a13.js:43:31368)
```

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by Cosmeen** [comment]
Hello @iTMC94,
What did you actually tried to do?
Can you write the steps that you tried to do that led to this bug?

More info would help the devs debug/fix your issue.

**Comment by iTMC94** [comment]
I dont know

**Comment by Cosmeen** [comment]
Is the issue still occurring?
