### ISSUE TITLE
Dev Console crashes

### ISSUE THREAD

**Issue by ElkeFelix** [nurikk/z2m-frontend#2105]
### What happened?

I wanted to create an external definition for an unsupported devices (Q-Malina). On step 2 of the instructions I'm supposed to go to the Dev Console. That crashes.

![image](https://github.com/user-attachments/assets/21fa2a01-a458-405e-9002-755969156b82)

(The download-link doesn't do anything btw.)

I restarted Zigbee2MQTT and still got the same result.

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: http://homeassistant.local:8123/api/hassio_ingress/S6N7VxyJtuPCFIrv62KN7dlfOkXf1uwgyU9AXeOIAPs/#/device/0x59940400e00bfdb0/dev-console
**Previous url**: http://homeassistant.local:8123/45df7312_zigbee2mqtt


**Error type**: TypeError
**Error message**: Cannot read properties of undefined (reading 'clusters')



TypeError: Cannot read properties of undefined (reading 'clusters')
    at zs.render (http://homeassistant.local:8123/api/hassio_ingress/S6N7VxyJtuPCFIrv62KN7dlfOkXf1uwgyU9AXeOIAPs/assets/ConnectedDevicePage-792280da.js:1:31105)
    at ab (http://homeassistant.local:8123/api/hassio_ingress/S6N7VxyJtuPCFIrv62KN7dlfOkXf1uwgyU9AXeOIAPs/assets/index-74e84a13.js:43:6186)
    at yD (http://homeassistant.local:8123/api/hassio_ingress/S6N7VxyJtuPCFIrv62KN7dlfOkXf1uwgyU9AXeOIAPs/assets/index-74e84a13.js:43:5982)
    at r3 (http://homeassistant.local:8123/api/hassio_ingress/S6N7VxyJtuPCFIrv62KN7dlfOkXf1uwgyU9AXeOIAPs/assets/index-74e84a13.js:43:44865)
    at e3 (http://homeassistant.local:8123/api/hassio_ingress/S6N7VxyJtuPCFIrv62KN7dlfOkXf1uwgyU9AXeOIAPs/assets/index-74e84a13.js:43:39756)
    at ISe (http://homeassistant.local:8123/api/hassio_ingress/S6N7VxyJtuPCFIrv62KN7dlfOkXf1uwgyU9AXeOIAPs/assets/index-74e84a13.js:43:39682)
    at ap (http://homeassistant.local:8123/api/hassio_ingress/S6N7VxyJtuPCFIrv62KN7dlfOkXf1uwgyU9AXeOIAPs/assets/index-74e84a13.js:43:39534)
    at cb (http://homeassistant.local:8123/api/hassio_ingress/S6N7VxyJtuPCFIrv62KN7dlfOkXf1uwgyU9AXeOIAPs/assets/index-74e84a13.js:43:35900)
    at CD (http://homeassistant.local:8123/api/hassio_ingress/S6N7VxyJtuPCFIrv62KN7dlfOkXf1uwgyU9AXeOIAPs/assets/index-74e84a13.js:43:36704)
    at Gn (http://homeassistant.local:8123/api/hassio_ingress/S6N7VxyJtuPCFIrv62KN7dlfOkXf1uwgyU9AXeOIAPs/assets/index-74e84a13.js:41:3283)
```

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by eeclee** [comment]
I'm having the exact same problem.

**Comment by gabriel403** [comment]
Same here 👍

**Comment by ElkeFelix** [comment]
Since quite a few users have this issue: Does anyone have an estimate how fast something like this is probably fixed? 

This might be a duplicate for #2086 and #2061. Both popped up after the last update, as far as I can see?

Edit: Is there a way to simply install an older version and try again?

Edit 2: Zigbee2MQTT Edge has the same issue.
