### ISSUE TITLE
Fatal error on Open development console or a un supported device 

### ISSUE THREAD

**Issue by RobertZwets** [nurikk/z2m-frontend#2106]
### What happened?

The request to raise a bug report in de ha Android app
Can not create the json zip file

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: https://ei3ldmh11ecqe0up0oxymm8skbvj6djt.ui.nabu.casa/api/hassio_ingress/X2aam834qgBgdKugHgNXphegRKmZWr5je4sNLddXDxo/#/device/0xa4c1387b16260fb6/dev-console
**Previous url**: https://ei3ldmh11ecqe0up0oxymm8skbvj6djt.ui.nabu.casa/45df7312_zigbee2mqtt


**Error type**: TypeError
**Error message**: Cannot read properties of undefined (reading 'clusters')



TypeError: Cannot read properties of undefined (reading 'clusters')
    at zs.render (https://ei3ldmh11ecqe0up0oxymm8skbvj6djt.ui.nabu.casa/api/hassio_ingress/X2aam834qgBgdKugHgNXphegRKmZWr5je4sNLddXDxo/assets/ConnectedDevicePage-792280da.js:1:31105)
    at ab (https://ei3ldmh11ecqe0up0oxymm8skbvj6djt.ui.nabu.casa/api/hassio_ingress/X2aam834qgBgdKugHgNXphegRKmZWr5je4sNLddXDxo/assets/index-74e84a13.js:43:6186)
    at yD (https://ei3ldmh11ecqe0up0oxymm8skbvj6djt.ui.nabu.casa/api/hassio_ingress/X2aam834qgBgdKugHgNXphegRKmZWr5je4sNLddXDxo/assets/index-74e84a13.js:43:5982)
    at r3 (https://ei3ldmh11ecqe0up0oxymm8skbvj6djt.ui.nabu.casa/api/hassio_ingress/X2aam834qgBgdKugHgNXphegRKmZWr5je4sNLddXDxo/assets/index-74e84a13.js:43:44865)
    at e3 (https://ei3ldmh11ecqe0up0oxymm8skbvj6djt.ui.nabu.casa/api/hassio_ingress/X2aam834qgBgdKugHgNXphegRKmZWr5je4sNLddXDxo/assets/index-74e84a13.js:43:39756)
    at ISe (https://ei3ldmh11ecqe0up0oxymm8skbvj6djt.ui.nabu.casa/api/hassio_ingress/X2aam834qgBgdKugHgNXphegRKmZWr5je4sNLddXDxo/assets/index-74e84a13.js:43:39682)
    at ap (https://ei3ldmh11ecqe0up0oxymm8skbvj6djt.ui.nabu.casa/api/hassio_ingress/X2aam834qgBgdKugHgNXphegRKmZWr5je4sNLddXDxo/assets/index-74e84a13.js:43:39534)
    at cb (https://ei3ldmh11ecqe0up0oxymm8skbvj6djt.ui.nabu.casa/api/hassio_ingress/X2aam834qgBgdKugHgNXphegRKmZWr5je4sNLddXDxo/assets/index-74e84a13.js:43:35900)
    at CD (https://ei3ldmh11ecqe0up0oxymm8skbvj6djt.ui.nabu.casa/api/hassio_ingress/X2aam834qgBgdKugHgNXphegRKmZWr5je4sNLddXDxo/assets/index-74e84a13.js:43:36704)
    at Gn (https://ei3ldmh11ecqe0up0oxymm8skbvj6djt.ui.nabu.casa/api/hassio_ingress/X2aam834qgBgdKugHgNXphegRKmZWr5je4sNLddXDxo/assets/index-74e84a13.js:41:3283)
```

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by RobertZwets** [comment]
duplicate of #2105
