### ISSUE TITLE
Trying to add a Sonoff ZBMINIL2 crash (interview doesn't seem to work)

### ISSUE THREAD

**Issue by xabix** [nurikk/z2m-frontend#2111]
### What happened?

Hi All

I am running on the latest dev bc of an ember issue and trying to add ZBMINIL2 Sonoff devices.
cf https://github.com/Koenkk/zigbee2mqtt/issues/23733

<img width="1213" alt="Capture d’écran 2024-08-27 à 15 51 52" src="https://github.com/user-attachments/assets/cb4eb7c0-5497-4aec-8b7a-c318b7bbd591">

<img width="1145" alt="Capture d’écran 2024-08-27 à 15 53 54" src="https://github.com/user-attachments/assets/e47cf05b-ace5-4a51-b089-a24c5c89330d">

Thanks

PS: I can't upload the state as it doesn't DL from HomeAssistant

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: http://homeassistant.local:8123/api/hassio_ingress/5R1PS62QTpW19EwmPJ9j8lQZVJoGuTyO3hZvZLj9QSE/#/device/0x0cae5ffffeb6494a/dev-console
**Previous url**: http://homeassistant.local:8123/45df7312_zigbee2mqtt_edge


**Error type**: TypeError
**Error message**: Cannot read properties of undefined (reading 'clusters')



TypeError: Cannot read properties of undefined (reading 'clusters')
    at zs.render (http://homeassistant.local:8123/api/hassio_ingress/5R1PS62QTpW19EwmPJ9j8lQZVJoGuTyO3hZvZLj9QSE/assets/ConnectedDevicePage-792280da.js:1:31105)
    at ab (http://homeassistant.local:8123/api/hassio_ingress/5R1PS62QTpW19EwmPJ9j8lQZVJoGuTyO3hZvZLj9QSE/assets/index-74e84a13.js:43:6186)
    at yD (http://homeassistant.local:8123/api/hassio_ingress/5R1PS62QTpW19EwmPJ9j8lQZVJoGuTyO3hZvZLj9QSE/assets/index-74e84a13.js:43:5982)
    at r3 (http://homeassistant.local:8123/api/hassio_ingress/5R1PS62QTpW19EwmPJ9j8lQZVJoGuTyO3hZvZLj9QSE/assets/index-74e84a13.js:43:44865)
    at e3 (http://homeassistant.local:8123/api/hassio_ingress/5R1PS62QTpW19EwmPJ9j8lQZVJoGuTyO3hZvZLj9QSE/assets/index-74e84a13.js:43:39756)
    at ISe (http://homeassistant.local:8123/api/hassio_ingress/5R1PS62QTpW19EwmPJ9j8lQZVJoGuTyO3hZvZLj9QSE/assets/index-74e84a13.js:43:39682)
    at ap (http://homeassistant.local:8123/api/hassio_ingress/5R1PS62QTpW19EwmPJ9j8lQZVJoGuTyO3hZvZLj9QSE/assets/index-74e84a13.js:43:39534)
    at cb (http://homeassistant.local:8123/api/hassio_ingress/5R1PS62QTpW19EwmPJ9j8lQZVJoGuTyO3hZvZLj9QSE/assets/index-74e84a13.js:43:35900)
    at CD (http://homeassistant.local:8123/api/hassio_ingress/5R1PS62QTpW19EwmPJ9j8lQZVJoGuTyO3hZvZLj9QSE/assets/index-74e84a13.js:43:36704)
    at Gn (http://homeassistant.local:8123/api/hassio_ingress/5R1PS62QTpW19EwmPJ9j8lQZVJoGuTyO3hZvZLj9QSE/assets/index-74e84a13.js:41:3283)
```

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by xabix** [comment]
Strange as my 2nd device did pair correctly!
<img width="759" alt="Capture d’écran 2024-08-27 à 16 03 48" src="https://github.com/user-attachments/assets/68d9c5a1-1148-4a9f-9bfb-85b3ea21a2cb">

Here is a picture of the device that didn't pair correctly:
![WhatsApp Image 2024-08-27 at 16 03 15](https://github.com/user-attachments/assets/5efd5a42-86a7-418a-bd1e-53f4647b0635)

After a delete, restart it was still showing, so I force an interview 2 times and ended up working. So for me it s ok but I still believe that there could be a bug to avoid the interface to crash when I went to Console Dev during the 1st inclusion.
<img width="1180" alt="Capture d’écran 2024-08-27 à 16 09 21" src="https://github.com/user-attachments/assets/8f537f0e-2197-4f7c-ba6a-7444073ae697">
