### ISSUE TITLE
Problems with Nous A1Z

### ISSUE THREAD

**Issue by gpbicego** [nurikk/z2m-frontend#2115]
### What happened?

I can't switch it On/Off.
I can't set 'Power outage memory' or 'Indicator mode'.
Now I deleted and I can't pair it:
![image](https://github.com/user-attachments/assets/576a8a9f-b58c-476f-a246-89e1e1363acc)

![image](https://github.com/user-attachments/assets/4ac54921-bfe8-4973-a96c-343cce0ed23d)
'Save this file' doesn't work.
![image](https://github.com/user-attachments/assets/a9326c38-cffb-488f-8da3-0d63bf63a234)
'Download state' doesn't work.
Thanks

### What browsers are you seeing the problem on?

Microsoft Edge

### Relevant stacktrace

```shell
**Current url**: http://192.168.1.45:8123/api/hassio_ingress/i0wB0svntDs0L3hiJlLl-DHBOMAR_asr6Ahg-FIrnBU/#/device/0xa4c138fd1b456657/dev-console
**Previous url**: http://192.168.1.45:8123/hassio


**Error type**: TypeError
**Error message**: Cannot read properties of undefined (reading 'clusters')



TypeError: Cannot read properties of undefined (reading 'clusters')
    at zs.render (http://192.168.1.45:8123/api/hassio_ingress/i0wB0svntDs0L3hiJlLl-DHBOMAR_asr6Ahg-FIrnBU/assets/ConnectedDevicePage-792280da.js:1:31105)
    at ab (http://192.168.1.45:8123/api/hassio_ingress/i0wB0svntDs0L3hiJlLl-DHBOMAR_asr6Ahg-FIrnBU/assets/index-74e84a13.js:43:6186)
    at yD (http://192.168.1.45:8123/api/hassio_ingress/i0wB0svntDs0L3hiJlLl-DHBOMAR_asr6Ahg-FIrnBU/assets/index-74e84a13.js:43:5982)
    at r3 (http://192.168.1.45:8123/api/hassio_ingress/i0wB0svntDs0L3hiJlLl-DHBOMAR_asr6Ahg-FIrnBU/assets/index-74e84a13.js:43:44865)
    at e3 (http://192.168.1.45:8123/api/hassio_ingress/i0wB0svntDs0L3hiJlLl-DHBOMAR_asr6Ahg-FIrnBU/assets/index-74e84a13.js:43:39756)
    at ISe (http://192.168.1.45:8123/api/hassio_ingress/i0wB0svntDs0L3hiJlLl-DHBOMAR_asr6Ahg-FIrnBU/assets/index-74e84a13.js:43:39682)
    at ap (http://192.168.1.45:8123/api/hassio_ingress/i0wB0svntDs0L3hiJlLl-DHBOMAR_asr6Ahg-FIrnBU/assets/index-74e84a13.js:43:39534)
    at cb (http://192.168.1.45:8123/api/hassio_ingress/i0wB0svntDs0L3hiJlLl-DHBOMAR_asr6Ahg-FIrnBU/assets/index-74e84a13.js:43:35900)
    at CD (http://192.168.1.45:8123/api/hassio_ingress/i0wB0svntDs0L3hiJlLl-DHBOMAR_asr6Ahg-FIrnBU/assets/index-74e84a13.js:43:36704)
    at Gn (http://192.168.1.45:8123/api/hassio_ingress/i0wB0svntDs0L3hiJlLl-DHBOMAR_asr6Ahg-FIrnBU/assets/index-74e84a13.js:41:3283)
```

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by gpbicego** [comment]
Zigbee2MQTT Log:
[2024-08-31 15:48:39] warning: 	z2m: Failed to ping 'Luce cancelletto' (attempt 1/2, ZCL command 0x60a423fffee6b612/1 genBasic.read(["zclVersion"], {"timeout":10000,"disableResponse":false,"disableRecovery":true,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 21919 - 1 - 219 - 0 - 1 after 10000ms))
[2024-08-31 15:50:57] warning: 	z2m: Failed to ping 'Air Compressor' (attempt 1/1, ZCL command 0x00124b0026b6f48c/1 genBasic.read(["zclVersion"], {"timeout":10000,"disableResponse":false,"disableRecovery":true,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC no ack' (233)))
[2024-08-31 15:55:17] warning: 	z2m: Failed to ping 'Faretto 1' (attempt 1/2, ZCL command 0xbc33acfffe0b38fc/1 genBasic.read(["zclVersion"], {"timeout":10000,"disableResponse":false,"disableRecovery":true,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 39640 - 1 - 225 - 0 - 1 after 10000ms))
[2024-08-31 16:00:59] warning: 	z2m: Failed to ping 'Air Compressor' (attempt 1/1, ZCL command 0x00124b0026b6f48c/1 genBasic.read(["zclVersion"], {"timeout":10000,"disableResponse":false,"disableRecovery":true,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC no ack' (233)))
[2024-08-31 16:08:36] error: 	z2m: Publish 'set' 'state' to 'Dishwasher' failed: 'Error: ZCL command 0xa4c138fd1b456657/1 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205))'
[2024-08-31 16:08:51] error: 	z2m: Publish 'set' 'state' to 'Dishwasher' failed: 'Error: ZCL command 0xa4c138fd1b456657/1 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205))'
[2024-08-31 16:09:28] error: 	z2m: Publish 'set' 'state' to 'Dishwasher' failed: 'Error: ZCL command 0xa4c138fd1b456657/1 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205))'
[2024-08-31 16:10:19] error: 	z2m: Publish 'set' 'state' to 'Dishwasher' failed: 'Error: ZCL command 0xa4c138fd1b456657/1 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (SREQ '--> ZDO - extRouteDisc - {"dstAddr":57113,"options":0,"radius":30}' failed with status '(0xc7: NWK_TABLE_FULL)' (expected '(0x00: SUCCESS)'))'
[2024-08-31 16:11:00] warning: 	z2m: Failed to ping 'Air Compressor' (attempt 1/1, ZCL command 0x00124b0026b6f48c/1 genBasic.read(["zclVersion"], {"timeout":10000,"disableResponse":false,"disableRecovery":true,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC no ack' (233)))
[2024-08-31 16:11:24] error: 	z2m: Publish 'set' 'state' to 'Dishwasher' failed: 'Error: ZCL command 0xa4c138fd1b456657/1 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205))'
[16:12:05] INFO: Preparing to start...
[16:12:06] INFO: Socat not enabled
[16:12:08] INFO: Starting Zigbee2MQTT...
Starting Zigbee2MQTT without watchdog.
[2024-08-31 16:12:18] warning: 	z2m: Failed to ping 'Air Compressor' (attempt 1/1, ZCL command 0x00124b0026b6f48c/1 genBasic.read(["zclVersion"], {"timeout":10000,"disableResponse":false,"disableRecovery":true,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC no ack' (233)))
[2024-08-31 16:13:10] error: 	z2m: Publish 'set' 'state' to 'Dishwasher' failed: 'Error: ZCL command 0xa4c138fd1b456657/1 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205))'
[2024-08-31 16:13:29] error: 	z2m: Publish 'set' 'power_outage_memory' to 'Dishwasher' failed: 'Error: ZCL command 0xa4c138fd1b456657/1 genOnOff.write({"moesStartUpOnOff":1}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205))'
[2024-08-31 16:13:45] error: 	z2m: Publish 'set' 'state' to 'Dishwasher' failed: 'Error: ZCL command 0xa4c138fd1b456657/1 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205))'
[2024-08-31 16:15:25] error: 	z2m: Publish 'set' 'power_outage_memory' to 'Dishwasher' failed: 'Error: ZCL command 0xa4c138fd1b456657/1 genOnOff.write({"moesStartUpOnOff":1}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 57113 - 1 - 10 - 6 - 4 after 10000ms)'
[2024-08-31 16:15:57] error: 	z2m: Publish 'set' 'state' to 'Dishwasher' failed: 'Error: ZCL command 0xa4c138fd1b456657/1 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 57113 - 1 - 11 - 6 - 11 after 10000ms)'
[2024-08-31 16:16:46] error: 	z2m: Publish 'get' 'power_outage_memory' to 'Dishwasher' failed: 'Error: ZCL command 0xa4c138fd1b456657/1 genOnOff.read(["moesStartUpOnOff"], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 57113 - 1 - 12 - 6 - 1 after 10000ms)'
[2024-08-31 16:17:09] error: 	z2m: Publish 'get' 'state' to 'Dishwasher' failed: 'Error: ZCL command 0xa4c138fd1b456657/1 genOnOff.read(["onOff"], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 57113 - 1 - 13 - 6 - 1 after 10000ms)'
[2024-08-31 16:17:52] error: 	z2m: Publish 'set' 'state' to 'Dishwasher' failed: 'Error: ZCL command 0xa4c138fd1b456657/1 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 57113 - 1 - 14 - 6 - 11 after 10000ms)'
[2024-08-31 16:18:54] error: 	z2m: Publish 'set' 'power_outage_memory' to 'Dishwasher' failed: 'Error: ZCL command 0xa4c138fd1b456657/1 genOnOff.write({"moesStartUpOnOff":1}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 57113 - 1 - 17 - 6 - 4 after 10000ms)'
[2024-08-31 16:19:17] error: 	z2m: Publish 'set' 'state' to 'Dishwasher' failed: 'Error: ZCL command 0xa4c138fd1b456657/1 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 57113 - 1 - 18 - 6 - 11 after 10000ms)'
[2024-08-31 16:21:12] error: 	z2m: Publish 'set' 'power_outage_memory' to 'Dishwasher' failed: 'Error: ZCL command 0xa4c138fd1b456657/1 genOnOff.write({"moesStartUpOnOff":1}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205))'
[2024-08-31 16:21:41] error: 	z2m: Publish 'set' 'state' to 'Dishwasher' failed: 'Error: ZCL command 0xa4c138fd1b456657/1 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205))'
[2024-08-31 16:22:34] warning: 	z2m: Failed to ping 'Air Compressor' (attempt 1/1, ZCL command 0x00124b0026b6f48c/1 genBasic.read(["zclVersion"], {"timeout":10000,"disableResponse":false,"disableRecovery":true,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC no ack' (233)))
[2024-08-31 16:22:45] error: 	zh:controller: Interview failed for '0xa4c138fd1b456657 with error 'Error: Interview failed because can not get active endpoints ('0xa4c138fd1b456657')'
[2024-08-31 16:22:45] error: 	z2m: Failed to interview '0xa4c138fd1b456657', device has not successfully been paired
[2024-08-31 16:23:07] error: 	zh:controller: Interview failed for '0xa4c138fd1b456657 with error 'Error: Interview failed because can not get active endpoints ('0xa4c138fd1b456657')'
[2024-08-31 16:23:07] error: 	z2m: Failed to interview '0xa4c138fd1b456657', device has not successfully been paired
[2024-08-31 16:23:30] error: 	zh:controller: Interview failed for '0xa4c138fd1b456657 with error 'Error: Interview failed because can not get active endpoints ('0xa4c138fd1b456657')'
[2024-08-31 16:23:30] error: 	z2m: Failed to interview 'Dishwasher', device has not successfully been paired
[2024-08-31 16:25:14] error: 	z2m: Publish 'get' 'state' to 'Dishwasher' failed: 'Error: ZCL command 0xa4c138fd1b456657/1 genOnOff.read(["onOff"], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205))'
[2024-08-31 16:25:39] error: 	z2m: Publish 'set' 'state' to 'Dishwasher' failed: 'Error: ZCL command 0xa4c138fd1b456657/1 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205))'
[2024-08-31 16:26:04] error: 	z2m: Publish 'set' 'power_outage_memory' to 'Dishwasher' failed: 'Error: ZCL command 0xa4c138fd1b456657/1 genOnOff.write({"moesStartUpOnOff":1}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205))'
[16:26:26] INFO: Preparing to start...
[16:26:26] INFO: Socat not enabled
[16:26:30] INFO: Starting Zigbee2MQTT...
Starting Zigbee2MQTT without watchdog.
[2024-08-31 16:27:57] error: 	zh:controller: Interview failed for '0xa4c138fd1b456657 with error 'Error: Interview failed because can not get active endpoints ('0xa4c138fd1b456657')'
[2024-08-31 16:27:57] error: 	z2m: Failed to interview 'Dishwasher', device has not successfully been paired
[2024-08-31 16:28:19] error: 	zh:controller: Interview failed for '0xa4c138fd1b456657 with error 'Error: Interview failed because can not get active endpoints ('0xa4c138fd1b456657')'
[2024-08-31 16:28:19] error: 	z2m: Failed to interview 'Dishwasher', device has not successfully been paired
[2024-08-31 16:28:42] error: 	zh:controller: Interview failed for '0xa4c138fd1b456657 with error 'Error: Interview failed because can not get active endpoints ('0xa4c138fd1b456657')'
[2024-08-31 16:28:42] error: 	z2m: Failed to interview 'Dishwasher', device has not successfully been paired
[2024-08-31 16:29:05] error: 	zh:controller: Interview failed for '0xa4c138fd1b456657 with error 'Error: DatabaseEntry with ID '18' does not exist'
[2024-08-31 16:30:19] error: 	zh:controller: Interview failed for '0xa4c138fd1b456657 with error 'Error: Interview failed because can not get active endpoints ('0xa4c138fd1b456657')'
[2024-08-31 16:30:19] error: 	z2m: Failed to interview '0xa4c138fd1b456657', device has not successfully been paired
[2024-08-31 16:30:42] error: 	zh:controller: Interview failed for '0xa4c138fd1b456657 with error 'Error: Interview failed because can not get active endpoints ('0xa4c138fd1b456657')'
[2024-08-31 16:30:42] error: 	z2m: Failed to interview '0xa4c138fd1b456657', device has not successfully been paired
[2024-08-31 16:31:41] error: 	zh:controller: Interview failed for '0xa4c138fd1b456657 with error 'Error: Interview failed because can not get active endpoints ('0xa4c138fd1b456657')'
[2024-08-31 16:31:41] error: 	z2m: Failed to interview '0xa4c138fd1b456657', device has not successfully been paired
[2024-08-31 16:32:04] error: 	zh:controller: Interview failed for '0xa4c138fd1b456657 with error 'Error: Interview failed because can not get active endpoints ('0xa4c138fd1b456657')'
[2024-08-31 16:32:04] error: 	z2m: Failed to interview '0xa4c138fd1b456657', device has not successfully been paired
[2024-08-31 16:32:27] error: 	zh:controller: Interview failed for '0xa4c138fd1b456657 with error 'Error: Interview failed because can not get active endpoints ('0xa4c138fd1b456657')'
[2024-08-31 16:32:27] error: 	z2m: Failed to interview '0xa4c138fd1b456657', device has not successfully been paired
[2024-08-31 16:32:52] error: 	zh:controller: Interview failed for '0xa4c138fd1b456657 with error 'Error: Interview failed because can not get active endpoints ('0xa4c138fd1b456657')'
[2024-08-31 16:32:52] error: 	z2m: Failed to interview '0xa4c138fd1b456657', device has not successfully been paired
[2024-08-31 16:33:14] error: 	zh:controller: Interview failed for '0xa4c138fd1b456657 with error 'Error: Interview failed because can not get active endpoints ('0xa4c138fd1b456657')'
[2024-08-31 16:33:14] error: 	z2m: Failed to interview '0xa4c138fd1b456657', device has not successfully been paired
[2024-08-31 16:33:37] error: 	zh:controller: Interview failed for '0xa4c138fd1b456657 with error 'Error: Interview failed because can not get active endpoints ('0xa4c138fd1b456657')'
[2024-08-31 16:33:37] error: 	z2m: Failed to interview '0xa4c138fd1b456657', device has not successfully been paired
[2024-08-31 16:34:00] error: 	zh:controller: Interview failed for '0xa4c138fd1b456657 with error 'Error: Interview failed because can not get active endpoints ('0xa4c138fd1b456657')'
[2024-08-31 16:34:00] error: 	z2m: Failed to interview '0xa4c138fd1b456657', device has not successfully been paired
[2024-08-31 16:34:22] error: 	zh:controller: Interview failed for '0xa4c138fd1b456657 with error 'Error: Interview failed because can not get active endpoints ('0xa4c138fd1b456657')'
[2024-08-31 16:34:22] error: 	z2m: Failed to interview '0xa4c138fd1b456657', device has not successfully been paired
[2024-08-31 16:34:50] error: 	z2m: Publish 'set' 'state' to '0xa4c138fd1b456657' failed: 'Error: ZCL command 0xa4c138fd1b456657/1 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205))'
[2024-08-31 16:35:08] error: 	z2m: Publish 'set' 'power_outage_memory' to '0xa4c138fd1b456657' failed: 'Error: ZCL command 0xa4c138fd1b456657/1 genOnOff.write({"moesStartUpOnOff":1}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205))'
[2024-08-31 16:35:29] error: 	z2m: Publish 'set' 'indicator_mode' to '0xa4c138fd1b456657' failed: 'Error: ZCL command 0xa4c138fd1b456657/1 genOnOff.write({"tuyaBacklightMode":0}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205))'
[2024-08-31 16:37:00] error: 	zh:controller:device: Read response to 0xa4c138fd1b456657 failed
[2024-08-31 16:37:16] error: 	zh:controller:device: Read response to 0xa4c138fd1b456657 failed
[2024-08-31 16:37:32] error: 	z2m: Publish 'set' 'power_outage_memory' to 'Dishwasher' failed: 'Error: ZCL command 0xa4c138fd1b456657/1 genOnOff.write({"moesStartUpOnOff":1}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205))'
[2024-08-31 16:39:53] error: 	z2m: Request 'zigbee2mqtt/bridge/request/device/interview' failed with error: 'interview of 'Dishwasher' (0xa4c138fd1b456657) failed: Error: Interview - interview already in progress for '0xa4c138fd1b456657''
[2024-08-31 16:40:51] error: 	z2m: Failed to execute LQI for 'Refrigerator LG'
[2024-08-31 16:42:38] error: 	z2m: Failed to execute LQI for 'Dishwasher'
[2024-08-31 16:43:40] error: 	z2m: Request 'zigbee2mqtt/bridge/request/device/interview' failed with error: 'interview of 'Dishwasher' (0xa4c138fd1b456657) failed: Error: Interview - interview already in progress for '0xa4c138fd1b456657''
[2024-08-31 16:44:14] error: 	z2m: Request 'zigbee2mqtt/bridge/request/device/interview' failed with error: 'interview of '0xa4c138fd1b456657' (0xa4c138fd1b456657) failed: Error: DatabaseEntry with ID '18' does not exist'
[16:44:43] INFO: Preparing to start...
[16:44:43] INFO: Socat not enabled
[16:44:45] INFO: Starting Zigbee2MQTT...
Starting Zigbee2MQTT without watchdog.
[2024-08-31 16:48:18] error: 	zh:controller: Interview failed for '0xa4c138fd1b456657 with error 'Error: Interview failed because can not get node descriptor ('0xa4c138fd1b456657')'
[2024-08-31 16:48:18] error: 	z2m: Failed to interview '0xa4c138fd1b456657', device has not successfully been paired
[2024-08-31 16:49:22] error: 	z2m: Failed to execute LQI for 'Tank water pump'
[2024-08-31 16:49:48] error: 	z2m: Failed to execute LQI for 'Faretto 1'
[2024-08-31 16:50:14] error: 	z2m: Failed to execute LQI for 'Faretto 2'
[2024-08-31 16:50:41] error: 	z2m: Failed to execute LQI for 'Faretto 3'
[2024-08-31 16:50:41] error: 	zh:controller: Interview failed for '0xa4c138fd1b456657 with error 'Error: Interview failed because can not get node descriptor ('0xa4c138fd1b456657')'
[2024-08-31 16:50:41] error: 	z2m: Failed to interview '0xa4c138fd1b456657', device has not successfully been paired
[2024-08-31 16:51:16] error: 	z2m: Failed to execute LQI for 'Refrigerator LG'
[2024-08-31 16:51:42] error: 	z2m: Failed to execute LQI for '0xa4c138fd1b456657'
[2024-08-31 16:53:36] error: 	zh:controller: Interview failed for '0xa4c138fd1b456657 with error 'Error: DatabaseEntry with ID '18' does not exist'
[2024-08-31 16:55:05] warning: 	z2m: Failed to ping 'Tank water pump' (attempt 1/2, ZCL command 0x00124b0026b6f473/1 genBasic.read(["zclVersion"], {"timeout":10000,"disableResponse":false,"disableRecovery":true,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC no ack' (233)))
[2024-08-31 16:55:16] warning: 	z2m: Failed to ping 'Tank water pump' (attempt 2/2, ZCL command 0x00124b0026b6f473/1 genBasic.read(["zclVersion"], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC no ack' (233)))
[2024-08-31 16:55:18] warning: 	z2m: Failed to ping 'Faretto 1' (attempt 1/2, ZCL command 0xbc33acfffe0b38fc/1 genBasic.read(["zclVersion"], {"timeout":10000,"disableResponse":false,"disableRecovery":true,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC no ack' (233)))
[2024-08-31 16:59:00] error: 	zh:controller: Interview failed for '0xa4c138fd1b456657 with error 'Error: Interview failed because can not get node descriptor ('0xa4c138fd1b456657')'
[2024-08-31 16:59:00] error: 	z2m: Failed to interview '0xa4c138fd1b456657', device has not successfully been paired
[2024-08-31 17:01:26] error: 	z2m: Request 'zigbee2mqtt/bridge/request/device/interview' failed with error: 'interview of 'Dishwasher' (0xa4c138fd1b456657) failed: Error: Interview failed because can not get node descriptor ('0xa4c138fd1b456657')'
[2024-08-31 17:04:53] error: 	z2m: Request 'zigbee2mqtt/bridge/request/device/interview' failed with error: 'interview of 'Dishwasher' (0xa4c138fd1b456657) failed: Error: Interview failed because can not get node descriptor ('0xa4c138fd1b456657')'

**Comment by gpbicego** [comment]
Solved!
The problem was either a low signal or an incompatible router.
I brought an Aqara SP-EUC01 near the device and after deleting it, I paired it again:
![image](https://github.com/user-attachments/assets/b188a83a-86ab-4dbb-9225-4ff83ff28eee)
![image](https://github.com/user-attachments/assets/8d6e95f9-d50d-4fb1-8d13-bd1bd91ac3da)
and everything works perfectly, even the OTA update.
