### ISSUE TITLE
[Bug]: Settings ->  Tools -> Download state button is getting Error

### ISSUE THREAD

**Issue by emandtf** [nurikk/z2m-frontend#2122]
### What happened?

Trying to download Z2M frontend state using specific button in Tools page is getting error in browser console and neither is done.

### What browsers are you seeing the problem on?

Firefox, Chrome

### Relevant stacktrace

```shell
Uncaught (in promise) ReferenceError: require is not defined
    _3 http://192.168.1.19:18833/assets/index-74e84a13.js:62
    exportState http://192.168.1.19:18833/assets/index-74e84a13.js:71
    action http://192.168.1.19:18833/assets/index-74e84a13.js:61
    s http://192.168.1.19:18833/assets/index-74e84a13.js:71
    Jke http://192.168.1.19:18833/assets/index-74e84a13.js:40
    twe http://192.168.1.19:18833/assets/index-74e84a13.js:40
    awe http://192.168.1.19:18833/assets/index-74e84a13.js:40
    XE http://192.168.1.19:18833/assets/index-74e84a13.js:40
    a5 http://192.168.1.19:18833/assets/index-74e84a13.js:40
    wv http://192.168.1.19:18833/assets/index-74e84a13.js:40
    CS http://192.168.1.19:18833/assets/index-74e84a13.js:43
    Aj http://192.168.1.19:18833/assets/index-74e84a13.js:40
    wv http://192.168.1.19:18833/assets/index-74e84a13.js:40
    aS http://192.168.1.19:18833/assets/index-74e84a13.js:40
    _we http://192.168.1.19:18833/assets/index-74e84a13.js:40
    r5 http://192.168.1.19:18833/assets/index-74e84a13.js:40
    kv http://192.168.1.19:18833/assets/index-74e84a13.js:40
    cd http://192.168.1.19:18833/assets/index-74e84a13.js:40
    cd http://192.168.1.19:18833/assets/index-74e84a13.js:40
    createRoot http://192.168.1.19:18833/assets/index-74e84a13.js:43
    <anonymous> http://192.168.1.19:18833/assets/index-74e84a13.js:226
```

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by hb020** [comment]
confirmed, same. Slightly different error log though (but the start is the same)

```text
index-74e84a13.js:62 Uncaught (in promise) ReferenceError: require is not defined
    at _3 (index-74e84a13.js:62:9206)
    at exportState (index-74e84a13.js:71:17798)
    at index-74e84a13.js:61:8374
    at s (index-74e84a13.js:71:25203)
    at Object.Jke (index-74e84a13.js:40:9864)
    at twe (index-74e84a13.js:40:10021)
    at awe (index-74e84a13.js:40:10081)
    at XE (index-74e84a13.js:40:31567)
    at a5 (index-74e84a13.js:40:31985)
    at index-74e84a13.js:40:36918
```
