### ISSUE TITLE
MAJ OTA 

### ISSUE THREAD

**Issue by Deki60** [nurikk/z2m-frontend#2132]
### What happened?

I just open OTA MAJ in home assistant

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: http://homeassistant.local:8123/api/hassio_ingress/gQtDcJFN7iH1zBZ5GALn7a3HjOLOHYDENPgPDpXfb2M/#/ota
**Previous url**: http://homeassistant.local:8123/45df7312_zigbee2mqtt


**Error type**: NotFoundError
**Error message**: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.



Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at K5 (http://homeassistant.local:8123/api/hassio_ingress/gQtDcJFN7iH1zBZ5GALn7a3HjOLOHYDENPgPDpXfb2M/assets/index-74e84a13.js:43:26095)
    at cn (http://homeassistant.local:8123/api/hassio_ingress/gQtDcJFN7iH1zBZ5GALn7a3HjOLOHYDENPgPDpXfb2M/assets/index-74e84a13.js:43:25782)
    at K5 (http://homeassistant.local:8123/api/hassio_ingress/gQtDcJFN7iH1zBZ5GALn7a3HjOLOHYDENPgPDpXfb2M/assets/index-74e84a13.js:43:26531)
    at cn (http://homeassistant.local:8123/api/hassio_ingress/gQtDcJFN7iH1zBZ5GALn7a3HjOLOHYDENPgPDpXfb2M/assets/index-74e84a13.js:43:25782)
    at K5 (http://homeassistant.local:8123/api/hassio_ingress/gQtDcJFN7iH1zBZ5GALn7a3HjOLOHYDENPgPDpXfb2M/assets/index-74e84a13.js:43:26531)
    at Ra (http://homeassistant.local:8123/api/hassio_ingress/gQtDcJFN7iH1zBZ5GALn7a3HjOLOHYDENPgPDpXfb2M/assets/index-74e84a13.js:43:27387)
    at Z5 (http://homeassistant.local:8123/api/hassio_ingress/gQtDcJFN7iH1zBZ5GALn7a3HjOLOHYDENPgPDpXfb2M/assets/index-74e84a13.js:43:27847)
    at Ra (http://homeassistant.local:8123/api/hassio_ingress/gQtDcJFN7iH1zBZ5GALn7a3HjOLOHYDENPgPDpXfb2M/assets/index-74e84a13.js:43:27537)
    at Z5 (http://homeassistant.local:8123/api/hassio_ingress/gQtDcJFN7iH1zBZ5GALn7a3HjOLOHYDENPgPDpXfb2M/assets/index-74e84a13.js:43:30582)
    at Ra (http://homeassistant.local:8123/api/hassio_ingress/gQtDcJFN7iH1zBZ5GALn7a3HjOLOHYDENPgPDpXfb2M/assets/index-74e84a13.js:43:27537)
```

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by Deki60** [comment]
![image](https://github.com/user-attachments/assets/05f04147-4b57-46d9-a5e8-0516ec1febb6)
