### ISSUE TITLE
IKEA L1528 Floalt 30x90

### ISSUE THREAD

**Issue by joonne** [nurikk/z2m-frontend#2157]
### What happened?

I was trying to pair my newly installed IKEA L1528 panel, the pairing did not succeed. Then I tried to browse around the Z2M UI and the Dev console tab gave me this error.

The download button did not give me any file on desktop (Arc) nor on Android (Duckduckgo).

The About tab also states that the device would not be supported, although it is listed on the zigbee2mqtt.io supported devices list.

![Screenshot 2024-10-15 at 7 41 17](https://github.com/user-attachments/assets/701f284e-eb3b-4abc-a98f-4d2bb7dfac60)
![Screenshot 2024-10-15 at 7 49 16](https://github.com/user-attachments/assets/a1b5c4b4-c9e9-4010-b54e-a0318b88b3d0)

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: http://192.168.0.19:8123/api/hassio_ingress/1KGmECx7hlZzspI7-XaNUoVRa_umEcgxqURErDqmFHc/#/device/0x90fd9ffffeeac9b2/dev-console
**Previous url**: http://192.168.0.19:8123/45df7312_zigbee2mqtt


**Error type**: TypeError
**Error message**: Cannot read properties of undefined (reading 'clusters')



TypeError: Cannot read properties of undefined (reading 'clusters')
    at zs.render (http://192.168.0.19:8123/api/hassio_ingress/1KGmECx7hlZzspI7-XaNUoVRa_umEcgxqURErDqmFHc/assets/ConnectedDevicePage-792280da.js:1:31105)
    at ab (http://192.168.0.19:8123/api/hassio_ingress/1KGmECx7hlZzspI7-XaNUoVRa_umEcgxqURErDqmFHc/assets/index-74e84a13.js:43:6186)
    at yD (http://192.168.0.19:8123/api/hassio_ingress/1KGmECx7hlZzspI7-XaNUoVRa_umEcgxqURErDqmFHc/assets/index-74e84a13.js:43:5982)
    at r3 (http://192.168.0.19:8123/api/hassio_ingress/1KGmECx7hlZzspI7-XaNUoVRa_umEcgxqURErDqmFHc/assets/index-74e84a13.js:43:44865)
    at e3 (http://192.168.0.19:8123/api/hassio_ingress/1KGmECx7hlZzspI7-XaNUoVRa_umEcgxqURErDqmFHc/assets/index-74e84a13.js:43:39756)
    at ISe (http://192.168.0.19:8123/api/hassio_ingress/1KGmECx7hlZzspI7-XaNUoVRa_umEcgxqURErDqmFHc/assets/index-74e84a13.js:43:39682)
    at ap (http://192.168.0.19:8123/api/hassio_ingress/1KGmECx7hlZzspI7-XaNUoVRa_umEcgxqURErDqmFHc/assets/index-74e84a13.js:43:39534)
    at cb (http://192.168.0.19:8123/api/hassio_ingress/1KGmECx7hlZzspI7-XaNUoVRa_umEcgxqURErDqmFHc/assets/index-74e84a13.js:43:35900)
    at CD (http://192.168.0.19:8123/api/hassio_ingress/1KGmECx7hlZzspI7-XaNUoVRa_umEcgxqURErDqmFHc/assets/index-74e84a13.js:43:36704)
    at Gn (http://192.168.0.19:8123/api/hassio_ingress/1KGmECx7hlZzspI7-XaNUoVRa_umEcgxqURErDqmFHc/assets/index-74e84a13.js:41:3283)
```

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by joonne** [comment]
This was not an issue after all, the panel initially tried to pair via a zigbee smart switch, but after forcing the pairing (by unplugging the switch) via another device the panel paired correctly.
