### ISSUE TITLE
BSEED Swi

### ISSUE THREAD

**Issue by kujrv1** [nurikk/z2m-frontend#2160]
### What happened?

Adding BSSED wall switch 2 gang

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
TypeError
Cannot read properties of undefined (reading 'clusters')
TypeError: Cannot read properties of undefined (reading 'clusters')
    at zs.render (http://homeassistant.local:8123/api/hassio_ingress/3cuAa-kLWAIUy-ULQ6kxbG9BhvodvvPyb26c4_ohgVk/assets/ConnectedDevicePage-792280da.js:1:31105)
    at ab (http://homeassistant.local:8123/api/hassio_ingress/3cuAa-kLWAIUy-ULQ6kxbG9BhvodvvPyb26c4_ohgVk/assets/index-74e84a13.js:43:6186)
    at yD (http://homeassistant.local:8123/api/hassio_ingress/3cuAa-kLWAIUy-ULQ6kxbG9BhvodvvPyb26c4_ohgVk/assets/index-74e84a13.js:43:5982)
    at r3 (http://homeassistant.local:8123/api/hassio_ingress/3cuAa-kLWAIUy-ULQ6kxbG9BhvodvvPyb26c4_ohgVk/assets/index-74e84a13.js:43:44865)
    at e3 (http://homeassistant.local:8123/api/hassio_ingress/3cuAa-kLWAIUy-ULQ6kxbG9BhvodvvPyb26c4_ohgVk/assets/index-74e84a13.js:43:39756)
    at ISe (http://homeassistant.local:8123/api/hassio_ingress/3cuAa-kLWAIUy-ULQ6kxbG9BhvodvvPyb26c4_ohgVk/assets/index-74e84a13.js:43:39682)
    at ap (http://homeassistant.local:8123/api/hassio_ingress/3cuAa-kLWAIUy-ULQ6kxbG9BhvodvvPyb26c4_ohgVk/assets/index-74e84a13.js:43:39534)
    at cb (http://homeassistant.local:8123/api/hassio_ingress/3cuAa-kLWAIUy-ULQ6kxbG9BhvodvvPyb26c4_ohgVk/assets/index-74e84a13.js:43:35900)
    at CD (http://homeassistant.local:8123/api/hassio_ingress/3cuAa-kLWAIUy-ULQ6kxbG9BhvodvvPyb26c4_ohgVk/assets/index-74e84a13.js:43:36704)
    at Gn (http://homeassistant.local:8123/api/hassio_ingress/3cuAa-kLWAIUy-ULQ6kxbG9BhvodvvPyb26c4_ohgVk/assets/index-74e84a13.js:41:3283)



TypeError: Cannot read properties of undefined (reading 'clusters')
    at zs.render (http://homeassistant.local:8123/api/hassio_ingress/3cuAa-kLWAIUy-ULQ6kxbG9BhvodvvPyb26c4_ohgVk/assets/ConnectedDevicePage-792280da.js:1:31105)
    at ab (http://homeassistant.local:8123/api/hassio_ingress/3cuAa-kLWAIUy-ULQ6kxbG9BhvodvvPyb26c4_ohgVk/assets/index-74e84a13.js:43:6186)
    at yD (http://homeassistant.local:8123/api/hassio_ingress/3cuAa-kLWAIUy-ULQ6kxbG9BhvodvvPyb26c4_ohgVk/assets/index-74e84a13.js:43:5982)
    at r3 (http://homeassistant.local:8123/api/hassio_ingress/3cuAa-kLWAIUy-ULQ6kxbG9BhvodvvPyb26c4_ohgVk/assets/index-74e84a13.js:43:44865)
    at e3 (http://homeassistant.local:8123/api/hassio_ingress/3cuAa-kLWAIUy-ULQ6kxbG9BhvodvvPyb26c4_ohgVk/assets/index-74e84a13.js:43:39756)
    at ISe (http://homeassistant.local:8123/api/hassio_ingress/3cuAa-kLWAIUy-ULQ6kxbG9BhvodvvPyb26c4_ohgVk/assets/index-74e84a13.js:43:39682)
    at ap (http://homeassistant.local:8123/api/hassio_ingress/3cuAa-kLWAIUy-ULQ6kxbG9BhvodvvPyb26c4_ohgVk/assets/index-74e84a13.js:43:39534)
    at cb (http://homeassistant.local:8123/api/hassio_ingress/3cuAa-kLWAIUy-ULQ6kxbG9BhvodvvPyb26c4_ohgVk/assets/index-74e84a13.js:43:35900)
    at CD (http://homeassistant.local:8123/api/hassio_ingress/3cuAa-kLWAIUy-ULQ6kxbG9BhvodvvPyb26c4_ohgVk/assets/index-74e84a13.js:43:36704)
    at Gn (http://homeassistant.local:8123/api/hassio_ingress/3cuAa-kLWAIUy-ULQ6kxbG9BhvodvvPyb26c4_ohgVk/assets/index-74e84a13.js:41:3283)
```

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by kujrv1** [comment]
attached state
[state.zip](https://github.com/user-attachments/files/17395514/state.zip)
![Error](https://github.com/user-attachments/assets/c3a284f6-af06-42cc-8d39-cc24ba796627)
