### ISSUE TITLE
Dev console: Cannot read properties of undefined (reading 'clusters')

### ISSUE THREAD

**Issue by lukebarton** [nurikk/z2m-frontend#2161]
### What happened?

Trying to follow the "add support" guide. No download either, button does nothing.

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: https://ha.home.innerspace.sh:8123/api/hassio_ingress/Hg-gwWfMOswPsPe6WLPwHLPNJt8s8zuVujApubw4Q-U/#/device/0x000781d5000652ce/dev-console
**Previous url**: https://ha.home.innerspace.sh:8123/45df7312_zigbee2mqtt/ingress


**Error type**: TypeError
**Error message**: Cannot read properties of undefined (reading 'clusters')



TypeError: Cannot read properties of undefined (reading 'clusters')
    at zs.render (https://ha.home.innerspace.sh:8123/api/hassio_ingress/Hg-gwWfMOswPsPe6WLPwHLPNJt8s8zuVujApubw4Q-U/assets/ConnectedDevicePage-792280da.js:1:31105)
    at ab (https://ha.home.innerspace.sh:8123/api/hassio_ingress/Hg-gwWfMOswPsPe6WLPwHLPNJt8s8zuVujApubw4Q-U/assets/index-74e84a13.js:43:6186)
    at yD (https://ha.home.innerspace.sh:8123/api/hassio_ingress/Hg-gwWfMOswPsPe6WLPwHLPNJt8s8zuVujApubw4Q-U/assets/index-74e84a13.js:43:5982)
    at r3 (https://ha.home.innerspace.sh:8123/api/hassio_ingress/Hg-gwWfMOswPsPe6WLPwHLPNJt8s8zuVujApubw4Q-U/assets/index-74e84a13.js:43:44865)
    at e3 (https://ha.home.innerspace.sh:8123/api/hassio_ingress/Hg-gwWfMOswPsPe6WLPwHLPNJt8s8zuVujApubw4Q-U/assets/index-74e84a13.js:43:39756)
    at ISe (https://ha.home.innerspace.sh:8123/api/hassio_ingress/Hg-gwWfMOswPsPe6WLPwHLPNJt8s8zuVujApubw4Q-U/assets/index-74e84a13.js:43:39682)
    at ap (https://ha.home.innerspace.sh:8123/api/hassio_ingress/Hg-gwWfMOswPsPe6WLPwHLPNJt8s8zuVujApubw4Q-U/assets/index-74e84a13.js:43:39534)
    at cb (https://ha.home.innerspace.sh:8123/api/hassio_ingress/Hg-gwWfMOswPsPe6WLPwHLPNJt8s8zuVujApubw4Q-U/assets/index-74e84a13.js:43:35900)
    at CD (https://ha.home.innerspace.sh:8123/api/hassio_ingress/Hg-gwWfMOswPsPe6WLPwHLPNJt8s8zuVujApubw4Q-U/assets/index-74e84a13.js:43:36704)
    at Gn (https://ha.home.innerspace.sh:8123/api/hassio_ingress/Hg-gwWfMOswPsPe6WLPwHLPNJt8s8zuVujApubw4Q-U/assets/index-74e84a13.js:41:3283)
```

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by 0x6c66** [comment]
I’m experiencing the same issue with pairing the Bosch Twinguard smoke alarm on my Home Assistant Yellow setup.
After attempting the pairing process, it fails, as described in [issue #20169](https://github.com/Koenkk/zigbee2mqtt/issues/20169) and opening the dev console returns the same `Cannot read properties of undefined (reading 'clusters').` error.

The behavior seems consistent across browsers (tested using Safari and Chrome), with the button not triggering any download.

**Comment by lukebarton** [comment]
If I had a dime for every issue I filed that got closed as stale…
