### ISSUE TITLE
Ikea AC plug is unsopported

### ISSUE THREAD

**Issue by erahham** [nurikk/z2m-frontend#2164]
### What happened?

I was pairing an Ikea plug to Zigbee 2 MQTT, it's says it's unsopported.

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: https://erahhamhass.duckdns.org/api/hassio_ingress/chsT9u-yPSuPVMosMNBByDUMW94FUUon9n85auGyzCI/#/device/0x14b457fffefd88d2/dev-console
**Previous url**: https://erahhamhass.duckdns.org/45df7312_zigbee2mqtt


**Error type**: TypeError
**Error message**: Cannot read properties of undefined (reading 'clusters')



TypeError: Cannot read properties of undefined (reading 'clusters')
    at zs.render (https://erahhamhass.duckdns.org/api/hassio_ingress/chsT9u-yPSuPVMosMNBByDUMW94FUUon9n85auGyzCI/assets/ConnectedDevicePage-792280da.js:1:31105)
    at ab (https://erahhamhass.duckdns.org/api/hassio_ingress/chsT9u-yPSuPVMosMNBByDUMW94FUUon9n85auGyzCI/assets/index-74e84a13.js:43:6186)
    at yD (https://erahhamhass.duckdns.org/api/hassio_ingress/chsT9u-yPSuPVMosMNBByDUMW94FUUon9n85auGyzCI/assets/index-74e84a13.js:43:5982)
    at r3 (https://erahhamhass.duckdns.org/api/hassio_ingress/chsT9u-yPSuPVMosMNBByDUMW94FUUon9n85auGyzCI/assets/index-74e84a13.js:43:44865)
    at e3 (https://erahhamhass.duckdns.org/api/hassio_ingress/chsT9u-yPSuPVMosMNBByDUMW94FUUon9n85auGyzCI/assets/index-74e84a13.js:43:39756)
    at ISe (https://erahhamhass.duckdns.org/api/hassio_ingress/chsT9u-yPSuPVMosMNBByDUMW94FUUon9n85auGyzCI/assets/index-74e84a13.js:43:39682)
    at ap (https://erahhamhass.duckdns.org/api/hassio_ingress/chsT9u-yPSuPVMosMNBByDUMW94FUUon9n85auGyzCI/assets/index-74e84a13.js:43:39534)
    at cb (https://erahhamhass.duckdns.org/api/hassio_ingress/chsT9u-yPSuPVMosMNBByDUMW94FUUon9n85auGyzCI/assets/index-74e84a13.js:43:35900)
    at CD (https://erahhamhass.duckdns.org/api/hassio_ingress/chsT9u-yPSuPVMosMNBByDUMW94FUUon9n85auGyzCI/assets/index-74e84a13.js:43:36704)
    at Gn (https://erahhamhass.duckdns.org/api/hassio_ingress/chsT9u-yPSuPVMosMNBByDUMW94FUUon9n85auGyzCI/assets/index-74e84a13.js:41:3283)
```

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by Cosmeen** [comment]
Hello,

What model are you using?
Is it the E2204/E2206 (new) or E1603/E1702/E1708 (old)?

I also had issues connecting the new plug first time, here are the infos from the docu on how to connect:

Pair the plug to Zigbee2MQTT by pressing the pair button (small hole below the round toggle button) using a needle or a paperclip for about two seconds. The white light next to the button should flash four times times and then turn off. After a few seconds it turns back on and pulsate. When connected, the light turns off.
https://www.zigbee2mqtt.io/devices/E2204.html


If you have the old plug here is the info on how to connect:
To factory reset the TRADFRI control outlet, press and hold the reset button (pinhole underneath the light, located at the top (bottom if UK) of the outlet) with a paperclip until the white light starts fading. Hold onto the button for a few more seconds, then release. After this, the outlet will automatically connect.
https://www.zigbee2mqtt.io/devices/E1603_E1702_E1708.html

**Comment by erahham** [comment]
Thank you so much for this, after following your instructions it works now.
Best,
Hans

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Cosmeen** [comment]
Great @erahham
You can also close the issue

**Comment by erahham** [comment]
Closed, problem solved
