### ISSUE TITLE
zigbee switch not recognised no brand on aliexpress

### ISSUE THREAD

**Issue by GiorgioVisconti** [nurikk/z2m-frontend#2170]
### What happened?

the device is discovered by z2m but not supported and when i try to open the developer console in the first screenshot i find the message of the second screenshot that says its a bug?
unfortunally i am not so good in english bat also with homeassistant 
hope somebody can help
![Screenshot 2024-10-26 alle 21 49 16](https://github.com/user-attachments/assets/15c3f896-4919-4469-8966-c8d79473d12e)
![Screenshot 2024-10-26 alle 21 54 04](https://github.com/user-attachments/assets/1a477d29-1de2-4d41-a152-257a343c2a28)

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: http://192.168.0.100:8123/api/hassio_ingress/olC6t9myTHQmpt_sd7ULVFO0RDVhlGzFuceNXNkurTg/#/device/0xa4c1389b61548a1c/dev-console
**Previous url**: 


**Error type**: TypeError
**Error message**: Cannot read properties of undefined (reading 'clusters')



TypeError: Cannot read properties of undefined (reading 'clusters')
    at zs.render (http://192.168.0.100:8123/api/hassio_ingress/olC6t9myTHQmpt_sd7ULVFO0RDVhlGzFuceNXNkurTg/assets/ConnectedDevicePage-792280da.js:1:31105)
    at ab (http://192.168.0.100:8123/api/hassio_ingress/olC6t9myTHQmpt_sd7ULVFO0RDVhlGzFuceNXNkurTg/assets/index-74e84a13.js:43:6186)
    at yD (http://192.168.0.100:8123/api/hassio_ingress/olC6t9myTHQmpt_sd7ULVFO0RDVhlGzFuceNXNkurTg/assets/index-74e84a13.js:43:5982)
    at r3 (http://192.168.0.100:8123/api/hassio_ingress/olC6t9myTHQmpt_sd7ULVFO0RDVhlGzFuceNXNkurTg/assets/index-74e84a13.js:43:44865)
    at e3 (http://192.168.0.100:8123/api/hassio_ingress/olC6t9myTHQmpt_sd7ULVFO0RDVhlGzFuceNXNkurTg/assets/index-74e84a13.js:43:39756)
    at ISe (http://192.168.0.100:8123/api/hassio_ingress/olC6t9myTHQmpt_sd7ULVFO0RDVhlGzFuceNXNkurTg/assets/index-74e84a13.js:43:39682)
    at ap (http://192.168.0.100:8123/api/hassio_ingress/olC6t9myTHQmpt_sd7ULVFO0RDVhlGzFuceNXNkurTg/assets/index-74e84a13.js:43:39534)
    at cb (http://192.168.0.100:8123/api/hassio_ingress/olC6t9myTHQmpt_sd7ULVFO0RDVhlGzFuceNXNkurTg/assets/index-74e84a13.js:43:35900)
    at CD (http://192.168.0.100:8123/api/hassio_ingress/olC6t9myTHQmpt_sd7ULVFO0RDVhlGzFuceNXNkurTg/assets/index-74e84a13.js:43:36704)
    at Gn (http://192.168.0.100:8123/api/hassio_ingress/olC6t9myTHQmpt_sd7ULVFO0RDVhlGzFuceNXNkurTg/assets/index-74e84a13.js:41:3283)
```

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by GiorgioVisconti** [comment]
i had two of those devices and the other one seems to work fine
so i think is a problem of the device itself (the other one is recognised as tuya model whd02)
