### ISSUE TITLE
[Bug]: EWAY CASA Smart Vertical Blinds Vertical Slats Tuya Zigbee Motor issue

### ISSUE THREAD

**Issue by Mrsash2020** [nurikk/z2m-frontend#2194]
### What happened?

Zigbee device paired but then said unsupported in the about section. I could then go to dev console but now it shows me the following screen. Clicking on the second blinking link does nothing in both Edge and Firefox browsers.
originally it did show me when I was able to go to the dev console and clicked "generated_external_definition" but now its not coming up.

```
const definition = {
    zigbeeModel: ['TS0601'],
    model: 'TS0601',
    vendor: '_TZE200_cs05mqku',
    description: 'Automatically generated definition',
    extend: [],
    meta: {},
};

module.exports = definition;
```

![image](https://github.com/user-attachments/assets/a7494ea3-61d5-4dbc-8706-4348f766d5b1)

TypeError
Cannot read properties of undefined (reading 'clusters')
TypeError: Cannot read properties of undefined (reading 'clusters')
    at zs.render (http://homeassistant.local:8123/api/hassio_ingress/1d39maaHKvuu-UNIpzFdI1jf0My4sfjmzraVT_lMzpQ/assets/ConnectedDevicePage-792280da.js:1:31105)
    at ab (http://homeassistant.local:8123/api/hassio_ingress/1d39maaHKvuu-UNIpzFdI1jf0My4sfjmzraVT_lMzpQ/assets/index-74e84a13.js:43:6186)
    at yD (http://homeassistant.local:8123/api/hassio_ingress/1d39maaHKvuu-UNIpzFdI1jf0My4sfjmzraVT_lMzpQ/assets/index-74e84a13.js:43:5982)
    at r3 (http://homeassistant.local:8123/api/hassio_ingress/1d39maaHKvuu-UNIpzFdI1jf0My4sfjmzraVT_lMzpQ/assets/index-74e84a13.js:43:44865)
    at e3 (http://homeassistant.local:8123/api/hassio_ingress/1d39maaHKvuu-UNIpzFdI1jf0My4sfjmzraVT_lMzpQ/assets/index-74e84a13.js:43:39756)
    at ISe (http://homeassistant.local:8123/api/hassio_ingress/1d39maaHKvuu-UNIpzFdI1jf0My4sfjmzraVT_lMzpQ/assets/index-74e84a13.js:43:39682)
    at ap (http://homeassistant.local:8123/api/hassio_ingress/1d39maaHKvuu-UNIpzFdI1jf0My4sfjmzraVT_lMzpQ/assets/index-74e84a13.js:43:39534)
    at cb (http://homeassistant.local:8123/api/hassio_ingress/1d39maaHKvuu-UNIpzFdI1jf0My4sfjmzraVT_lMzpQ/assets/index-74e84a13.js:43:35900)
    at CD (http://homeassistant.local:8123/api/hassio_ingress/1d39maaHKvuu-UNIpzFdI1jf0My4sfjmzraVT_lMzpQ/assets/index-74e84a13.js:43:36704)
    at Gn (http://homeassistant.local:8123/api/hassio_ingress/1d39maaHKvuu-UNIpzFdI1jf0My4sfjmzraVT_lMzpQ/assets/index-74e84a13.js:41:3283)

### What browsers are you seeing the problem on?

Microsoft Edge

### Did you download state.json.zip?

No state.json created on clicking link

**Comment by Mrsash2020** [comment]
Update: I paired the device again and find that the issue has resolved itself(the screen allows me to generate external definition) but the device does not expose any controls since its an unsupported device.
