### ISSUE TITLE
Unable to complete interview for Inovelli VZM31-SN

### ISSUE THREAD

**Issue by blodestone** [nurikk/z2m-frontend#2220]
### What happened?

I am using the official Home Assistant Add-on for Z2M.  Home assistant is running latest version.

I am adding two Inovelli Blue 2-1 dimmers [VZM31-SN](https://www.zigbee2mqtt.io/devices/VZM31-SN.html#inovelli-vzm31-sn) that I had as spares from the first firmware release (after the manufacturing defect was corrected).  These are at factory firmware, just opened the box.  I have over 20 of these already installed for the past 2 years (almost).

The interview fails with the error 'Error: Interview failed because can not get node descriptor'.  Both devices fail with the same symptoms.

I have reset them several times using factory reset process. My Zigbee channel is 25.  I have changed my 2.4Ghz wifi to the opposite end (from 11 to 1) as well as air-gapping all of my other zigbee switches (59/95 of my endpoints/routers are powered off ) to reduce network interference.  My network has always been very responsive.

I'm using tube_zb_gw_cc2652p2_poe coordinator, which is within line of sight at less than 7 meters from one of the switches and 2 meters from the other.  I have restarted the coordinator.  I have restarted the Home Assistant z2m container, I have restarted Home Assistant (HA-OS).

I have tried to download the state file (from the blinking link as well as from the Tools page) but I don't get any file downloaded.

All troubleshooting ends with the same result.

Is there an issue with the herdsman?  What should I do next?

![Inovelli bug](https://github.com/user-attachments/assets/436513f3-ca93-4de2-b109-1c751e13483c)info 2024-11-05 15:51:41z2m: Starting interview of '0x94deb8fffe315054'
info 2024-11-05 15:51:42z2m:mqtt: MQTT publish: topic 'zigbee/bridge/event', payload '{"data":{"friendly_name":"0x94deb8fffe315054","ieee_address":"0x94deb8fffe315054"},"type":"device_joined"}'
info 2024-11-05 15:51:42z2m:mqtt: MQTT publish: topic 'zigbee/bridge/event', payload '{"data":{"friendly_name":"0x94deb8fffe315054","ieee_address":"0x94deb8fffe315054","status":"started"},"type":"device_interview"}'
error 2024-11-05 15:52:42zh:controller: Interview failed for '0x94deb8fffe315054 with error 'Error: Interview failed because can not get node descriptor ('0x94deb8fffe315054')'
error 2024-11-05 15:52:42z2m: Failed to interview '0x94deb8fffe315054', device has not successfully been paired
info 2024-11-05 15:52:43z2m:mqtt: MQTT publish: topic 'zigbee/bridge/event', payload '{"data":{"friendly_name":"0x94deb8fffe315054","ieee_address":"0x94deb8fffe315054","status":"failed"},"type":"device_interview"}'

Zigbee2MQTT version
    [1.41.0](https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.41.0) commit: [unknown](https://github.com/Koenkk/zigbee2mqtt/commit/unknown)
Coordinator type
    zStack3x0
Coordinator revision
    20221226
Coordinator IEEE Address
    0x00124b00237dfbe9
Frontend version
    0.7.4
zigbee-herdsman-converters version
    20.38.0
zigbee-herdsman version
    2.1.7

Home Assistant    
Core 2024.10.4
Supervisor 2024.10.3
Operating System 13.2
Frontend 20241002.4

### What browsers are you seeing the problem on?

Firefox, Chrome

### Relevant stacktrace

```shell
**Current url**: http://192.168.0.5:8123/api/hassio_ingress/SV06LW0jlJeOHTN5cE-3mBNywTpIFWshPRcesBgTSog/#/device/0x94deb8fffe315054/dev-console
**Previous url**: 


**Error type**: TypeError
**Error message**: Cannot read properties of undefined (reading 'clusters')



TypeError: Cannot read properties of undefined (reading 'clusters')
    at zs.render (http://192.168.0.5:8123/api/hassio_ingress/SV06LW0jlJeOHTN5cE-3mBNywTpIFWshPRcesBgTSog/assets/ConnectedDevicePage-792280da.js:1:31105)
    at ab (http://192.168.0.5:8123/api/hassio_ingress/SV06LW0jlJeOHTN5cE-3mBNywTpIFWshPRcesBgTSog/assets/index-74e84a13.js:43:6186)
    at yD (http://192.168.0.5:8123/api/hassio_ingress/SV06LW0jlJeOHTN5cE-3mBNywTpIFWshPRcesBgTSog/assets/index-74e84a13.js:43:5982)
    at r3 (http://192.168.0.5:8123/api/hassio_ingress/SV06LW0jlJeOHTN5cE-3mBNywTpIFWshPRcesBgTSog/assets/index-74e84a13.js:43:44865)
    at e3 (http://192.168.0.5:8123/api/hassio_ingress/SV06LW0jlJeOHTN5cE-3mBNywTpIFWshPRcesBgTSog/assets/index-74e84a13.js:43:39756)
    at ISe (http://192.168.0.5:8123/api/hassio_ingress/SV06LW0jlJeOHTN5cE-3mBNywTpIFWshPRcesBgTSog/assets/index-74e84a13.js:43:39682)
    at ap (http://192.168.0.5:8123/api/hassio_ingress/SV06LW0jlJeOHTN5cE-3mBNywTpIFWshPRcesBgTSog/assets/index-74e84a13.js:43:39534)
    at cb (http://192.168.0.5:8123/api/hassio_ingress/SV06LW0jlJeOHTN5cE-3mBNywTpIFWshPRcesBgTSog/assets/index-74e84a13.js:43:35900)
    at CD (http://192.168.0.5:8123/api/hassio_ingress/SV06LW0jlJeOHTN5cE-3mBNywTpIFWshPRcesBgTSog/assets/index-74e84a13.js:43:36704)
    at Gn (http://192.168.0.5:8123/api/hassio_ingress/SV06LW0jlJeOHTN5cE-3mBNywTpIFWshPRcesBgTSog/assets/index-74e84a13.js:41:3283)
```

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by blodestone** [comment]
close as a dupe.  I have opened another issue under the main zigbee2mqtt resource
https://github.com/Koenkk/zigbee2mqtt/issues/24907
