### ISSUE TITLE
Click on "Dev Console" tab on an unsupported device shows an "oopsi" page

### ISSUE THREAD

**Issue by RubenKelevra** [nurikk/z2m-frontend#2225]
### What happened?

Click on "Dev Console" tab on an unsupported device shows an "oopsi" page
![Screenshot_20241109_212453](https://github.com/user-attachments/assets/c62c5be4-c684-40e9-a122-c946c842c774)
![Screenshot_20241109_212517](https://github.com/user-attachments/assets/1841fb25-1576-4624-baa0-f78d18128dc1)

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: http://homeassistant.local:8123/api/hassio_ingress/ZTWaRp7q_tMs_vS2fJZHYNAjF_g1i8Lf_BNf_vWhB1I/#/device/0xa4c13800aa4310eb/dev-console
**Previous url**: 


**Error type**: TypeError
**Error message**: Cannot read properties of undefined (reading 'clusters')



TypeError: Cannot read properties of undefined (reading 'clusters')
    at zs.render (http://homeassistant.local:8123/api/hassio_ingress/ZTWaRp7q_tMs_vS2fJZHYNAjF_g1i8Lf_BNf_vWhB1I/assets/ConnectedDevicePage-792280da.js:1:31105)
    at ab (http://homeassistant.local:8123/api/hassio_ingress/ZTWaRp7q_tMs_vS2fJZHYNAjF_g1i8Lf_BNf_vWhB1I/assets/index-74e84a13.js:43:6186)
    at yD (http://homeassistant.local:8123/api/hassio_ingress/ZTWaRp7q_tMs_vS2fJZHYNAjF_g1i8Lf_BNf_vWhB1I/assets/index-74e84a13.js:43:5982)
    at r3 (http://homeassistant.local:8123/api/hassio_ingress/ZTWaRp7q_tMs_vS2fJZHYNAjF_g1i8Lf_BNf_vWhB1I/assets/index-74e84a13.js:43:44865)
    at e3 (http://homeassistant.local:8123/api/hassio_ingress/ZTWaRp7q_tMs_vS2fJZHYNAjF_g1i8Lf_BNf_vWhB1I/assets/index-74e84a13.js:43:39756)
    at ISe (http://homeassistant.local:8123/api/hassio_ingress/ZTWaRp7q_tMs_vS2fJZHYNAjF_g1i8Lf_BNf_vWhB1I/assets/index-74e84a13.js:43:39682)
    at ap (http://homeassistant.local:8123/api/hassio_ingress/ZTWaRp7q_tMs_vS2fJZHYNAjF_g1i8Lf_BNf_vWhB1I/assets/index-74e84a13.js:43:39534)
    at cb (http://homeassistant.local:8123/api/hassio_ingress/ZTWaRp7q_tMs_vS2fJZHYNAjF_g1i8Lf_BNf_vWhB1I/assets/index-74e84a13.js:43:35900)
    at CD (http://homeassistant.local:8123/api/hassio_ingress/ZTWaRp7q_tMs_vS2fJZHYNAjF_g1i8Lf_BNf_vWhB1I/assets/index-74e84a13.js:43:36704)
    at Gn (http://homeassistant.local:8123/api/hassio_ingress/ZTWaRp7q_tMs_vS2fJZHYNAjF_g1i8Lf_BNf_vWhB1I/assets/index-74e84a13.js:41:3283)
```

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by RubenKelevra** [comment]
Possibly the same issue described [here](https://github.com/nurikk/zigbee2mqtt-frontend/issues/2222), just for an Aldi device, which isn't really connecting correctly to the network

**Comment by RubenKelevra** [comment]
Wouldn't it be nice if bugs would be fixed instead of closed by an harassing bot? 🤔
