### ISSUE TITLE
Not supported bosch bth-ra thermostat

### ISSUE THREAD

**Issue by skorencev** [nurikk/z2m-frontend#2239]
### What happened?

I removed the batteries from the thermal head, pressed the power button and put the batteries back in, it enabled synchronization mode and I started adding the device to zigbe2mqtt. The thermal head was detected but a message popped up that it was not supported. 

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: http://homeassistant.local:8123/api/hassio_ingress/PIubrRC7q7J5cCgsJ0Zz-ZDObgTZDuhUbuVnUG7Elig/#/device/0xc498860000d4bbcc/dev-console
**Previous url**: http://homeassistant.local:8123/45df7312_zigbee2mqtt


**Error type**: TypeError
**Error message**: Cannot read properties of undefined (reading 'clusters')



TypeError: Cannot read properties of undefined (reading 'clusters')
    at zs.render (http://homeassistant.local:8123/api/hassio_ingress/PIubrRC7q7J5cCgsJ0Zz-ZDObgTZDuhUbuVnUG7Elig/assets/ConnectedDevicePage-792280da.js:1:31105)
    at ab (http://homeassistant.local:8123/api/hassio_ingress/PIubrRC7q7J5cCgsJ0Zz-ZDObgTZDuhUbuVnUG7Elig/assets/index-74e84a13.js:43:6186)
    at yD (http://homeassistant.local:8123/api/hassio_ingress/PIubrRC7q7J5cCgsJ0Zz-ZDObgTZDuhUbuVnUG7Elig/assets/index-74e84a13.js:43:5982)
    at r3 (http://homeassistant.local:8123/api/hassio_ingress/PIubrRC7q7J5cCgsJ0Zz-ZDObgTZDuhUbuVnUG7Elig/assets/index-74e84a13.js:43:44865)
    at e3 (http://homeassistant.local:8123/api/hassio_ingress/PIubrRC7q7J5cCgsJ0Zz-ZDObgTZDuhUbuVnUG7Elig/assets/index-74e84a13.js:43:39756)
    at ISe (http://homeassistant.local:8123/api/hassio_ingress/PIubrRC7q7J5cCgsJ0Zz-ZDObgTZDuhUbuVnUG7Elig/assets/index-74e84a13.js:43:39682)
    at ap (http://homeassistant.local:8123/api/hassio_ingress/PIubrRC7q7J5cCgsJ0Zz-ZDObgTZDuhUbuVnUG7Elig/assets/index-74e84a13.js:43:39534)
    at cb (http://homeassistant.local:8123/api/hassio_ingress/PIubrRC7q7J5cCgsJ0Zz-ZDObgTZDuhUbuVnUG7Elig/assets/index-74e84a13.js:43:35900)
    at CD (http://homeassistant.local:8123/api/hassio_ingress/PIubrRC7q7J5cCgsJ0Zz-ZDObgTZDuhUbuVnUG7Elig/assets/index-74e84a13.js:43:36704)
    at Gn (http://homeassistant.local:8123/api/hassio_ingress/PIubrRC7q7J5cCgsJ0Zz-ZDObgTZDuhUbuVnUG7Elig/assets/index-74e84a13.js:41:3283)
```

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by skorencev** [comment]
SONOFF Zigbee 3.0 USB Dongle
