### ISSUE TITLE
Tried to go to Dev console for an unsupported device

### ISSUE THREAD

**Issue by KGholam** [nurikk/z2m-frontend#2263]
### What happened?

[initialState.json.zip](https://github.com/user-attachments/files/18008239/initialState.json.zip)
![Screenshot 2024-12-04 123543](https://github.com/user-attachments/assets/31d265d0-57ec-48c2-8017-97cdebbcaefe)

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: http://homeassistant.local:8123/api/hassio_ingress/0aj06OY5EFGN5_Mb1edlTK3wWKHe0-6qUXaka6lv1g0/#/device/0xa4c1386542b166ba/dev-console
**Previous url**: http://homeassistant.local:8123/45df7312_zigbee2mqtt/ingress


**Error type**: TypeError
**Error message**: Cannot read properties of undefined (reading 'clusters')



TypeError: Cannot read properties of undefined (reading 'clusters')
    at zs.render (http://homeassistant.local:8123/api/hassio_ingress/0aj06OY5EFGN5_Mb1edlTK3wWKHe0-6qUXaka6lv1g0/assets/ConnectedDevicePage-904482a0.js:1:31232)
    at ab (http://homeassistant.local:8123/api/hassio_ingress/0aj06OY5EFGN5_Mb1edlTK3wWKHe0-6qUXaka6lv1g0/assets/index-1213f99f.js:43:6186)
    at _D (http://homeassistant.local:8123/api/hassio_ingress/0aj06OY5EFGN5_Mb1edlTK3wWKHe0-6qUXaka6lv1g0/assets/index-1213f99f.js:43:5982)
    at a3 (http://homeassistant.local:8123/api/hassio_ingress/0aj06OY5EFGN5_Mb1edlTK3wWKHe0-6qUXaka6lv1g0/assets/index-1213f99f.js:43:44865)
    at J5 (http://homeassistant.local:8123/api/hassio_ingress/0aj06OY5EFGN5_Mb1edlTK3wWKHe0-6qUXaka6lv1g0/assets/index-1213f99f.js:43:39756)
    at Oze (http://homeassistant.local:8123/api/hassio_ingress/0aj06OY5EFGN5_Mb1edlTK3wWKHe0-6qUXaka6lv1g0/assets/index-1213f99f.js:43:39682)
    at ap (http://homeassistant.local:8123/api/hassio_ingress/0aj06OY5EFGN5_Mb1edlTK3wWKHe0-6qUXaka6lv1g0/assets/index-1213f99f.js:43:39534)
    at cb (http://homeassistant.local:8123/api/hassio_ingress/0aj06OY5EFGN5_Mb1edlTK3wWKHe0-6qUXaka6lv1g0/assets/index-1213f99f.js:43:35900)
    at AD (http://homeassistant.local:8123/api/hassio_ingress/0aj06OY5EFGN5_Mb1edlTK3wWKHe0-6qUXaka6lv1g0/assets/index-1213f99f.js:43:36704)
    at Gn (http://homeassistant.local:8123/api/hassio_ingress/0aj06OY5EFGN5_Mb1edlTK3wWKHe0-6qUXaka6lv1g0/assets/index-1213f99f.js:41:3283)
```

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by KGholam** [comment]
The device is a Tuya WSD500A, and the previous 3 "identical" devices worked fine.
