### ISSUE TITLE
Getting Error after upgrading to Ember driver from ezsp : Cannot read properties of undefined (reading 'clusters')

### ISSUE THREAD

**Issue by rhakbari** [nurikk/z2m-frontend#2272]
### What happened?

I upgraded my tasmota esp32 gateway coordinator firmware from 6.7.x to 7.4.x so that my gateway adapter can support ember driver instead of ezsp then one of my switch stopped working and started showing this error below. It was working fine before.

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: http://192.168.0.100:8123/api/hassio_ingress/47_LnmkwbyqUDSWbZZHML-eLcwN3ARegQDC0avJAxn4/#/device/0xa4c1389aa0928744/dev-console
**Previous url**: http://192.168.0.100:8123/45df7312_zigbee2mqtt


**Error type**: TypeError
**Error message**: Cannot read properties of undefined (reading 'clusters')



TypeError: Cannot read properties of undefined (reading 'clusters')
    at zs.render (http://192.168.0.100:8123/api/hassio_ingress/47_LnmkwbyqUDSWbZZHML-eLcwN3ARegQDC0avJAxn4/assets/ConnectedDevicePage-904482a0.js:1:31232)
    at ab (http://192.168.0.100:8123/api/hassio_ingress/47_LnmkwbyqUDSWbZZHML-eLcwN3ARegQDC0avJAxn4/assets/index-1213f99f.js:43:6186)
    at _D (http://192.168.0.100:8123/api/hassio_ingress/47_LnmkwbyqUDSWbZZHML-eLcwN3ARegQDC0avJAxn4/assets/index-1213f99f.js:43:5982)
    at a3 (http://192.168.0.100:8123/api/hassio_ingress/47_LnmkwbyqUDSWbZZHML-eLcwN3ARegQDC0avJAxn4/assets/index-1213f99f.js:43:44865)
    at J5 (http://192.168.0.100:8123/api/hassio_ingress/47_LnmkwbyqUDSWbZZHML-eLcwN3ARegQDC0avJAxn4/assets/index-1213f99f.js:43:39756)
    at Oze (http://192.168.0.100:8123/api/hassio_ingress/47_LnmkwbyqUDSWbZZHML-eLcwN3ARegQDC0avJAxn4/assets/index-1213f99f.js:43:39682)
    at ap (http://192.168.0.100:8123/api/hassio_ingress/47_LnmkwbyqUDSWbZZHML-eLcwN3ARegQDC0avJAxn4/assets/index-1213f99f.js:43:39534)
    at cb (http://192.168.0.100:8123/api/hassio_ingress/47_LnmkwbyqUDSWbZZHML-eLcwN3ARegQDC0avJAxn4/assets/index-1213f99f.js:43:35900)
    at AD (http://192.168.0.100:8123/api/hassio_ingress/47_LnmkwbyqUDSWbZZHML-eLcwN3ARegQDC0avJAxn4/assets/index-1213f99f.js:43:36704)
    at Gn (http://192.168.0.100:8123/api/hassio_ingress/47_LnmkwbyqUDSWbZZHML-eLcwN3ARegQDC0avJAxn4/assets/index-1213f99f.js:41:3283)
```

**Comment by Koenkk** [comment]
Could you attach the state (shows when the bug appears), also when does this exactly happen?
