### ISSUE TITLE
Hello, you've found a bug (Dev console access for unsupported ZBMINIR2)

### ISSUE THREAD

**Issue by crispylees** [nurikk/z2m-frontend#2277]
### What happened?

I clicked

zigbee2mqtt frontend > Devices > device_id > Dev console

and was greeted with a message
 (Hello, you've found a bug. Congratulations!) and instructions to create an issue

Steps to reproduce > click the same link again. Note that this device paired but did not successfully complete an interview. It is a SONOFF ZBMINIR2 (brand new, not previously paired), which is reported on the website to be supported but is reported in the frontend to be unsupported. I was starting steps to add support for new devices and clicked Dev console as the first step.

[initialState.json.zip](https://github.com/user-attachments/files/18048136/initialState.json.zip)
![Dev_console_screenshot](https://github.com/user-attachments/assets/809a047b-b160-4e5b-97e3-48e0af469eba)

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: http://192.168.11.84:8080/#/device/0x7cc6b6fffef40cf9/dev-console
**Previous url**: 


**Error type**: TypeError
**Error message**: Cannot read properties of undefined (reading 'clusters')



TypeError: Cannot read properties of undefined (reading 'clusters')
    at zs.render (http://192.168.11.84:8080/assets/ConnectedDevicePage-904482a0.js:1:31232)
    at ab (http://192.168.11.84:8080/assets/index-1213f99f.js:43:6186)
    at _D (http://192.168.11.84:8080/assets/index-1213f99f.js:43:5982)
    at a3 (http://192.168.11.84:8080/assets/index-1213f99f.js:43:44865)
    at J5 (http://192.168.11.84:8080/assets/index-1213f99f.js:43:39756)
    at Oze (http://192.168.11.84:8080/assets/index-1213f99f.js:43:39682)
    at ap (http://192.168.11.84:8080/assets/index-1213f99f.js:43:39534)
    at cb (http://192.168.11.84:8080/assets/index-1213f99f.js:43:35900)
    at AD (http://192.168.11.84:8080/assets/index-1213f99f.js:43:36704)
    at Gn (http://192.168.11.84:8080/assets/index-1213f99f.js:41:3283)
```

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by Koenkk** [comment]
Should be fixed!


Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now. Note that the dev branch currently contains **breaking changes**, see https://github.com/Koenkk/zigbee2mqtt/discussions/24198
