### ISSUE TITLE
Eror clicking Dev console with JR-ZDS02 module 

### ISSUE THREAD

**Issue by singinglarvae** [nurikk/z2m-frontend#2278]
### What happened?

Just wanted to check if a Girier JR-ZDS02 module could be added. I just clicked on Device > Dev console tab "et voilà"
Nb : no Json file available for this one
### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
TypeError
Cannot read properties of undefined (reading 'clusters')
TypeError: Cannot read properties of undefined (reading 'clusters')
    at zs.render (http://192.168.2.8:8081/assets/ConnectedDevicePage-904482a0.js:1:31232)
    at ab (http://192.168.2.8:8081/assets/index-1213f99f.js:43:6186)
    at _D (http://192.168.2.8:8081/assets/index-1213f99f.js:43:5982)
    at a3 (http://192.168.2.8:8081/assets/index-1213f99f.js:43:44865)
    at J5 (http://192.168.2.8:8081/assets/index-1213f99f.js:43:39756)
    at Oze (http://192.168.2.8:8081/assets/index-1213f99f.js:43:39682)
    at ap (http://192.168.2.8:8081/assets/index-1213f99f.js:43:39534)
    at cb (http://192.168.2.8:8081/assets/index-1213f99f.js:43:35900)
    at AD (http://192.168.2.8:8081/assets/index-1213f99f.js:43:36704)
    at Gn (http://192.168.2.8:8081/assets/index-1213f99f.js:41:3283)



TypeError: Cannot read properties of undefined (reading 'clusters')
    at zs.render (http://192.168.2.8:8081/assets/ConnectedDevicePage-904482a0.js:1:31232)
    at ab (http://192.168.2.8:8081/assets/index-1213f99f.js:43:6186)
    at _D (http://192.168.2.8:8081/assets/index-1213f99f.js:43:5982)
    at a3 (http://192.168.2.8:8081/assets/index-1213f99f.js:43:44865)
    at J5 (http://192.168.2.8:8081/assets/index-1213f99f.js:43:39756)
    at Oze (http://192.168.2.8:8081/assets/index-1213f99f.js:43:39682)
    at ap (http://192.168.2.8:8081/assets/index-1213f99f.js:43:39534)
    at cb (http://192.168.2.8:8081/assets/index-1213f99f.js:43:35900)
    at AD (http://192.168.2.8:8081/assets/index-1213f99f.js:43:36704)
    at Gn (http://192.168.2.8:8081/assets/index-1213f99f.js:41:3283)
```

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by Koenkk** [comment]
Should be fixed by https://github.com/nurikk/zigbee2mqtt-frontend/commit/06693f02c48f000e91d6337a8551acbbe4cf3cf7
