### ISSUE TITLE
mqtt error

### ISSUE THREAD

**Issue by scarin66** [nurikk/z2m-frontend#2280]
### What happened?

failed install of aqara door sensor system told me to report
[initialState.json.zip](https://github.com/user-attachments/files/18051959/initialState.json.zip)
 bug

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: https://mirtnwkucqzljp7kvuqpynotkhty93tg.ui.nabu.casa/api/hassio_ingress/4j2yLOnVWHFWzawky3XIzddT3_-uoW1o_96blfmTxmA/#/device/0x00158d000abd9fb3/dev-console
**Previous url**: https://mirtnwkucqzljp7kvuqpynotkhty93tg.ui.nabu.casa/45df7312_zigbee2mqtt


**Error type**: TypeError
**Error message**: Cannot read properties of undefined (reading 'clusters')



TypeError: Cannot read properties of undefined (reading 'clusters')
    at zs.render (https://mirtnwkucqzljp7kvuqpynotkhty93tg.ui.nabu.casa/api/hassio_ingress/4j2yLOnVWHFWzawky3XIzddT3_-uoW1o_96blfmTxmA/assets/ConnectedDevicePage-904482a0.js:1:31232)
    at ab (https://mirtnwkucqzljp7kvuqpynotkhty93tg.ui.nabu.casa/api/hassio_ingress/4j2yLOnVWHFWzawky3XIzddT3_-uoW1o_96blfmTxmA/assets/index-1213f99f.js:43:6186)
    at _D (https://mirtnwkucqzljp7kvuqpynotkhty93tg.ui.nabu.casa/api/hassio_ingress/4j2yLOnVWHFWzawky3XIzddT3_-uoW1o_96blfmTxmA/assets/index-1213f99f.js:43:5982)
    at a3 (https://mirtnwkucqzljp7kvuqpynotkhty93tg.ui.nabu.casa/api/hassio_ingress/4j2yLOnVWHFWzawky3XIzddT3_-uoW1o_96blfmTxmA/assets/index-1213f99f.js:43:44865)
    at J5 (https://mirtnwkucqzljp7kvuqpynotkhty93tg.ui.nabu.casa/api/hassio_ingress/4j2yLOnVWHFWzawky3XIzddT3_-uoW1o_96blfmTxmA/assets/index-1213f99f.js:43:39756)
    at Oze (https://mirtnwkucqzljp7kvuqpynotkhty93tg.ui.nabu.casa/api/hassio_ingress/4j2yLOnVWHFWzawky3XIzddT3_-uoW1o_96blfmTxmA/assets/index-1213f99f.js:43:39682)
    at ap (https://mirtnwkucqzljp7kvuqpynotkhty93tg.ui.nabu.casa/api/hassio_ingress/4j2yLOnVWHFWzawky3XIzddT3_-uoW1o_96blfmTxmA/assets/index-1213f99f.js:43:39534)
    at cb (https://mirtnwkucqzljp7kvuqpynotkhty93tg.ui.nabu.casa/api/hassio_ingress/4j2yLOnVWHFWzawky3XIzddT3_-uoW1o_96blfmTxmA/assets/index-1213f99f.js:43:35900)
    at AD (https://mirtnwkucqzljp7kvuqpynotkhty93tg.ui.nabu.casa/api/hassio_ingress/4j2yLOnVWHFWzawky3XIzddT3_-uoW1o_96blfmTxmA/assets/index-1213f99f.js:43:36704)
    at Gn (https://mirtnwkucqzljp7kvuqpynotkhty93tg.ui.nabu.casa/api/hassio_ingress/4j2yLOnVWHFWzawky3XIzddT3_-uoW1o_96blfmTxmA/assets/index-1213f99f.js:41:3283)
```

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by Koenkk** [comment]
should be fixed now!



Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now. Note that the dev branch currently contains **breaking changes**, see https://github.com/Koenkk/zigbee2mqtt/discussions/24198
