### ISSUE TITLE
Error while pairing a new zigbee device

### ISSUE THREAD

**Issue by Jim-91** [nurikk/z2m-frontend#2282]
### What happened?

Unable to reload devices page after pairing a new device.

Error message : 
Error
Unable to preload CSS for http://homeassistant.local:8123/api/hassio_ingress/2s9l8ISQMuAb3vx_BjvKWJbVPtp4DjzfZJRJUS39cMA/assets/index-c733cdf7.css
Error: Unable to preload CSS for http://homeassistant.local:8123/api/hassio_ingress/2s9l8ISQMuAb3vx_BjvKWJbVPtp4DjzfZJRJUS39cMA/assets/index-c733cdf7.css
    at HTMLLinkElement.<anonymous> (http://homeassistant.local:8123/api/hassio_ingress/2s9l8ISQMuAb3vx_BjvKWJbVPtp4DjzfZJRJUS39cMA/assets/index-1213f99f.js:61:9232)

![Capture d’écran 2024-12-08 à 21 41 17](https://github.com/user-attachments/assets/b18de7a6-e911-4c7d-bbb3-f9fa97ea0464)
[initialState.json.zip](https://github.com/user-attachments/files/18053932/initialState.json.zip)

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: http://homeassistant.local:8123/api/hassio_ingress/2s9l8ISQMuAb3vx_BjvKWJbVPtp4DjzfZJRJUS39cMA/#/
**Previous url**: http://homeassistant.local:8123/45df7312_zigbee2mqtt


**Error type**: Error
**Error message**: Unable to preload CSS for http://homeassistant.local:8123/api/hassio_ingress/2s9l8ISQMuAb3vx_BjvKWJbVPtp4DjzfZJRJUS39cMA/assets/index-c733cdf7.css



Error: Unable to preload CSS for http://homeassistant.local:8123/api/hassio_ingress/2s9l8ISQMuAb3vx_BjvKWJbVPtp4DjzfZJRJUS39cMA/assets/index-c733cdf7.css
    at HTMLLinkElement.<anonymous> (http://homeassistant.local:8123/api/hassio_ingress/2s9l8ISQMuAb3vx_BjvKWJbVPtp4DjzfZJRJUS39cMA/assets/index-1213f99f.js:61:9232)
```

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by hogdanish** [comment]
Same issue, stacktrace and log looks identical
