### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by bieskholodov** [nurikk/z2m-frontend#2283]
### What happened?

[initialState.json.zip](https://github.com/user-attachments/files/18060278/initialState.json.zip)

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: http://192.168.100.16:8123/api/hassio_ingress/Fz6gl25OTmmsRH4b0jy9ymCKJak-CYtCQxBbKZaa1KQ/#/device/0x404ccafffe53b064/dev-console
**Previous url**: http://192.168.100.16:8123/hassio


**Error type**: TypeError
**Error message**: Cannot read properties of undefined (reading 'clusters')



TypeError: Cannot read properties of undefined (reading 'clusters')
    at zs.render (http://192.168.100.16:8123/api/hassio_ingress/Fz6gl25OTmmsRH4b0jy9ymCKJak-CYtCQxBbKZaa1KQ/assets/ConnectedDevicePage-904482a0.js:1:31232)
    at ab (http://192.168.100.16:8123/api/hassio_ingress/Fz6gl25OTmmsRH4b0jy9ymCKJak-CYtCQxBbKZaa1KQ/assets/index-1213f99f.js:43:6186)
    at _D (http://192.168.100.16:8123/api/hassio_ingress/Fz6gl25OTmmsRH4b0jy9ymCKJak-CYtCQxBbKZaa1KQ/assets/index-1213f99f.js:43:5982)
    at a3 (http://192.168.100.16:8123/api/hassio_ingress/Fz6gl25OTmmsRH4b0jy9ymCKJak-CYtCQxBbKZaa1KQ/assets/index-1213f99f.js:43:44865)
    at J5 (http://192.168.100.16:8123/api/hassio_ingress/Fz6gl25OTmmsRH4b0jy9ymCKJak-CYtCQxBbKZaa1KQ/assets/index-1213f99f.js:43:39756)
    at Oze (http://192.168.100.16:8123/api/hassio_ingress/Fz6gl25OTmmsRH4b0jy9ymCKJak-CYtCQxBbKZaa1KQ/assets/index-1213f99f.js:43:39682)
    at ap (http://192.168.100.16:8123/api/hassio_ingress/Fz6gl25OTmmsRH4b0jy9ymCKJak-CYtCQxBbKZaa1KQ/assets/index-1213f99f.js:43:39534)
    at cb (http://192.168.100.16:8123/api/hassio_ingress/Fz6gl25OTmmsRH4b0jy9ymCKJak-CYtCQxBbKZaa1KQ/assets/index-1213f99f.js:43:35900)
    at AD (http://192.168.100.16:8123/api/hassio_ingress/Fz6gl25OTmmsRH4b0jy9ymCKJak-CYtCQxBbKZaa1KQ/assets/index-1213f99f.js:43:36704)
    at Gn (http://192.168.100.16:8123/api/hassio_ingress/Fz6gl25OTmmsRH4b0jy9ymCKJak-CYtCQxBbKZaa1KQ/assets/index-1213f99f.js:41:3283)
```

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by bieskholodov** [comment]
This is a custom device but it is installed normally in zh (16 pcs relay) esp32c6
![Снимок экрана от 2024-12-09 14-29-49](https://github.com/user-attachments/assets/4938d215-f353-4204-9c5a-ff8b53297d2d)

**Comment by Koenkk** [comment]
Could you check if this is fixed in the dev branch? 

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now. Note that the dev branch currently contains **breaking changes**, see https://github.com/Koenkk/zigbee2mqtt/discussions/24198

**Comment by bieskholodov** [comment]
I was able to fix it via file 
manually increasing the number of partitions.
   extend: [deviceEndpoints({"endpoints":{"1":1,"2":2,"3":3}}), onOff({"powerOnBehavior":false,"endpointNames":["1", "2","3"]})], And so on until 16. Judging by the error, he could not assign clusters from 1 to 16

**Comment by bieskholodov** [comment]
When I check it in the beta branch, I will write the result. Thank you

**Comment by bieskholodov** [comment]
In the beta version everything works fine. Thank you

const {deviceEndpoints, onOff} = require('zigbee-herdsman-converters/lib/modernExtend');

const definition = {
    zigbeeModel: ['zb-rele-16-esp32c6'],
    model: 'zb-rele-16-esp32c6',
    vendor: 'esphome',
    description: 'Automatically generated definition',
    extend: [deviceEndpoints({"endpoints":{"1":1,"2":2,"3":3,"4":4,"5":5,"6":6,"7":7,"8":8,"9":9,"10":10,"11":11,"12":12,"13":13,"14":14,"15":15,"16":16}}), onOff({"powerOnBehavior":false,"endpointNames":["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16"]})],
    meta: {"multiEndpoint":true},
};

module.exports = definition;
