### ISSUE TITLE
Move to Dev console tab when working with unsupported device 

### ISSUE THREAD

**Issue by crs2007** [nurikk/z2m-frontend#2285]
### What happened?

Adding new device - SOS Panic Button
The device is unsupported, moving to Dev console tab 
![image](https://github.com/user-attachments/assets/00cfae8e-1672-443d-88b6-954e5a56d88e)
[initialState.json.zip](https://github.com/user-attachments/files/18065126/initialState.json.zip)

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: http://homeassistant.local:8123/api/hassio_ingress/WUxEl3Dx6Bgd6eNELL55j0DwVBFYWz-F52BHvf9lE1Y/#/device/0xa4c1385b5268514f/dev-console
**Previous url**: http://homeassistant.local:8123/hassio


**Error type**: TypeError
**Error message**: Cannot read properties of undefined (reading 'clusters')



TypeError: Cannot read properties of undefined (reading 'clusters')
    at zs.render (http://homeassistant.local:8123/api/hassio_ingress/WUxEl3Dx6Bgd6eNELL55j0DwVBFYWz-F52BHvf9lE1Y/assets/ConnectedDevicePage-904482a0.js:1:31232)
    at ab (http://homeassistant.local:8123/api/hassio_ingress/WUxEl3Dx6Bgd6eNELL55j0DwVBFYWz-F52BHvf9lE1Y/assets/index-1213f99f.js:43:6186)
    at _D (http://homeassistant.local:8123/api/hassio_ingress/WUxEl3Dx6Bgd6eNELL55j0DwVBFYWz-F52BHvf9lE1Y/assets/index-1213f99f.js:43:5982)
    at a3 (http://homeassistant.local:8123/api/hassio_ingress/WUxEl3Dx6Bgd6eNELL55j0DwVBFYWz-F52BHvf9lE1Y/assets/index-1213f99f.js:43:44865)
    at J5 (http://homeassistant.local:8123/api/hassio_ingress/WUxEl3Dx6Bgd6eNELL55j0DwVBFYWz-F52BHvf9lE1Y/assets/index-1213f99f.js:43:39756)
    at Oze (http://homeassistant.local:8123/api/hassio_ingress/WUxEl3Dx6Bgd6eNELL55j0DwVBFYWz-F52BHvf9lE1Y/assets/index-1213f99f.js:43:39682)
    at ap (http://homeassistant.local:8123/api/hassio_ingress/WUxEl3Dx6Bgd6eNELL55j0DwVBFYWz-F52BHvf9lE1Y/assets/index-1213f99f.js:43:39534)
    at cb (http://homeassistant.local:8123/api/hassio_ingress/WUxEl3Dx6Bgd6eNELL55j0DwVBFYWz-F52BHvf9lE1Y/assets/index-1213f99f.js:43:35900)
    at AD (http://homeassistant.local:8123/api/hassio_ingress/WUxEl3Dx6Bgd6eNELL55j0DwVBFYWz-F52BHvf9lE1Y/assets/index-1213f99f.js:43:36704)
    at Gn (http://homeassistant.local:8123/api/hassio_ingress/WUxEl3Dx6Bgd6eNELL55j0DwVBFYWz-F52BHvf9lE1Y/assets/index-1213f99f.js:41:3283)
```

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by Koenkk** [comment]
Should be fixed now!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now. Note that the dev branch currently contains **breaking changes**, see https://github.com/Koenkk/zigbee2mqtt/discussions/24198
