### ISSUE TITLE
Bug: `Cannot read properties of undefined (reading 'clusters')`

### ISSUE THREAD

**Issue by nodinosaur** [nurikk/z2m-frontend#2293]
### What happened?

I tried to pair a plug, and it appeared in the device list, with an image, but also had another icon underneath.
I tried to delete the Z! icon

[initialState.json.zip](https://github.com/user-attachments/files/18112659/initialState.json.zip)
![Z2M-issue](https://github.com/user-attachments/assets/b1d45456-ddab-47b0-a9f8-e9abb9cd8906)

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: http://192.168.86.10:8123/api/hassio_ingress/BUVB6Qo7W92VSbjsXGzlJlLtdD53BcwR3bUuymVAQi8/#/device/0x001c5500000835c3/dev-console
**Previous url**: http://192.168.86.10:8123/45df7312_zigbee2mqtt


**Error type**: TypeError
**Error message**: Cannot read properties of undefined (reading 'clusters')



TypeError: Cannot read properties of undefined (reading 'clusters')
    at zs.render (http://192.168.86.10:8123/api/hassio_ingress/BUVB6Qo7W92VSbjsXGzlJlLtdD53BcwR3bUuymVAQi8/assets/ConnectedDevicePage-904482a0.js:1:31232)
    at ab (http://192.168.86.10:8123/api/hassio_ingress/BUVB6Qo7W92VSbjsXGzlJlLtdD53BcwR3bUuymVAQi8/assets/index-1213f99f.js:43:6186)
    at _D (http://192.168.86.10:8123/api/hassio_ingress/BUVB6Qo7W92VSbjsXGzlJlLtdD53BcwR3bUuymVAQi8/assets/index-1213f99f.js:43:5982)
    at a3 (http://192.168.86.10:8123/api/hassio_ingress/BUVB6Qo7W92VSbjsXGzlJlLtdD53BcwR3bUuymVAQi8/assets/index-1213f99f.js:43:44865)
    at J5 (http://192.168.86.10:8123/api/hassio_ingress/BUVB6Qo7W92VSbjsXGzlJlLtdD53BcwR3bUuymVAQi8/assets/index-1213f99f.js:43:39756)
    at Oze (http://192.168.86.10:8123/api/hassio_ingress/BUVB6Qo7W92VSbjsXGzlJlLtdD53BcwR3bUuymVAQi8/assets/index-1213f99f.js:43:39682)
    at ap (http://192.168.86.10:8123/api/hassio_ingress/BUVB6Qo7W92VSbjsXGzlJlLtdD53BcwR3bUuymVAQi8/assets/index-1213f99f.js:43:39534)
    at cb (http://192.168.86.10:8123/api/hassio_ingress/BUVB6Qo7W92VSbjsXGzlJlLtdD53BcwR3bUuymVAQi8/assets/index-1213f99f.js:43:35900)
    at AD (http://192.168.86.10:8123/api/hassio_ingress/BUVB6Qo7W92VSbjsXGzlJlLtdD53BcwR3bUuymVAQi8/assets/index-1213f99f.js:43:36704)
    at Gn (http://192.168.86.10:8123/api/hassio_ingress/BUVB6Qo7W92VSbjsXGzlJlLtdD53BcwR3bUuymVAQi8/assets/index-1213f99f.js:41:3283)
```

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by Koenkk** [comment]
After pressing what buttons did the frontend crash?

**Comment by nodinosaur** [comment]
> After pressing what buttons did the frontend crash?

the steps I took were to `Permit join (Control Outlet Media Cabinet)` which is an [Ikea E1603/E1702/E1708](https://www.zigbee2mqtt.io/devices/E1603_E1702_E1708.html#ikea-e1603%252Fe1702%252Fe1708)
Once the interview had gone through I saw that "extra" icon, when I pressed the delete I couldn't get rid of it. Otherwise the front end appeared to behave normally, occasionally the red dialog popped up, but never hung around long enough for me to be able to copy the message out of it.

I have since rolled back to my previous full back up of Home Assistant and with it Zigbee2Mqtt and retried the pairing and it worked as expected this time.

**Comment by Koenkk** [comment]
But when exactly did you get the `**Error message**: Cannot read properties of undefined (reading 'clusters')` error?

**Comment by nodinosaur** [comment]
That was after the pairing, sorry if that isn't very helpful
