### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Bluesw** [nurikk/z2m-frontend#2294]
### What happened?

restarted home assistant after updating now can not access frontend (
![874068227dd5f0f7735debd0903cc035](https://github.com/user-attachments/assets/74c05949-5521-448b-b67f-7364695fb671)
[initialState.json (1).zip](https://github.com/user-attachments/files/18115155/initialState.json.1.zip)

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Relevant stacktrace

```shell
**Current url**: http://192.168.0.74:8123/api/hassio_ingress/ZK1Ck2dduYNY1npKDGNJ3yOFBRUml1EmhqsEJ3kX1fY/#/
**Previous url**: http://192.168.0.74:8123/45df7312_zigbee2mqtt


**Error type**: Error
**Error message**: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.



Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at bm (http://192.168.0.74:8123/api/hassio_ingress/ZK1Ck2dduYNY1npKDGNJ3yOFBRUml1EmhqsEJ3kX1fY/assets/index-1213f99f.js:41:12799)
    at m (http://192.168.0.74:8123/api/hassio_ingress/ZK1Ck2dduYNY1npKDGNJ3yOFBRUml1EmhqsEJ3kX1fY/assets/index-1213f99f.js:41:14587)
    at g (http://192.168.0.74:8123/api/hassio_ingress/ZK1Ck2dduYNY1npKDGNJ3yOFBRUml1EmhqsEJ3kX1fY/assets/index-1213f99f.js:41:15740)
    at y (http://192.168.0.74:8123/api/hassio_ingress/ZK1Ck2dduYNY1npKDGNJ3yOFBRUml1EmhqsEJ3kX1fY/assets/index-1213f99f.js:41:17816)
    at Ct (http://192.168.0.74:8123/api/hassio_ingress/ZK1Ck2dduYNY1npKDGNJ3yOFBRUml1EmhqsEJ3kX1fY/assets/index-1213f99f.js:43:1479)
    at a3 (http://192.168.0.74:8123/api/hassio_ingress/ZK1Ck2dduYNY1npKDGNJ3yOFBRUml1EmhqsEJ3kX1fY/assets/index-1213f99f.js:43:45712)
    at J5 (http://192.168.0.74:8123/api/hassio_ingress/ZK1Ck2dduYNY1npKDGNJ3yOFBRUml1EmhqsEJ3kX1fY/assets/index-1213f99f.js:43:39756)
    at Oze (http://192.168.0.74:8123/api/hassio_ingress/ZK1Ck2dduYNY1npKDGNJ3yOFBRUml1EmhqsEJ3kX1fY/assets/index-1213f99f.js:43:39682)
    at ap (http://192.168.0.74:8123/api/hassio_ingress/ZK1Ck2dduYNY1npKDGNJ3yOFBRUml1EmhqsEJ3kX1fY/assets/index-1213f99f.js:43:39534)
    at cb (http://192.168.0.74:8123/api/hassio_ingress/ZK1Ck2dduYNY1npKDGNJ3yOFBRUml1EmhqsEJ3kX1fY/assets/index-1213f99f.js:43:35900)
```

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by Bluesw** [comment]
Could someone in the know help please or give me a direction to go as issuse persists and i tried a few things including changing coordinator from a lan zigbee device back to a sonoff -p dongle to no avail and dont no what to do next. and really need to get into frontend and now i have lost 2 philips hue bulbs act like bricked devices and wont respond or can get in pairing mode one died last week the other today no other zigbee devices showing problems to me. many thanks for any support/assistance :)

**Comment by Bluesw** [comment]
is this a problem out of my hands to fix? only asking due to a old post having same fault/bug
https://github.com/nurikk/zigbee2mqtt-frontend/issues/397

**Comment by Koenkk** [comment]
Could you try clearing your cache or in incognito mode?

**Comment by Bluesw** [comment]
Incognito did not help also cleared cache from all browsers and home assistant app on android now and nothing has changed.  
many thanks for you help though as i really do not know what to do and have no one to turn to for advice

**Comment by Bluesw** [comment]
fixed issuse by deleting db.tmp file and state.json while mqtt was stopped on restart frontend is accessable again i will close ticket in 24 hours just to be on safe side if problem re surfaces thanks again for assistance

**Comment by Bluesw** [comment]
Closed ticket. Fix required removal of tmp files.
