### ISSUE TITLE
Unable to preload CSS

### ISSUE THREAD

**Issue by staub79** [nurikk/z2m-frontend#2306]
### What happened?

I reloaded the page (was still open on my laptop) the next day and instead of the zigbee2mqtt page this error appeared

Error
Unable to preload CSS for http://192.168.20.31/assets/index-e4174e1c.css
Error: Unable to preload CSS for http://192.168.20.31/assets/index-e4174e1c.css
    at HTMLLinkElement.<anonymous> (http://192.168.20.31/assets/index-1213f99f.js:61:9232)

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: http://192.168.20.31/#/device/0xe0798dfffebbfa94/info
**Previous url**: 


**Error type**: Error
**Error message**: Unable to preload CSS for http://192.168.20.31/assets/index-e4174e1c.css



Error: Unable to preload CSS for http://192.168.20.31/assets/index-e4174e1c.css
    at HTMLLinkElement.<anonymous> (http://192.168.20.31/assets/index-1213f99f.js:61:9232)
```

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by staub79** [comment]
[initialState.json.zip](https://github.com/user-attachments/files/18146217/initialState.json.zip)

**Comment by hogdanish** [comment]
Same here. Identical stacktrace.
