### ISSUE TITLE
Recently reinstalled Z2M to re-pair devices, facing major issues 

### ISSUE THREAD

**Issue by Nafjan** [nurikk/z2m-frontend#2316]
### What happened?

[initialState.json.zip](https://github.com/user-attachments/files/18208175/initialState.json.zip)
![Screenshot_20241220-113000~2](https://github.com/user-attachments/assets/01a20fc8-8d46-4ef5-a505-ea011448a080)
![Screenshot_20241220-114328~3](https://github.com/user-attachments/assets/65f44df3-3f64-4f60-8a64-ac4b22b1a367)

I recently had major connectivity/interference issues with my ZigBee network on Z2M so I decided to remove all devices, reinstall Z2M and re-pair everything. 

Unfortunately, it doesn't seem to be able to pick up any devices no matter what I do (after putting them in pairing mode obviously). The only device that it saw and connected to was a USB ZigBee repeater that was working before without any external converters. Unfortunately, the interview failed even though it was automatically recognized and added before. 

For all other devices, it just doesn't see them. I'm using the Sonoff ZigBee 3.0 USB Dongle Plus, connected via an extension cable and placed away from other wireless devices. 

### What browsers are you seeing the problem on?

Firefox, Chrome

### Relevant stacktrace

```shell
**Current url**: https://lssjmsobxcs9k5yoaeqdxhsextpc5lyk.ui.nabu.casa/api/hassio_ingress/mjWAn_S7WUdRgJg8vgRq3vGjNL9ipXFWw2Y6626Aa0I/#/device/0x00124b0025614752/dev-console
**Previous url**: https://lssjmsobxcs9k5yoaeqdxhsextpc5lyk.ui.nabu.casa/45df7312_zigbee2mqtt


**Error type**: TypeError
**Error message**: Cannot read properties of undefined (reading 'clusters')



TypeError: Cannot read properties of undefined (reading 'clusters')
    at zs.render (https://lssjmsobxcs9k5yoaeqdxhsextpc5lyk.ui.nabu.casa/api/hassio_ingress/mjWAn_S7WUdRgJg8vgRq3vGjNL9ipXFWw2Y6626Aa0I/assets/ConnectedDevicePage-904482a0.js:1:31232)
    at ab (https://lssjmsobxcs9k5yoaeqdxhsextpc5lyk.ui.nabu.casa/api/hassio_ingress/mjWAn_S7WUdRgJg8vgRq3vGjNL9ipXFWw2Y6626Aa0I/assets/index-1213f99f.js:43:6186)
    at _D (https://lssjmsobxcs9k5yoaeqdxhsextpc5lyk.ui.nabu.casa/api/hassio_ingress/mjWAn_S7WUdRgJg8vgRq3vGjNL9ipXFWw2Y6626Aa0I/assets/index-1213f99f.js:43:5982)
    at a3 (https://lssjmsobxcs9k5yoaeqdxhsextpc5lyk.ui.nabu.casa/api/hassio_ingress/mjWAn_S7WUdRgJg8vgRq3vGjNL9ipXFWw2Y6626Aa0I/assets/index-1213f99f.js:43:44865)
    at J5 (https://lssjmsobxcs9k5yoaeqdxhsextpc5lyk.ui.nabu.casa/api/hassio_ingress/mjWAn_S7WUdRgJg8vgRq3vGjNL9ipXFWw2Y6626Aa0I/assets/index-1213f99f.js:43:39756)
    at Oze (https://lssjmsobxcs9k5yoaeqdxhsextpc5lyk.ui.nabu.casa/api/hassio_ingress/mjWAn_S7WUdRgJg8vgRq3vGjNL9ipXFWw2Y6626Aa0I/assets/index-1213f99f.js:43:39682)
    at ap (https://lssjmsobxcs9k5yoaeqdxhsextpc5lyk.ui.nabu.casa/api/hassio_ingress/mjWAn_S7WUdRgJg8vgRq3vGjNL9ipXFWw2Y6626Aa0I/assets/index-1213f99f.js:43:39534)
    at cb (https://lssjmsobxcs9k5yoaeqdxhsextpc5lyk.ui.nabu.casa/api/hassio_ingress/mjWAn_S7WUdRgJg8vgRq3vGjNL9ipXFWw2Y6626Aa0I/assets/index-1213f99f.js:43:35900)
    at AD (https://lssjmsobxcs9k5yoaeqdxhsextpc5lyk.ui.nabu.casa/api/hassio_ingress/mjWAn_S7WUdRgJg8vgRq3vGjNL9ipXFWw2Y6626Aa0I/assets/index-1213f99f.js:43:36704)
    at Gn (https://lssjmsobxcs9k5yoaeqdxhsextpc5lyk.ui.nabu.casa/api/hassio_ingress/mjWAn_S7WUdRgJg8vgRq3vGjNL9ipXFWw2Y6626Aa0I/assets/index-1213f99f.js:41:3283)
```

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by Merril-r** [comment]
I had something similar to this. Reinstalling gave the same issue for me. After check in the folder I saw that not all ZM2 folders were removed in my case. so I manually deleted them and any files in them, After reinstalling I was able to repair. dont know if this is an issue or just me when I removed the add-on

**Comment by Koenkk** [comment]
Could you try if this is fixed in the dev branch?

> Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now. Note that the dev branch currently contains **breaking changes**, see https://github.com/Koenkk/zigbee2mqtt/discussions/24198

**Comment by Nafjan** [comment]
I tried uninstalling Z2M and removing every single z2m file or folder I could find as per @Merril-r's post.

I then installed the dev branch from the addon store as per the suggestion from @Koenkk.

It now won't find any ZigBee devices I try to pair it with. I tried putting 10 devices in pairing mode consecutively, making sure z2m is in allow join mode. I also tried changing the ZigBee channel (20, 25) and transmit power (5, 20). I tried generating a new network_key. Same issue.

**Comment by Nafjan** [comment]
[state.json.zip](https://github.com/user-attachments/files/18239932/state.json.zip)

Here's the latest state.json.zip

**Comment by Koenkk** [comment]
Make sure to turn off all Zigbee devices first (as they could still have formed their own network)
