### ISSUE TITLE
Unable to open "Console" tab under unsupported device page. 

### ISSUE THREAD

**Issue by kondzioku** [nurikk/z2m-frontend#2319]
### What happened?

Trying many times to pair agian power plug NAS-WR01B with 2mqtt. Each time device is founded and due to issue with interview become unsupporeted. 
In device state as unsupported not able to open Console tab under device page - here I get banner "You found the bug".
Files attached by following baner and github sugesstions

[state.json.zip](https://github.com/user-attachments/files/18212395/state.json.zip)
[initialState.json.zip](https://github.com/user-attachments/files/18212397/initialState.json.zip)

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: https://kmicica33ha.duckdns.org:8123/api/hassio_ingress/QXqUqMOldwX86ZCSbDkYSG1WGavxmLG-QmAW8HjJgUY/#/device/0xa4c13813fcb92b5e/dev-console
**Previous url**: https://kmicica33ha.duckdns.org:8123/45df7312_zigbee2mqtt


**Error type**: TypeError
**Error message**: Cannot read properties of undefined (reading 'clusters')



TypeError: Cannot read properties of undefined (reading 'clusters')
    at zs.render (https://kmicica33ha.duckdns.org:8123/api/hassio_ingress/QXqUqMOldwX86ZCSbDkYSG1WGavxmLG-QmAW8HjJgUY/assets/ConnectedDevicePage-904482a0.js:1:31232)
    at ab (https://kmicica33ha.duckdns.org:8123/api/hassio_ingress/QXqUqMOldwX86ZCSbDkYSG1WGavxmLG-QmAW8HjJgUY/assets/index-1213f99f.js:43:6186)
    at _D (https://kmicica33ha.duckdns.org:8123/api/hassio_ingress/QXqUqMOldwX86ZCSbDkYSG1WGavxmLG-QmAW8HjJgUY/assets/index-1213f99f.js:43:5982)
    at a3 (https://kmicica33ha.duckdns.org:8123/api/hassio_ingress/QXqUqMOldwX86ZCSbDkYSG1WGavxmLG-QmAW8HjJgUY/assets/index-1213f99f.js:43:44865)
    at J5 (https://kmicica33ha.duckdns.org:8123/api/hassio_ingress/QXqUqMOldwX86ZCSbDkYSG1WGavxmLG-QmAW8HjJgUY/assets/index-1213f99f.js:43:39756)
    at Oze (https://kmicica33ha.duckdns.org:8123/api/hassio_ingress/QXqUqMOldwX86ZCSbDkYSG1WGavxmLG-QmAW8HjJgUY/assets/index-1213f99f.js:43:39682)
    at ap (https://kmicica33ha.duckdns.org:8123/api/hassio_ingress/QXqUqMOldwX86ZCSbDkYSG1WGavxmLG-QmAW8HjJgUY/assets/index-1213f99f.js:43:39534)
    at cb (https://kmicica33ha.duckdns.org:8123/api/hassio_ingress/QXqUqMOldwX86ZCSbDkYSG1WGavxmLG-QmAW8HjJgUY/assets/index-1213f99f.js:43:35900)
    at AD (https://kmicica33ha.duckdns.org:8123/api/hassio_ingress/QXqUqMOldwX86ZCSbDkYSG1WGavxmLG-QmAW8HjJgUY/assets/index-1213f99f.js:43:36704)
    at Gn (https://kmicica33ha.duckdns.org:8123/api/hassio_ingress/QXqUqMOldwX86ZCSbDkYSG1WGavxmLG-QmAW8HjJgUY/assets/index-1213f99f.js:41:3283)
```

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by Koenkk** [comment]
Should be fixed in the latest dev branch!

>  Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now. Note that the dev branch currently contains **breaking changes**, see https://github.com/Koenkk/zigbee2mqtt/discussions/24198
