### ISSUE TITLE
Sonoff temperature probe pairing problem

### ISSUE THREAD

**Issue by monobras79** [nurikk/z2m-frontend#2336]
### What happened?

when I want to pair my sonoff probe via the zigbee2mqtt interface it is added in the list of devices but it appears as "not supported" whereas with my previous conbee II key it worked (CONBEE 3 key currently)
[initialState.json.zip](https://github.com/user-attachments/files/18245084/initialState.json.zip)

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: http://192.168.1.36:8080/#/device/0x00124b002503264e/dev-console
**Previous url**: http://192.168.1.36/


**Error type**: TypeError
**Error message**: Cannot read properties of undefined (reading 'clusters')



TypeError: Cannot read properties of undefined (reading 'clusters')
    at zs.render (http://192.168.1.36:8080/assets/ConnectedDevicePage-904482a0.js:1:31232)
    at ab (http://192.168.1.36:8080/assets/index-1213f99f.js:43:6186)
    at _D (http://192.168.1.36:8080/assets/index-1213f99f.js:43:5982)
    at a3 (http://192.168.1.36:8080/assets/index-1213f99f.js:43:44865)
    at J5 (http://192.168.1.36:8080/assets/index-1213f99f.js:43:39756)
    at Oze (http://192.168.1.36:8080/assets/index-1213f99f.js:43:39682)
    at ap (http://192.168.1.36:8080/assets/index-1213f99f.js:43:39534)
    at cb (http://192.168.1.36:8080/assets/index-1213f99f.js:43:35900)
    at AD (http://192.168.1.36:8080/assets/index-1213f99f.js:43:36704)
    at Gn (http://192.168.1.36:8080/assets/index-1213f99f.js:41:3283)
```

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by Koenkk** [comment]
Duplicate of https://github.com/nurikk/zigbee2mqtt-frontend/issues/2293
