### ISSUE TITLE
"Cannot read property 'forEach' of undefined" on Reporting tab

### ISSUE THREAD

**Issue by Zorchz** [nurikk/z2m-frontend#236]
![image](https://user-images.githubusercontent.com/4949986/103457736-df894f00-4d12-11eb-9eb5-60519d3d4859.png)
TypeError
Cannot read property 'forEach' of undefined
TypeError: Cannot read property 'forEach' of undefined
    at http://192.168.1.29:8080/main.7b57fba2a3248673702d.js:1:59534
    at Map.forEach (<anonymous>)
    at http://192.168.1.29:8080/main.7b57fba2a3248673702d.js:1:59487
    at t.getDerivedStateFromProps (http://192.168.1.29:8080/main.7b57fba2a3248673702d.js:1:59597)
    at fa (http://192.168.1.29:8080/scripts/vendor.40030f02031d7f2b1161.js:89:48345)
    at ya (http://192.168.1.29:8080/scripts/vendor.40030f02031d7f2b1161.js:89:50057)
    at jo (http://192.168.1.29:8080/scripts/vendor.40030f02031d7f2b1161.js:89:68689)
    at qs (http://192.168.1.29:8080/scripts/vendor.40030f02031d7f2b1161.js:89:112380)
    at Eu (http://192.168.1.29:8080/scripts/vendor.40030f02031d7f2b1161.js:89:98336)
    at Iu (http://192.168.1.29:8080/scripts/vendor.40030f02031d7f2b1161.js:89:98264)

**Comment by nurikk** [comment]
Can you attach state file?

**Comment by Zorchz** [comment]
Unable to reproduce after restart Rpi, It can be closed.
