### ISSUE TITLE
TypeError Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by Konsts** [nurikk/z2m-frontend#279]
TypeError
Cannot read property 'replace' of undefined
TypeError: Cannot read property 'replace' of undefined
appeared after the last update
```
at Ze (http://192.168.1.25:8123/api/hassio_ingress/6YRhHnbzdQ1CDZKrN3cGlfz407nV3PKIXY4Ta3qOL-w/main.7b57fba2a3248673702d.js:1:34056)
    at Ye (http://192.168.1.25:8123/api/hassio_ingress/6YRhHnbzdQ1CDZKrN3cGlfz407nV3PKIXY4Ta3qOL-w/main.7b57fba2a3248673702d.js:1:34988)
    at to (http://192.168.1.25:8123/api/hassio_ingress/6YRhHnbzdQ1CDZKrN3cGlfz407nV3PKIXY4Ta3qOL-w/scripts/vendor.40030f02031d7f2b1161.js:89:58888)
    at qs (http://192.168.1.25:8123/api/hassio_ingress/6YRhHnbzdQ1CDZKrN3cGlfz407nV3PKIXY4Ta3qOL-w/scripts/vendor.40030f02031d7f2b1161.js:89:111324)
    at Eu (http://192.168.1.25:8123/api/hassio_ingress/6YRhHnbzdQ1CDZKrN3cGlfz407nV3PKIXY4Ta3qOL-w/scripts/vendor.40030f02031d7f2b1161.js:89:98336)
    at Iu (http://192.168.1.25:8123/api/hassio_ingress/6YRhHnbzdQ1CDZKrN3cGlfz407nV3PKIXY4Ta3qOL-w/scripts/vendor.40030f02031d7f2b1161.js:89:98264)
    at _u (http://192.168.1.25:8123/api/hassio_ingress/6YRhHnbzdQ1CDZKrN3cGlfz407nV3PKIXY4Ta3qOL-w/scripts/vendor.40030f02031d7f2b1161.js:89:98127)
    at cu (http://192.168.1.25:8123/api/hassio_ingress/6YRhHnbzdQ1CDZKrN3cGlfz407nV3PKIXY4Ta3qOL-w/scripts/vendor.40030f02031d7f2b1161.js:89:95114)
    at http://192.168.1.25:8123/api/hassio_ingress/6YRhHnbzdQ1CDZKrN3cGlfz407nV3PKIXY4Ta3qOL-w/scripts/vendor.40030f02031d7f2b1161.js:89:44783
    at t.unstable_runWithPriority (http://192.168.1.25:8123/api/hassio_ingress/6YRhHnbzdQ1CDZKrN3cGlfz407nV3PKIXY4Ta3qOL-w/scripts/vendor.40030f02031d7f2b1161.js:9:3768)

```
[state (2).zip](https://github.com/nurikk/z2m-frontend/files/5869103/state.2.zip)
![error](https://user-images.githubusercontent.com/7313400/105754243-80ee7400-5f52-11eb-8c6a-0e5b19b19b0b.PNG)

**Comment by nurikk** [comment]
Hello, it seems you have added device using external converter, but your definition is incorrect. Don't omit fields, kindly refer to official documentation
