### ISSUE TITLE
Got error: Cannot read property 'ieee_address' of undefined

### ISSUE THREAD

**Issue by bjornero** [nurikk/z2m-frontend#298]
Hi. 
Trying to go to the groups tab in the UI and got this message:
![image](https://user-images.githubusercontent.com/77730183/107071409-ee1cc780-67e4-11eb-8e5e-5b31b9178238.png)

This is the file, had to zip it since i can not upload.json:
[state.zip](https://github.com/nurikk/z2m-frontend/files/5934397/state.zip)

This is the full text:
TypeError
Cannot read property 'ieee_address' of undefined
TypeError: Cannot read property 'ieee_address' of undefined
    at t.render (http://192.168.1.132:8123/api/hassio_ingress/DBMQi9XYL3P5Ld5QTkOC5PEnfULI8gR_czBJ9Qdbeak/main.92526ad5964cfad9bd7d.js:1:99578)
    at Vo (http://192.168.1.132:8123/api/hassio_ingress/DBMQi9XYL3P5Ld5QTkOC5PEnfULI8gR_czBJ9Qdbeak/scripts/vendor.22be7ecfd4aef8b0b349.js:2:469005)
    at zo (http://192.168.1.132:8123/api/hassio_ingress/DBMQi9XYL3P5Ld5QTkOC5PEnfULI8gR_czBJ9Qdbeak/scripts/vendor.22be7ecfd4aef8b0b349.js:2:468804)
    at Vu (http://192.168.1.132:8123/api/hassio_ingress/DBMQi9XYL3P5Ld5QTkOC5PEnfULI8gR_czBJ9Qdbeak/scripts/vendor.22be7ecfd4aef8b0b349.js:2:509322)
    at Ds (http://192.168.1.132:8123/api/hassio_ingress/DBMQi9XYL3P5Ld5QTkOC5PEnfULI8gR_czBJ9Qdbeak/scripts/vendor.22be7ecfd4aef8b0b349.js:2:495701)
    at bs (http://192.168.1.132:8123/api/hassio_ingress/DBMQi9XYL3P5Ld5QTkOC5PEnfULI8gR_czBJ9Qdbeak/scripts/vendor.22be7ecfd4aef8b0b349.js:2:495629)
    at gs (http://192.168.1.132:8123/api/hassio_ingress/DBMQi9XYL3P5Ld5QTkOC5PEnfULI8gR_czBJ9Qdbeak/scripts/vendor.22be7ecfd4aef8b0b349.js:2:495492)
    at ds (http://192.168.1.132:8123/api/hassio_ingress/DBMQi9XYL3P5Ld5QTkOC5PEnfULI8gR_czBJ9Qdbeak/scripts/vendor.22be7ecfd4aef8b0b349.js:2:492648)
    at http://192.168.1.132:8123/api/hassio_ingress/DBMQi9XYL3P5Ld5QTkOC5PEnfULI8gR_czBJ9Qdbeak/scripts/vendor.22be7ecfd4aef8b0b349.js:2:442356
    at t.unstable_runWithPriority (http://192.168.1.132:8123/api/hassio_ingress/DBMQi9XYL3P5Ld5QTkOC5PEnfULI8gR_czBJ9Qdbeak/scripts/vendor.22be7ecfd4aef8b0b349.js:2:545263)

Tried rebooting a couple of times, but it does not go away.

**Comment by nurikk** [comment]
what did you do when you've got this error? on which page?

**Comment by nurikk** [comment]
Additionally you can switch to edge version and check again

**Comment by bjornero** [comment]
Did not change to the edge version, but i am pretty shore i figured out what the problem was. Turns out one of my devices that belonged to a group had left the ZigBee network. I repaired the device and suddenly the group tab started working again.
