### ISSUE TITLE
Got error: Cannot read property 'ieee_address' of undefined

### ISSUE THREAD

**Issue by Diaryofamadman** [nurikk/z2m-frontend#396]
Hi, I cant access  groups. keeps getting this error

**Current url**: http://homeassistant.local:8123/api/hassio_ingress/Vn_NKOAV0lKO45Y_YXeaPxOD8K1fpHXbaETbdsHDxLs/#/groups
**Previous url**: http://homeassistant.local:8123/110c40b1_zigbee2mqtt/dashboard

**Error type**: TypeError
**Error message**: Cannot read property 'ieee_address' of undefined

TypeError: Cannot read property 'ieee_address' of undefined
    at t.render (http://homeassistant.local:8123/api/hassio_ingress/Vn_NKOAV0lKO45Y_YXeaPxOD8K1fpHXbaETbdsHDxLs/main.7c791b396724cd5681c7.js:1:99181)
    at Ha (http://homeassistant.local:8123/api/hassio_ingress/Vn_NKOAV0lKO45Y_YXeaPxOD8K1fpHXbaETbdsHDxLs/scripts/vendor.d2ddf849cc03b8f1b4ad.js:2:918059)
    at za (http://homeassistant.local:8123/api/hassio_ingress/Vn_NKOAV0lKO45Y_YXeaPxOD8K1fpHXbaETbdsHDxLs/scripts/vendor.d2ddf849cc03b8f1b4ad.js:2:917858)
    at Hs (http://homeassistant.local:8123/api/hassio_ingress/Vn_NKOAV0lKO45Y_YXeaPxOD8K1fpHXbaETbdsHDxLs/scripts/vendor.d2ddf849cc03b8f1b4ad.js:2:958773)
    at _l (http://homeassistant.local:8123/api/hassio_ingress/Vn_NKOAV0lKO45Y_YXeaPxOD8K1fpHXbaETbdsHDxLs/scripts/vendor.d2ddf849cc03b8f1b4ad.js:2:944924)
    at xl (http://homeassistant.local:8123/api/hassio_ingress/Vn_NKOAV0lKO45Y_YXeaPxOD8K1fpHXbaETbdsHDxLs/scripts/vendor.d2ddf849cc03b8f1b4ad.js:2:944852)
    at Sl (http://homeassistant.local:8123/api/hassio_ingress/Vn_NKOAV0lKO45Y_YXeaPxOD8K1fpHXbaETbdsHDxLs/scripts/vendor.d2ddf849cc03b8f1b4ad.js:2:944715)
    at fl (http://homeassistant.local:8123/api/hassio_ingress/Vn_NKOAV0lKO45Y_YXeaPxOD8K1fpHXbaETbdsHDxLs/scripts/vendor.d2ddf849cc03b8f1b4ad.js:2:941702)
    at http://homeassistant.local:8123/api/hassio_ingress/Vn_NKOAV0lKO45Y_YXeaPxOD8K1fpHXbaETbdsHDxLs/scripts/vendor.d2ddf849cc03b8f1b4ad.js:2:891410
    at t.unstable_runWithPriority (http://homeassistant.local:8123/api/hassio_ingress/Vn_NKOAV0lKO45Y_YXeaPxOD8K1fpHXbaETbdsHDxLs/scripts/vendor.d2ddf849cc03b8f1b4ad.js:2:994763)

**Comment by nurikk** [comment]
Hi!
Can you attach complete state.json file from `Settings -> Tools -> Download state` ?

**Comment by Diaryofamadman** [comment]
Hi, thank you for your reply, and apologies for late reply. Everything
works perfectly now, I've done several restarts of the add-on, and the the
error cleared. The issue can be closed. Much appreciated all the hard work
you do.

Best regards,
Grigore-Cristian Tiplea
