### ISSUE TITLE
Got error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=Invalid%20Date for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

### ISSUE THREAD

**Issue by salopette** [nurikk/z2m-frontend#397]
DESCRIBE HERE WHAT HAPPENED AND WHAT YOU EXPECTED TO HAPPEN

Dashboard no longer works with the update

**Current url**: http://192.168.178.37:8080/#/dashboard
**Previous url**: http://192.168.178.37:8080/

**Error type**: Error
**Error message**: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=Invalid%20Date for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=Invalid%20Date for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at wa (http://192.168.178.37:8080/scripts/vendor.80affb35364c26bbef84.js:2:1003019)
    at http://192.168.178.37:8080/scripts/vendor.80affb35364c26bbef84.js:2:1007856
    at Po (http://192.168.178.37:8080/scripts/vendor.80affb35364c26bbef84.js:2:1018850)
    at Us (http://192.168.178.37:8080/scripts/vendor.80affb35364c26bbef84.js:2:1064813)
    at El (http://192.168.178.37:8080/scripts/vendor.80affb35364c26bbef84.js:2:1050214)
    at Sl (http://192.168.178.37:8080/scripts/vendor.80affb35364c26bbef84.js:2:1050142)
    at _l (http://192.168.178.37:8080/scripts/vendor.80affb35364c26bbef84.js:2:1050005)
    at fl (http://192.168.178.37:8080/scripts/vendor.80affb35364c26bbef84.js:2:1046992)
    at http://192.168.178.37:8080/scripts/vendor.80affb35364c26bbef84.js:2:996700
    at t.unstable_runWithPriority (http://192.168.178.37:8080/scripts/vendor.80affb35364c26bbef84.js:2:1100053)

![sshot-1](https://user-images.githubusercontent.com/32480002/111861473-c32ea300-894e-11eb-8371-7754c5d6a810.jpg)
[state.json.zip](https://github.com/nurikk/z2m-frontend/files/6175009/state.json.zip)

**Comment by nurikk** [comment]
The very first man who can follow instructions! :) Fixed in latest dev

**Comment by salopette** [comment]
It Works! 
THX!

**Comment by Bluesw** [comment]
Its back minified react error 31 for me
