### ISSUE TITLE
Got error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by xrust83** [nurikk/z2m-frontend#398]
DESCRIBE HERE WHAT HAPPENED AND WHAT YOU EXPECTED TO HAPPEN

**Current url**: http://192.168.31.132:8080/#/map
**Previous url**: 

**Error type**: NotFoundError
**Error message**: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at bs (http://192.168.31.132:8080/scripts/vendor.d2ddf849cc03b8f1b4ad.js:2:936105)
    at Dl (http://192.168.31.132:8080/scripts/vendor.d2ddf849cc03b8f1b4ad.js:2:947855)
    at t.unstable_runWithPriority (http://192.168.31.132:8080/scripts/vendor.d2ddf849cc03b8f1b4ad.js:2:994763)
    at Hi (http://192.168.31.132:8080/scripts/vendor.d2ddf849cc03b8f1b4ad.js:2:891187)
    at Il (http://192.168.31.132:8080/scripts/vendor.d2ddf849cc03b8f1b4ad.js:2:945816)
    at fl (http://192.168.31.132:8080/scripts/vendor.d2ddf849cc03b8f1b4ad.js:2:941927)
    at http://192.168.31.132:8080/scripts/vendor.d2ddf849cc03b8f1b4ad.js:2:891410
    at t.unstable_runWithPriority (http://192.168.31.132:8080/scripts/vendor.d2ddf849cc03b8f1b4ad.js:2:994763)
    at Hi (http://192.168.31.132:8080/scripts/vendor.d2ddf849cc03b8f1b4ad.js:2:891187)
    at Vi (http://192.168.31.132:8080/scripts/vendor.d2ddf849cc03b8f1b4ad.js:2:891355)

**Comment by nurikk** [comment]
Hi!
Can you attach complete state.json file from `Settings -> Tools -> Download state` ?
