### ISSUE TITLE
Got error: Cannot read property 'source' of undefined

### ISSUE THREAD

**Issue by OvCa77** [nurikk/z2m-frontend#440]
DESCRIBE HERE WHAT HAPPENED AND WHAT YOU EXPECTED TO HAPPEN
I encountered this page when making map of network.

![image](https://user-images.githubusercontent.com/42266910/114385845-c9e8b880-9b90-11eb-8f7b-2442da359ef0.png)

[state.zip](https://github.com/nurikk/z2m-frontend/files/6296115/state.zip)

**Current url**: http://192.168.1.15:8123/api/hassio_ingress/gFfhdWT91t2E19oUVhq8aUBmY8D_Gqyl2D0fAuRqgho/#/map
**Previous url**: http://192.168.1.15:8123/7ad98f9c_zigbee2mqtt/dashboard

**Error type**: TypeError
**Error message**: Cannot read property 'source' of undefined

TypeError: Cannot read property 'source' of undefined
    at SVGPathElement.s (http://192.168.1.15:8123/api/hassio_ingress/gFfhdWT91t2E19oUVhq8aUBmY8D_Gqyl2D0fAuRqgho/main.7c791b396724cd5681c7.js:1:21473)
    at SVGPathElement.<anonymous> (http://192.168.1.15:8123/api/hassio_ingress/gFfhdWT91t2E19oUVhq8aUBmY8D_Gqyl2D0fAuRqgho/scripts/vendor.d2ddf849cc03b8f1b4ad.js:2:678706)
    at se.each (http://192.168.1.15:8123/api/hassio_ingress/gFfhdWT91t2E19oUVhq8aUBmY8D_Gqyl2D0fAuRqgho/scripts/vendor.d2ddf849cc03b8f1b4ad.js:2:676522)
    at se.s [as style] (http://192.168.1.15:8123/api/hassio_ingress/gFfhdWT91t2E19oUVhq8aUBmY8D_Gqyl2D0fAuRqgho/scripts/vendor.d2ddf849cc03b8f1b4ad.js:2:678845)
    at Ie (http://192.168.1.15:8123/api/hassio_ingress/gFfhdWT91t2E19oUVhq8aUBmY8D_Gqyl2D0fAuRqgho/main.7c791b396724cd5681c7.js:1:21572)
    at t.updateNodes (http://192.168.1.15:8123/api/hassio_ingress/gFfhdWT91t2E19oUVhq8aUBmY8D_Gqyl2D0fAuRqgho/main.7c791b396724cd5681c7.js:1:22608)
    at t.componentDidUpdate (http://192.168.1.15:8123/api/hassio_ingress/gFfhdWT91t2E19oUVhq8aUBmY8D_Gqyl2D0fAuRqgho/main.7c791b396724cd5681c7.js:1:23711)
    at ds (http://192.168.1.15:8123/api/hassio_ingress/gFfhdWT91t2E19oUVhq8aUBmY8D_Gqyl2D0fAuRqgho/scripts/vendor.d2ddf849cc03b8f1b4ad.js:2:932326)
    at Dl (http://192.168.1.15:8123/api/hassio_ingress/gFfhdWT91t2E19oUVhq8aUBmY8D_Gqyl2D0fAuRqgho/scripts/vendor.d2ddf849cc03b8f1b4ad.js:2:949077)
    at t.unstable_runWithPriority (http://192.168.1.15:8123/api/hassio_ingress/gFfhdWT91t2E19oUVhq8aUBmY8D_Gqyl2D0fAuRqgho/scripts/vendor.d2ddf849cc03b8f1b4ad.js:2:994763)

**Comment by nurikk** [comment]
Hi, can you try to update to the latest z2m version?

**Comment by OvCa77** [comment]
Hello, I am using updated version:1.18.1-1

**Comment by nurikk** [comment]
Latest version is 1.8.2

**Comment by OvCa77** [comment]
Thanks for notice, I made update, if still present will report.
