### ISSUE TITLE
Activating frontend produces error in Homebridge UI

### ISSUE THREAD

**Issue by to-schi** [nurikk/z2m-frontend#544]
Hi,
I am running a CC2530 (DL-20 UART) with Mosquitto, Zigbee2MQTT, Homebridge and Homebridge-Z2M-plugin on a Raspberry Pi Zero W. When I activate the Zigbee2MQTT frontend, it works fine, but Homebridge-log shows this Error:
...
[21.5.2021, 23:51:07] [Homebridge UI] Homebridge Config UI X v4.41.1 is listening on :: port 8581
[21.5.2021, 23:51:11] [HB Supervisor] Delaying Homebridge startup by 20 seconds on low powered server
[21.5.2021, 23:51:15] [Homebridge UI] TypeError: Invalid Version: undefined
[21.5.2021, 23:51:15] [Homebridge UI] Caught Unhandled Rejection Error :: Details Below
TypeError: Invalid Version: undefined
    at new SemVer (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/classes/semver.js:19:13)
    at compare (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/functions/compare.js:3:3)
    at Object.gt (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/functions/gt.js:2:29)
    at StatusService.checkHomebridgeStatus (/usr/local/lib/node_modules/homebridge-config-ui-x/dist/main.js:70560:54)
    at StatusService.getHomebridgeStats (/usr/local/lib/node_modules/homebridge-config-ui-x/dist/main.js:70556:32)
    at StatusService.watchStats (/usr/local/lib/node_modules/homebridge-config-ui-x/dist/main.js:70526:53)
    at StatusGateway.serverStatus (/usr/local/lib/node_modules/homebridge-config-ui-x/dist/main.js:70195:28)
    at /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/@nestjs/websockets/context/ws-context-creator.js:43:33
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at StatusGateway.<anonymous> (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/@nestjs/websockets/context/ws-proxy.js:12:32)
    at WebSocketsController.pickResult (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/@nestjs/websockets/web-sockets-controller.js:86:24)
[21.5.2021, 23:51:26] [Homebridge UI] [npm] Failed to check registry.npmjs.org for updates: "timeout of 5000ms exceeded" - see https://git.io/JJSz6 for help.
[21.5.2021, 23:51:31] [HB Supervisor] Starting Homebridge with extra flags: -I
[21.5.2021, 23:51:31] [HB Supervisor] Started Homebridge v1.3.4 with PID: 819

Homebridge and Zigbee2MQTT seem to work nevertheless.
When I deactivate the frontend, the error is gone.

**Comment by to-schi** [comment]
The problem was solved by re-installing node.js

**Comment by to-schi** [comment]
Added --> to configuration.yaml:

homeassistant: false
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://localhost'
-->    include_device_information: true
-->    keepalive: 60
serial:
  port: /dev/ttyAMA0
devices:
  '0x00158d00039d9a48':
    friendly_name: '0x00158d00039d9a48'
user: user
password: password
frontend:
  port: 8787
-->  advanced:
-->    baudrate: 115200
-->    ikea_ota_use_test_url: false
-->    log_syslog:
-->      app_name: Zigbee2MQTT
-->      eol: /n
-->      host: localhost
-->      localhost: localhost
-->      path: /dev/log
-->      pid: process.pid
-->      port: 123
-->      protocol: tcp4
-->      type: '5424'

No error in homebridge-log now.

**Comment by to-schi** [comment]
Updating node.js to 14.17.0 and re-installing Zigbee2mqtt and homebridge did not change anything.

**Comment by nurikk** [comment]
Hi, try to change port number in frontend settings. If any issues feel free to reopen
