### ISSUE TITLE
Got error: Cannot read property 'lastAttributeReadResult' of undefined

### ISSUE THREAD

**Issue by datvista** [nurikk/z2m-frontend#545]
DESCRIBE HERE WHAT HAPPENED AND WHAT YOU EXPECTED TO HAPPEN

**Current url**: https://datvista.duckdns.org/api/hassio_ingress/lVfBwee6P4xsiqchEeFuNly69nvpKOizP8rpFc7Xp8Y/#/device/0x5c0272fffe03fdc6/dev-console
**Previous url**: https://datvista.duckdns.org/7ad98f9c_zigbee2mqtt_edge

**Error type**: TypeError
**Error message**: Cannot read property 'lastAttributeReadResult' of undefined

TypeError: Cannot read property 'lastAttributeReadResult' of undefined
    at fn.renderLastResult (https://datvista.duckdns.org/api/hassio_ingress/lVfBwee6P4xsiqchEeFuNly69nvpKOizP8rpFc7Xp8Y/main.e0e6e94f0a0c688a4299.js:1:64661)
    at fn.render (https://datvista.duckdns.org/api/hassio_ingress/lVfBwee6P4xsiqchEeFuNly69nvpKOizP8rpFc7Xp8Y/main.e0e6e94f0a0c688a4299.js:1:66648)
    at Ua (https://datvista.duckdns.org/api/hassio_ingress/lVfBwee6P4xsiqchEeFuNly69nvpKOizP8rpFc7Xp8Y/scripts/vendor.b96668a1d56374f6ea1e.js:2:1023905)
    at ja (https://datvista.duckdns.org/api/hassio_ingress/lVfBwee6P4xsiqchEeFuNly69nvpKOizP8rpFc7Xp8Y/scripts/vendor.b96668a1d56374f6ea1e.js:2:1023704)
    at Us (https://datvista.duckdns.org/api/hassio_ingress/lVfBwee6P4xsiqchEeFuNly69nvpKOizP8rpFc7Xp8Y/scripts/vendor.b96668a1d56374f6ea1e.js:2:1064619)
    at El (https://datvista.duckdns.org/api/hassio_ingress/lVfBwee6P4xsiqchEeFuNly69nvpKOizP8rpFc7Xp8Y/scripts/vendor.b96668a1d56374f6ea1e.js:2:1050770)
    at Sl (https://datvista.duckdns.org/api/hassio_ingress/lVfBwee6P4xsiqchEeFuNly69nvpKOizP8rpFc7Xp8Y/scripts/vendor.b96668a1d56374f6ea1e.js:2:1050698)
    at _l (https://datvista.duckdns.org/api/hassio_ingress/lVfBwee6P4xsiqchEeFuNly69nvpKOizP8rpFc7Xp8Y/scripts/vendor.b96668a1d56374f6ea1e.js:2:1050561)
    at fl (https://datvista.duckdns.org/api/hassio_ingress/lVfBwee6P4xsiqchEeFuNly69nvpKOizP8rpFc7Xp8Y/scripts/vendor.b96668a1d56374f6ea1e.js:2:1047548)
    at https://datvista.duckdns.org/api/hassio_ingress/lVfBwee6P4xsiqchEeFuNly69nvpKOizP8rpFc7Xp8Y/scripts/vendor.b96668a1d56374f6ea1e.js:2:997256

**Comment by datvista** [comment]
![Uploading Screenshot_20210523-162052.png…]()

**Comment by nurikk** [comment]
Incomplete issue
Incomplete issue, all required information is missing
