### ISSUE TITLE
Got error: Cannot read property 'source' of undefined

### ISSUE THREAD

**Issue by KrzysztofHajdamowicz** [nurikk/z2m-frontend#556]
DESCRIBE HERE WHAT HAPPENED AND WHAT YOU EXPECTED TO HAPPEN

I've clicked on device on network map

**Current url**: https://homeassistant.MY_HOME_ASSISTANT/api/hassio_ingress/jfl1omp8TiyagE0weJt0Hibwx38d3HEl6mCFh3ma-5E/#/map
**Previous url**: https://homeassistant.MY_HOME_ASSISTANT/45df7312_zigbee2mqtt/dashboard

**Error type**: TypeError
**Error message**: Cannot read property 'source' of undefined

TypeError: Cannot read property 'source' of undefined
    at SVGPathElement.o (https://homeassistant.MY_HOME_ASSISTANT/api/hassio_ingress/jfl1omp8TiyagE0weJt0Hibwx38d3HEl6mCFh3ma-5E/main.22f9c9018f9c72dffcff.js:1:16767)
    at SVGPathElement.<anonymous> (https://homeassistant.MY_HOME_ASSISTANT/api/hassio_ingress/jfl1omp8TiyagE0weJt0Hibwx38d3HEl6mCFh3ma-5E/scripts/vendor.46f2f1bd08054c950eed.js:2:680722)
    at se.each (https://homeassistant.MY_HOME_ASSISTANT/api/hassio_ingress/jfl1omp8TiyagE0weJt0Hibwx38d3HEl6mCFh3ma-5E/scripts/vendor.46f2f1bd08054c950eed.js:2:678538)
    at se.s [as style] (https://homeassistant.MY_HOME_ASSISTANT/api/hassio_ingress/jfl1omp8TiyagE0weJt0Hibwx38d3HEl6mCFh3ma-5E/scripts/vendor.46f2f1bd08054c950eed.js:2:680861)
    at https://homeassistant.MY_HOME_ASSISTANT/api/hassio_ingress/jfl1omp8TiyagE0weJt0Hibwx38d3HEl6mCFh3ma-5E/main.22f9c9018f9c72dffcff.js:1:16848
    at Ne.updateNodes (https://homeassistant.MY_HOME_ASSISTANT/api/hassio_ingress/jfl1omp8TiyagE0weJt0Hibwx38d3HEl6mCFh3ma-5E/main.22f9c9018f9c72dffcff.js:1:16969)
    at Ne.componentDidUpdate (https://homeassistant.MY_HOME_ASSISTANT/api/hassio_ingress/jfl1omp8TiyagE0weJt0Hibwx38d3HEl6mCFh3ma-5E/main.22f9c9018f9c72dffcff.js:1:17958)
    at ds (https://homeassistant.MY_HOME_ASSISTANT/api/hassio_ingress/jfl1omp8TiyagE0weJt0Hibwx38d3HEl6mCFh3ma-5E/scripts/vendor.46f2f1bd08054c950eed.js:2:1038257)
    at kl (https://homeassistant.MY_HOME_ASSISTANT/api/hassio_ingress/jfl1omp8TiyagE0weJt0Hibwx38d3HEl6mCFh3ma-5E/scripts/vendor.46f2f1bd08054c950eed.js:2:1055008)
    at t.unstable_runWithPriority (https://homeassistant.MY_HOME_ASSISTANT/api/hassio_ingress/jfl1omp8TiyagE0weJt0Hibwx38d3HEl6mCFh3ma-5E/scripts/vendor.46f2f1bd08054c950eed.js:2:1100694)
[initialState.json.zip](https://github.com/nurikk/z2m-frontend/files/6566350/initialState.json.zip)

**Comment by nurikk** [comment]
Hi, can you help me to identify which device you've clicked?
