### ISSUE TITLE
Got error: Cannot read property 'source' of undefined

### ISSUE THREAD

**Issue by ftiradom** [nurikk/z2m-frontend#669]
I was on the map seeing the routers with whom they connected and I got the error message

TypeError
Cannot read property 'source' of undefined
TypeError: Cannot read property 'source' of undefined
    at SVGPathElement.l (http://192.168.1.10:8123/api/hassio_ingress/BNImRw5XhR-sxRnetE0YxjfdLasdHmJU-SUqP_p9cQo/main.125c9bd8fa26692dd8b6.js:1:18171)
    at SVGPathElement.<anonymous> (http://192.168.1.10:8123/api/hassio_ingress/BNImRw5XhR-sxRnetE0YxjfdLasdHmJU-SUqP_p9cQo/scripts/vendor.a0ef53a74e6d2443acda.js:2:681093)
    at se.each (http://192.168.1.10:8123/api/hassio_ingress/BNImRw5XhR-sxRnetE0YxjfdLasdHmJU-SUqP_p9cQo/scripts/vendor.a0ef53a74e6d2443acda.js:2:678909)
    at se.s [as style] (http://192.168.1.10:8123/api/hassio_ingress/BNImRw5XhR-sxRnetE0YxjfdLasdHmJU-SUqP_p9cQo/scripts/vendor.a0ef53a74e6d2443acda.js:2:681232)
    at http://192.168.1.10:8123/api/hassio_ingress/BNImRw5XhR-sxRnetE0YxjfdLasdHmJU-SUqP_p9cQo/main.125c9bd8fa26692dd8b6.js:1:18252
    at Oe.updateNodes (http://192.168.1.10:8123/api/hassio_ingress/BNImRw5XhR-sxRnetE0YxjfdLasdHmJU-SUqP_p9cQo/main.125c9bd8fa26692dd8b6.js:1:18373)
    at Oe.componentDidUpdate (http://192.168.1.10:8123/api/hassio_ingress/BNImRw5XhR-sxRnetE0YxjfdLasdHmJU-SUqP_p9cQo/main.125c9bd8fa26692dd8b6.js:1:19362)
    at ds (http://192.168.1.10:8123/api/hassio_ingress/BNImRw5XhR-sxRnetE0YxjfdLasdHmJU-SUqP_p9cQo/scripts/vendor.a0ef53a74e6d2443acda.js:2:1087409)
    at Il (http://192.168.1.10:8123/api/hassio_ingress/BNImRw5XhR-sxRnetE0YxjfdLasdHmJU-SUqP_p9cQo/scripts/vendor.a0ef53a74e6d2443acda.js:2:1104160)
    at t.unstable_runWithPriority (http://192.168.1.10:8123/api/hassio_ingress/BNImRw5XhR-sxRnetE0YxjfdLasdHmJU-SUqP_p9cQo/scripts/vendor.a0ef53a74e6d2443acda.js:2:1156698)
[initialState.json.zip](https://github.com/nurikk/z2m-frontend/files/6818687/initialState.json.zip)

**Current url**: http://192.168.1.10:8123/api/hassio_ingress/BNImRw5XhR-sxRnetE0YxjfdLasdHmJU-SUqP_p9cQo/#/map
**Previous url**: http://192.168.1.10:8123/45df7312_zigbee2mqtt

**Error type**: TypeError
**Error message**: Cannot read property 'source' of undefined

TypeError: Cannot read property 'source' of undefined
    at SVGPathElement.l (http://192.168.1.10:8123/api/hassio_ingress/BNImRw5XhR-sxRnetE0YxjfdLasdHmJU-SUqP_p9cQo/main.125c9bd8fa26692dd8b6.js:1:18171)
    at SVGPathElement.<anonymous> (http://192.168.1.10:8123/api/hassio_ingress/BNImRw5XhR-sxRnetE0YxjfdLasdHmJU-SUqP_p9cQo/scripts/vendor.a0ef53a74e6d2443acda.js:2:681093)
    at se.each (http://192.168.1.10:8123/api/hassio_ingress/BNImRw5XhR-sxRnetE0YxjfdLasdHmJU-SUqP_p9cQo/scripts/vendor.a0ef53a74e6d2443acda.js:2:678909)
    at se.s [as style] (http://192.168.1.10:8123/api/hassio_ingress/BNImRw5XhR-sxRnetE0YxjfdLasdHmJU-SUqP_p9cQo/scripts/vendor.a0ef53a74e6d2443acda.js:2:681232)
    at http://192.168.1.10:8123/api/hassio_ingress/BNImRw5XhR-sxRnetE0YxjfdLasdHmJU-SUqP_p9cQo/main.125c9bd8fa26692dd8b6.js:1:18252
    at Oe.updateNodes (http://192.168.1.10:8123/api/hassio_ingress/BNImRw5XhR-sxRnetE0YxjfdLasdHmJU-SUqP_p9cQo/main.125c9bd8fa26692dd8b6.js:1:18373)
    at Oe.componentDidUpdate (http://192.168.1.10:8123/api/hassio_ingress/BNImRw5XhR-sxRnetE0YxjfdLasdHmJU-SUqP_p9cQo/main.125c9bd8fa26692dd8b6.js:1:19362)
    at ds (http://192.168.1.10:8123/api/hassio_ingress/BNImRw5XhR-sxRnetE0YxjfdLasdHmJU-SUqP_p9cQo/scripts/vendor.a0ef53a74e6d2443acda.js:2:1087409)
    at Il (http://192.168.1.10:8123/api/hassio_ingress/BNImRw5XhR-sxRnetE0YxjfdLasdHmJU-SUqP_p9cQo/scripts/vendor.a0ef53a74e6d2443acda.js:2:1104160)
    at t.unstable_runWithPriority (http://192.168.1.10:8123/api/hassio_ingress/BNImRw5XhR-sxRnetE0YxjfdLasdHmJU-SUqP_p9cQo/scripts/vendor.a0ef53a74e6d2443acda.js:2:1156698)

**Comment by nurikk** [comment]
Hello, can you update to the latest `z2m dev`, and try to reproduce the bug? If able to reproduce raise another ticket
