### ISSUE TITLE
Got error: Cannot read property 'ieee_address' of undefined

### ISSUE THREAD

**Issue by DTTerastar** [nurikk/z2m-frontend#674]
[initialState.json.zip](https://github.com/nurikk/z2m-frontend/files/6834666/initialState.json.zip)

Just clicked on Groups.

**Current url**: https://zigbee2mqtt.z13.org/#/groups
**Previous url**: https://zigbee2mqtt.z13.org/

**Error type**: TypeError
**Error message**: Cannot read property 'ieee_address' of undefined

TypeError: Cannot read property 'ieee_address' of undefined
    at _a (https://zigbee2mqtt.z13.org/main.100d892eb09595171725.js:1:84383)
    at ra (https://zigbee2mqtt.z13.org/scripts/vendor.70e4fd8417d338e0fdad.js:2:1056182)
    at Us (https://zigbee2mqtt.z13.org/scripts/vendor.70e4fd8417d338e0fdad.js:2:1108387)
    at El (https://zigbee2mqtt.z13.org/scripts/vendor.70e4fd8417d338e0fdad.js:2:1095594)
    at _l (https://zigbee2mqtt.z13.org/scripts/vendor.70e4fd8417d338e0fdad.js:2:1095522)
    at Sl (https://zigbee2mqtt.z13.org/scripts/vendor.70e4fd8417d338e0fdad.js:2:1095385)
    at fl (https://zigbee2mqtt.z13.org/scripts/vendor.70e4fd8417d338e0fdad.js:2:1092372)
    at https://zigbee2mqtt.z13.org/scripts/vendor.70e4fd8417d338e0fdad.js:2:1042080
    at t.unstable_runWithPriority (https://zigbee2mqtt.z13.org/scripts/vendor.70e4fd8417d338e0fdad.js:2:1152260)
    at Ui (https://zigbee2mqtt.z13.org/scripts/vendor.70e4fd8417d338e0fdad.js:2:1041857)

**Comment by nurikk** [comment]
Thanks, I've added workaround for this case.


@Koenkk, hi! Here we have another case when devices has beed removed, but still present in a group

**Comment by Koenkk** [comment]
@DTTerastar could you share your data/database.db?

**Comment by DTTerastar** [comment]
Sorry, I've been migrating and messing with stuff so I don't have one that is like that anymore.  I totally moved to a hass setup w/ supervisor.  I was also having trouble w/ certain devices that I deleted.  They did all have dateCodes with binary junk in them tho

**Comment by nurikk** [comment]
> Sorry, I've been migrating and messing with stuff so I don't have one that is like that anymore. I totally moved to a hass setup w/ supervisor. I was also having trouble w/ certain devices that I deleted. They did all have dateCodes with binary junk in them tho

how did you delete them?

**Comment by DTTerastar** [comment]
I think it could remove them successfully.  But honestly I didn't look.  The gui did show them gone.

**Comment by nurikk** [comment]
This is solved in latest z2m dev
