### ISSUE TITLE
Got error: Cannot read property 'source' of undefined

### ISSUE THREAD

**Issue by iotinkognito** [nurikk/z2m-frontend#694]
DESCRIBE HERE WHAT HAPPENED AND WHAT YOU EXPECTED TO HAPPEN

**Current url**: http://homeassistant:8123/api/hassio_ingress/EV-OydLhjHj2TOVK0Nt8QhBCoaMHAK2q4dKUT1MDwH0/#/map
**Previous url**: http://homeassistant:8123/api/hassio_ingress/EV-OydLhjHj2TOVK0Nt8QhBCoaMHAK2q4dKUT1MDwH0/

**Error type**: TypeError
**Error message**: Cannot read property 'source' of undefined

TypeError: Cannot read property 'source' of undefined
    at SVGPathElement.l (http://homeassistant:8123/api/hassio_ingress/EV-OydLhjHj2TOVK0Nt8QhBCoaMHAK2q4dKUT1MDwH0/main.125c9bd8fa26692dd8b6.js:1:18171)
    at SVGPathElement.<anonymous> (http://homeassistant:8123/api/hassio_ingress/EV-OydLhjHj2TOVK0Nt8QhBCoaMHAK2q4dKUT1MDwH0/scripts/vendor.a0ef53a74e6d2443acda.js:2:681093)
    at se.each (http://homeassistant:8123/api/hassio_ingress/EV-OydLhjHj2TOVK0Nt8QhBCoaMHAK2q4dKUT1MDwH0/scripts/vendor.a0ef53a74e6d2443acda.js:2:678909)
    at se.s [as style] (http://homeassistant:8123/api/hassio_ingress/EV-OydLhjHj2TOVK0Nt8QhBCoaMHAK2q4dKUT1MDwH0/scripts/vendor.a0ef53a74e6d2443acda.js:2:681232)
    at http://homeassistant:8123/api/hassio_ingress/EV-OydLhjHj2TOVK0Nt8QhBCoaMHAK2q4dKUT1MDwH0/main.125c9bd8fa26692dd8b6.js:1:18252
    at Oe.updateNodes (http://homeassistant:8123/api/hassio_ingress/EV-OydLhjHj2TOVK0Nt8QhBCoaMHAK2q4dKUT1MDwH0/main.125c9bd8fa26692dd8b6.js:1:18373)
    at Oe.componentDidUpdate (http://homeassistant:8123/api/hassio_ingress/EV-OydLhjHj2TOVK0Nt8QhBCoaMHAK2q4dKUT1MDwH0/main.125c9bd8fa26692dd8b6.js:1:19362)
    at ds (http://homeassistant:8123/api/hassio_ingress/EV-OydLhjHj2TOVK0Nt8QhBCoaMHAK2q4dKUT1MDwH0/scripts/vendor.a0ef53a74e6d2443acda.js:2:1087409)
    at Il (http://homeassistant:8123/api/hassio_ingress/EV-OydLhjHj2TOVK0Nt8QhBCoaMHAK2q4dKUT1MDwH0/scripts/vendor.a0ef53a74e6d2443acda.js:2:1104160)
    at t.unstable_runWithPriority (http://homeassistant:8123/api/hassio_ingress/EV-OydLhjHj2TOVK0Nt8QhBCoaMHAK2q4dKUT1MDwH0/scripts/vendor.a0ef53a74e6d2443acda.js:2:1156698)

**Comment by iotinkognito** [comment]
[initialState.json.zip](https://github.com/nurikk/z2m-frontend/files/6874058/initialState.json.zip)

**Comment by nurikk** [comment]
Hello, can you update to the latest `z2m dev`, and try to reproduce the bug? If able to reproduce raise another ticket
