### ISSUE TITLE
Donate button not working

### ISSUE THREAD

**Issue by aletzi1** [nurikk/z2m-frontend#719]
### What happened?

Donate button not working. After clicking donate -button, it will say "Hello, you've found a bug. Congratulations!" 🗡️ 
![screenshot](https://user-images.githubusercontent.com/66028464/128335883-bed70bc8-eb7d-4c8d-9959-6daf1a94690d.JPG)
[initialState.json.zip](https://github.com/nurikk/z2m-frontend/files/6937918/initialState.json.zip)

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: https://aleksikinnunen.duckdns.org/api/hassio_ingress/_J5UZh9yf93Qvwrn1pMVmCS9BVWS5nljEdRQwgZlaYc/#/settings/donate
**Previous url**: https://aleksikinnunen.duckdns.org/45df7312_zigbee2mqtt


**Error type**: TypeError
**Error message**: donateText.map is not a function



TypeError: donateText.map is not a function
    at SettingsPage.renderDonate (https://aleksikinnunen.duckdns.org/api/hassio_ingress/_J5UZh9yf93Qvwrn1pMVmCS9BVWS5nljEdRQwgZlaYc/main.ceb75b6ba3052daf2d40.js:3358:24)
    at SettingsPage.renderSwitcher (https://aleksikinnunen.duckdns.org/api/hassio_ingress/_J5UZh9yf93Qvwrn1pMVmCS9BVWS5nljEdRQwgZlaYc/main.ceb75b6ba3052daf2d40.js:3247:29)
    at SettingsPage.render (https://aleksikinnunen.duckdns.org/api/hassio_ingress/_J5UZh9yf93Qvwrn1pMVmCS9BVWS5nljEdRQwgZlaYc/main.ceb75b6ba3052daf2d40.js:3232:93)
    at qi (https://aleksikinnunen.duckdns.org/api/hassio_ingress/_J5UZh9yf93Qvwrn1pMVmCS9BVWS5nljEdRQwgZlaYc/scripts/vendor.55fa8a7d53667a3e9c75.js:75478:188)
    at pi (https://aleksikinnunen.duckdns.org/api/hassio_ingress/_J5UZh9yf93Qvwrn1pMVmCS9BVWS5nljEdRQwgZlaYc/scripts/vendor.55fa8a7d53667a3e9c75.js:75477:173)
    at ck (https://aleksikinnunen.duckdns.org/api/hassio_ingress/_J5UZh9yf93Qvwrn1pMVmCS9BVWS5nljEdRQwgZlaYc/scripts/vendor.55fa8a7d53667a3e9c75.js:75560:427)
    at bk (https://aleksikinnunen.duckdns.org/api/hassio_ingress/_J5UZh9yf93Qvwrn1pMVmCS9BVWS5nljEdRQwgZlaYc/scripts/vendor.55fa8a7d53667a3e9c75.js:75541:347)
    at ak (https://aleksikinnunen.duckdns.org/api/hassio_ingress/_J5UZh9yf93Qvwrn1pMVmCS9BVWS5nljEdRQwgZlaYc/scripts/vendor.55fa8a7d53667a3e9c75.js:75541:278)
    at Tj (https://aleksikinnunen.duckdns.org/api/hassio_ingress/_J5UZh9yf93Qvwrn1pMVmCS9BVWS5nljEdRQwgZlaYc/scripts/vendor.55fa8a7d53667a3e9c75.js:75541:138)
    at Lj (https://aleksikinnunen.duckdns.org/api/hassio_ingress/_J5UZh9yf93Qvwrn1pMVmCS9BVWS5nljEdRQwgZlaYc/scripts/vendor.55fa8a7d53667a3e9c75.js:75534:163)
```

### initialState.zip

I will attach initialState.zip

**Comment by nurikk** [comment]
What a shame :) fixed, thanks :)
