### ISSUE TITLE
Donate bug

### ISSUE THREAD

**Issue by Tohelo101** [nurikk/z2m-frontend#797]
### What happened?

I was just looking settings and press donate this came 

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: http://homeassistant.local:8123/api/hassio_ingress/P4DQxdMUKD4Wc7hRlZ3t5agr1KZotylXmmTVmvt3PGc/#/settings/donate
**Previous url**: http://homeassistant.local:8123/45df7312_zigbee2mqtt


**Error type**: TypeError
**Error message**: donateText.map is not a function



TypeError: donateText.map is not a function
    at SettingsPage.renderDonate (http://homeassistant.local:8123/api/hassio_ingress/P4DQxdMUKD4Wc7hRlZ3t5agr1KZotylXmmTVmvt3PGc/main.ceb75b6ba3052daf2d40.js:3358:24)
    at SettingsPage.renderSwitcher (http://homeassistant.local:8123/api/hassio_ingress/P4DQxdMUKD4Wc7hRlZ3t5agr1KZotylXmmTVmvt3PGc/main.ceb75b6ba3052daf2d40.js:3247:29)
    at SettingsPage.render (http://homeassistant.local:8123/api/hassio_ingress/P4DQxdMUKD4Wc7hRlZ3t5agr1KZotylXmmTVmvt3PGc/main.ceb75b6ba3052daf2d40.js:3232:93)
    at qi (http://homeassistant.local:8123/api/hassio_ingress/P4DQxdMUKD4Wc7hRlZ3t5agr1KZotylXmmTVmvt3PGc/scripts/vendor.55fa8a7d53667a3e9c75.js:75478:188)
    at pi (http://homeassistant.local:8123/api/hassio_ingress/P4DQxdMUKD4Wc7hRlZ3t5agr1KZotylXmmTVmvt3PGc/scripts/vendor.55fa8a7d53667a3e9c75.js:75477:173)
    at ck (http://homeassistant.local:8123/api/hassio_ingress/P4DQxdMUKD4Wc7hRlZ3t5agr1KZotylXmmTVmvt3PGc/scripts/vendor.55fa8a7d53667a3e9c75.js:75560:427)
    at bk (http://homeassistant.local:8123/api/hassio_ingress/P4DQxdMUKD4Wc7hRlZ3t5agr1KZotylXmmTVmvt3PGc/scripts/vendor.55fa8a7d53667a3e9c75.js:75541:347)
    at ak (http://homeassistant.local:8123/api/hassio_ingress/P4DQxdMUKD4Wc7hRlZ3t5agr1KZotylXmmTVmvt3PGc/scripts/vendor.55fa8a7d53667a3e9c75.js:75541:278)
    at Tj (http://homeassistant.local:8123/api/hassio_ingress/P4DQxdMUKD4Wc7hRlZ3t5agr1KZotylXmmTVmvt3PGc/scripts/vendor.55fa8a7d53667a3e9c75.js:75541:138)
    at Lj (http://homeassistant.local:8123/api/hassio_ingress/P4DQxdMUKD4Wc7hRlZ3t5agr1KZotylXmmTVmvt3PGc/scripts/vendor.55fa8a7d53667a3e9c75.js:75534:163)
```

### Did you donwload state.json.zip?

I will attach state.json.zip

**Comment by Tohelo101** [comment]
[initialState.json.zip](https://github.com/nurikk/z2m-frontend/files/7085091/initialState.json.zip)

**Comment by nurikk** [comment]
fixed, please update to the latest version
