### ISSUE TITLE
Got error: t.map is not a function Livolo switches

### ISSUE THREAD

**Issue by wajo666** [nurikk/z2m-frontend#816]
DESCRIBE HERE WHAT HAPPENED AND WHAT YOU EXPECTED TO HAPPEN

**Current url**: http://192.168.1.11:8099/#/settings/donate
**Previous url**: 

**Error type**: TypeError
**Error message**: t.map is not a function

TypeError: t.map is not a function
    at Kn.renderDonate (http://192.168.1.11:8099/main.ba64bda627ba8e632abe.js:1:77373)
    at Kn.renderSwitcher (http://192.168.1.11:8099/main.ba64bda627ba8e632abe.js:1:73070)
    at Kn.render (http://192.168.1.11:8099/main.ba64bda627ba8e632abe.js:1:72791)
    at Ua (http://192.168.1.11:8099/scripts/vendor.70e4fd8417d338e0fdad.js:2:1068729)
    at Ba (http://192.168.1.11:8099/scripts/vendor.70e4fd8417d338e0fdad.js:2:1068528)
    at Us (http://192.168.1.11:8099/scripts/vendor.70e4fd8417d338e0fdad.js:2:1109443)
    at El (http://192.168.1.11:8099/scripts/vendor.70e4fd8417d338e0fdad.js:2:1095594)
    at _l (http://192.168.1.11:8099/scripts/vendor.70e4fd8417d338e0fdad.js:2:1095522)
    at Sl (http://192.168.1.11:8099/scripts/vendor.70e4fd8417d338e0fdad.js:2:1095385)
    at fl (http://192.168.1.11:8099/scripts/vendor.70e4fd8417d338e0fdad.js:2:1092372)

**Comment by nurikk** [comment]
fixed, please update to the latest version
