### ISSUE TITLE
Got error: Cannot read properties of undefined (reading 'ieee_address')

### ISSUE THREAD

**Issue by Tamadite** [nurikk/z2m-frontend#821]
DESCRIBE HERE WHAT HAPPENED AND WHAT YOU EXPECTED TO HAPPEN
I created a group with a remote and four bulbs. The configuration has been working in Home Assistant/zigbee2mqtt for long time. Somehow the four bulbs lost their configuration (not manageable by the remote nor by Home Assistant) and I noticed that they disappeared from the zigbee2mqtt main screen in Home Assistant. The remote seems to be left. I clicked on "Groups" under the zigbee2mqtt menu to find the group configuration and I got this error.

**Current url**: http://hassio.home.local:8123/api/hassio_ingress/VMcywLRJ9JKeRCwVhUlxOHpnpXzL-TLMH4KD02es_Bs/#/groups
**Previous url**: http://hassio.home.local:8123/7ad98f9c_zigbee2mqtt
zigbee2mqtt: Current version: 1.18.1-1
OS ver: 6.2
HA Core ver: core-2021.8.7

**Error type**: TypeError
**Error message**: Cannot read properties of undefined (reading 'ieee_address')

![image](https://user-images.githubusercontent.com/30261982/132406511-2ed7b255-b53f-4dc2-81e0-569afbaa32b5.png)

[state.json.txt](https://github.com/nurikk/z2m-frontend/files/7124175/state.json.txt)

TypeError: Cannot read properties of undefined (reading 'ieee_address')
    at t.render (http://hassio.home.local:8123/api/hassio_ingress/VMcywLRJ9JKeRCwVhUlxOHpnpXzL-TLMH4KD02es_Bs/main.7c791b396724cd5681c7.js:1:99181)
    at Ha (http://hassio.home.local:8123/api/hassio_ingress/VMcywLRJ9JKeRCwVhUlxOHpnpXzL-TLMH4KD02es_Bs/scripts/vendor.d2ddf849cc03b8f1b4ad.js:2:918059)
    at za (http://hassio.home.local:8123/api/hassio_ingress/VMcywLRJ9JKeRCwVhUlxOHpnpXzL-TLMH4KD02es_Bs/scripts/vendor.d2ddf849cc03b8f1b4ad.js:2:917858)
    at Hs (http://hassio.home.local:8123/api/hassio_ingress/VMcywLRJ9JKeRCwVhUlxOHpnpXzL-TLMH4KD02es_Bs/scripts/vendor.d2ddf849cc03b8f1b4ad.js:2:958773)
    at _l (http://hassio.home.local:8123/api/hassio_ingress/VMcywLRJ9JKeRCwVhUlxOHpnpXzL-TLMH4KD02es_Bs/scripts/vendor.d2ddf849cc03b8f1b4ad.js:2:944924)
    at xl (http://hassio.home.local:8123/api/hassio_ingress/VMcywLRJ9JKeRCwVhUlxOHpnpXzL-TLMH4KD02es_Bs/scripts/vendor.d2ddf849cc03b8f1b4ad.js:2:944852)
    at Sl (http://hassio.home.local:8123/api/hassio_ingress/VMcywLRJ9JKeRCwVhUlxOHpnpXzL-TLMH4KD02es_Bs/scripts/vendor.d2ddf849cc03b8f1b4ad.js:2:944715)
    at fl (http://hassio.home.local:8123/api/hassio_ingress/VMcywLRJ9JKeRCwVhUlxOHpnpXzL-TLMH4KD02es_Bs/scripts/vendor.d2ddf849cc03b8f1b4ad.js:2:941702)
    at http://hassio.home.local:8123/api/hassio_ingress/VMcywLRJ9JKeRCwVhUlxOHpnpXzL-TLMH4KD02es_Bs/scripts/vendor.d2ddf849cc03b8f1b4ad.js:2:891410
    at t.unstable_runWithPriority (http://hassio.home.local:8123/api/hassio_ingress/VMcywLRJ9JKeRCwVhUlxOHpnpXzL-TLMH4KD02es_Bs/scripts/vendor.d2ddf849cc03b8f1b4ad.js:2:994763)

**Comment by nurikk** [comment]
You’re using way outdated version, consider upgrading to the latest release

**Comment by Tamadite** [comment]
> You’re using way outdated version, consider upgrading to the latest release

I guess you refer to Home Assistant latest version core-2021.9.4 because concerning zigbee2mqtt I'm on the latest one available on the HA Supervisor (1.18.1-1). Please confirm.

**Comment by nurikk** [comment]
Wakeup Neo :) 1.21.0 is the latest one

https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.21.1
