### ISSUE TITLE
Zigbee2MQTT crash

### ISSUE THREAD

**Issue by andrewigali** [nurikk/z2m-frontend#835]
### What happened?

I just clicked on one of the routers on Map site.

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: https://igalihomeassistant.duckdns.org:8123/api/hassio_ingress/Qu4JaDxICHu5Kx5IiKDWg3y-6vOko1lNYvxA8fc-1Vo/#/map
**Previous url**: https://igalihomeassistant.duckdns.org:8123/45df7312_zigbee2mqtt


**Error type**: TypeError
**Error message**: Cannot read properties of undefined (reading 'source')



TypeError: Cannot read properties of undefined (reading 'source')
    at SVGPathElement.computeOpacity (https://igalihomeassistant.duckdns.org:8123/api/hassio_ingress/Qu4JaDxICHu5Kx5IiKDWg3y-6vOko1lNYvxA8fc-1Vo/main.00c7a6f56d7119e5fb75.js:1022:38)
    at SVGPathElement.<anonymous> (https://igalihomeassistant.duckdns.org:8123/api/hassio_ingress/Qu4JaDxICHu5Kx5IiKDWg3y-6vOko1lNYvxA8fc-1Vo/scripts/vendor.00cfd74d45f5998227f4.js:83924:19)
    at Selection.each (https://igalihomeassistant.duckdns.org:8123/api/hassio_ingress/Qu4JaDxICHu5Kx5IiKDWg3y-6vOko1lNYvxA8fc-1Vo/scripts/vendor.00cfd74d45f5998227f4.js:83352:37)
    at Selection.__WEBPACK_DEFAULT_EXPORT__ [as style] (https://igalihomeassistant.duckdns.org:8123/api/hassio_ingress/Qu4JaDxICHu5Kx5IiKDWg3y-6vOko1lNYvxA8fc-1Vo/scripts/vendor.00cfd74d45f5998227f4.js:83932:14)
    at processHighlights (https://igalihomeassistant.duckdns.org:8123/api/hassio_ingress/Qu4JaDxICHu5Kx5IiKDWg3y-6vOko1lNYvxA8fc-1Vo/main.00c7a6f56d7119e5fb75.js:1025:14)
    at MapComponent.updateNodes (https://igalihomeassistant.duckdns.org:8123/api/hassio_ingress/Qu4JaDxICHu5Kx5IiKDWg3y-6vOko1lNYvxA8fc-1Vo/main.00c7a6f56d7119e5fb75.js:1067:13)
    at MapComponent.componentDidUpdate (https://igalihomeassistant.duckdns.org:8123/api/hassio_ingress/Qu4JaDxICHu5Kx5IiKDWg3y-6vOko1lNYvxA8fc-1Vo/main.00c7a6f56d7119e5fb75.js:1110:14)
    at Yi (https://igalihomeassistant.duckdns.org:8123/api/hassio_ingress/Qu4JaDxICHu5Kx5IiKDWg3y-6vOko1lNYvxA8fc-1Vo/scripts/vendor.00cfd74d45f5998227f4.js:70107:502)
    at dk (https://igalihomeassistant.duckdns.org:8123/api/hassio_ingress/Qu4JaDxICHu5Kx5IiKDWg3y-6vOko1lNYvxA8fc-1Vo/scripts/vendor.00cfd74d45f5998227f4.js:70147:160)
    at exports.unstable_runWithPriority (https://igalihomeassistant.duckdns.org:8123/api/hassio_ingress/Qu4JaDxICHu5Kx5IiKDWg3y-6vOko1lNYvxA8fc-1Vo/scripts/vendor.00cfd74d45f5998227f4.js:73321:343)
```

### Did you donwload state.json.zip?

I will attach state.json.zip

**Comment by nurikk** [comment]
fixed
