### ISSUE TITLE
Error on click at dashboard

### ISSUE THREAD

**Issue by andregat** [nurikk/z2m-frontend#931]
### What happened?

Some of my devices weren't responding, so I was trying to investigate on zigbee2mqtt tools when I got the page error.

[initialState.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/7318636/initialState.json.zip)
![Screenshot 2021-10-10 205511](https://user-images.githubusercontent.com/775836/136717388-0b178aa6-d821-4b95-be90-a19d6869b566.jpg)

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: http://homeassistant.local:8123/api/hassio_ingress/kRbXxzu_HsMKBKtYPM85NXfVKLHLiFqJkIJGT5v3GC8/#/settings/donate
**Previous url**: http://homeassistant.local:8123/45df7312_zigbee2mqtt/dashboard


**Error type**: TypeError
**Error message**: res.match is not a function



TypeError: res.match is not a function
    at Translator.extendTranslation (http://homeassistant.local:8123/api/hassio_ingress/kRbXxzu_HsMKBKtYPM85NXfVKLHLiFqJkIJGT5v3GC8/scripts/vendor.a4e132b2b3c8436dc2af.js:53175:24)
    at Translator.translate (http://homeassistant.local:8123/api/hassio_ingress/kRbXxzu_HsMKBKtYPM85NXfVKLHLiFqJkIJGT5v3GC8/scripts/vendor.a4e132b2b3c8436dc2af.js:53151:20)
    at I18n.t (http://homeassistant.local:8123/api/hassio_ingress/kRbXxzu_HsMKBKtYPM85NXfVKLHLiFqJkIJGT5v3GC8/scripts/vendor.a4e132b2b3c8436dc2af.js:54694:80)
    at fixedT (http://homeassistant.local:8123/api/hassio_ingress/kRbXxzu_HsMKBKtYPM85NXfVKLHLiFqJkIJGT5v3GC8/scripts/vendor.a4e132b2b3c8436dc2af.js:54676:23)
    at SettingsPage.renderDonate (http://homeassistant.local:8123/api/hassio_ingress/kRbXxzu_HsMKBKtYPM85NXfVKLHLiFqJkIJGT5v3GC8/main.08840951372a374db68a.js:3608:28)
    at SettingsPage.renderSwitcher (http://homeassistant.local:8123/api/hassio_ingress/kRbXxzu_HsMKBKtYPM85NXfVKLHLiFqJkIJGT5v3GC8/main.08840951372a374db68a.js:3499:29)
    at SettingsPage.render (http://homeassistant.local:8123/api/hassio_ingress/kRbXxzu_HsMKBKtYPM85NXfVKLHLiFqJkIJGT5v3GC8/main.08840951372a374db68a.js:3484:93)
    at qi (http://homeassistant.local:8123/api/hassio_ingress/kRbXxzu_HsMKBKtYPM85NXfVKLHLiFqJkIJGT5v3GC8/scripts/vendor.a4e132b2b3c8436dc2af.js:70159:188)
    at pi (http://homeassistant.local:8123/api/hassio_ingress/kRbXxzu_HsMKBKtYPM85NXfVKLHLiFqJkIJGT5v3GC8/scripts/vendor.a4e132b2b3c8436dc2af.js:70158:173)
    at ck (http://homeassistant.local:8123/api/hassio_ingress/kRbXxzu_HsMKBKtYPM85NXfVKLHLiFqJkIJGT5v3GC8/scripts/vendor.a4e132b2b3c8436dc2af.js:70241:427)
```

### Did you donwload state.json.zip?

I will attach state.json.zip

**Comment by nurikk** [comment]
Thanks, fixed
