### ISSUE TITLE
Web Interface Crashes

### ISSUE THREAD

**Issue by Highvolt** [nurikk/z2m-frontend#966]
### What happened?

When I open the web interface of zigbee2mqtt it crashes almost imediatly.

[initialState.json (1).zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/7399528/initialState.json.1.zip)

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: https://mariajose.pedroborges.me/api/hassio_ingress/fFn2dhZYqPGBOaaZwcuEZQ5daerH-WkNYVc3wKKp5Mc/#/
**Previous url**: https://mariajose.pedroborges.me/hassio/addon/45df7312_zigbee2mqtt/info


**Error type**: Error
**Error message**: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B0%2C%201%2C%202%2C%203%2C%204%2C%205%2C%206%2C%207%2C%208%2C%209%2C%2010%2C%2011%2C%2012%2C%2013%2C%2014%2C%2015%2C%2016%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.



Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B0%2C%201%2C%202%2C%203%2C%204%2C%205%2C%206%2C%207%2C%208%2C%209%2C%2010%2C%2011%2C%2012%2C%2013%2C%2014%2C%2015%2C%2016%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Rg (https://mariajose.pedroborges.me/api/hassio_ingress/fFn2dhZYqPGBOaaZwcuEZQ5daerH-WkNYVc3wKKp5Mc/scripts/vendor.a4e132b2b3c8436dc2af.js:70112:47)
    at A (https://mariajose.pedroborges.me/api/hassio_ingress/fFn2dhZYqPGBOaaZwcuEZQ5daerH-WkNYVc3wKKp5Mc/scripts/vendor.a4e132b2b3c8436dc2af.js:70116:29)
    at x (https://mariajose.pedroborges.me/api/hassio_ingress/fFn2dhZYqPGBOaaZwcuEZQ5daerH-WkNYVc3wKKp5Mc/scripts/vendor.a4e132b2b3c8436dc2af.js:70118:132)
    at https://mariajose.pedroborges.me/api/hassio_ingress/fFn2dhZYqPGBOaaZwcuEZQ5daerH-WkNYVc3wKKp5Mc/scripts/vendor.a4e132b2b3c8436dc2af.js:70122:224
    at fi (https://mariajose.pedroborges.me/api/hassio_ingress/fFn2dhZYqPGBOaaZwcuEZQ5daerH-WkNYVc3wKKp5Mc/scripts/vendor.a4e132b2b3c8436dc2af.js:70148:171)
    at ck (https://mariajose.pedroborges.me/api/hassio_ingress/fFn2dhZYqPGBOaaZwcuEZQ5daerH-WkNYVc3wKKp5Mc/scripts/vendor.a4e132b2b3c8436dc2af.js:70243:134)
    at bk (https://mariajose.pedroborges.me/api/hassio_ingress/fFn2dhZYqPGBOaaZwcuEZQ5daerH-WkNYVc3wKKp5Mc/scripts/vendor.a4e132b2b3c8436dc2af.js:70222:347)
    at ak (https://mariajose.pedroborges.me/api/hassio_ingress/fFn2dhZYqPGBOaaZwcuEZQ5daerH-WkNYVc3wKKp5Mc/scripts/vendor.a4e132b2b3c8436dc2af.js:70222:278)
    at Tj (https://mariajose.pedroborges.me/api/hassio_ingress/fFn2dhZYqPGBOaaZwcuEZQ5daerH-WkNYVc3wKKp5Mc/scripts/vendor.a4e132b2b3c8436dc2af.js:70222:138)
    at Lj (https://mariajose.pedroborges.me/api/hassio_ingress/fFn2dhZYqPGBOaaZwcuEZQ5daerH-WkNYVc3wKKp5Mc/scripts/vendor.a4e132b2b3c8436dc2af.js:70215:163)
```

### Did you donwload state.json.zip?

I will attach state.json.zip

**Comment by nurikk** [comment]
Hello, your device `0x50325ffffe4047ad` publishes mallformed data into state, `battery` value has to be a `number` or `undefined`, your value is object. Apparently you're tinkering with external converter and doing something very wrong


<img width="202" alt="Screenshot 2021-10-23 at 11 54 49 AM" src="https://user-images.githubusercontent.com/1525421/138541527-e3a36853-b081-44c5-8d0c-57aa1995056d.png">
