### ISSUE TITLE
Error when opening device map

### ISSUE THREAD

**Issue by sthausmann** [nurikk/z2m-frontend#970]
### What happened?

While tinkering with Automations, all my lights and switches lost connection.
I opened the map frature in zigbee2mqtt, when this happened
[initialState.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/7406000/initialState.json.zip)
![image](https://user-images.githubusercontent.com/40239959/138607011-2f14dd14-c878-40d6-a71f-01047c57ec31.png)

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: http://mcp:8123/api/hassio_ingress/agq7_LTdjPOzs41H1xKPvcnptVO0EBsqgwdKgYB1KqU/#/map
**Previous url**: http://mcp:8123/45df7312_zigbee2mqtt_edge


**Error type**: TypeError
**Error message**: Cannot read properties of undefined (reading 'interviewing')



TypeError: Cannot read properties of undefined (reading 'interviewing')
    at DeviceImage (http://mcp:8123/api/hassio_ingress/agq7_LTdjPOzs41H1xKPvcnptVO0EBsqgwdKgYB1KqU/main.f3d0e1cfdda35d266b34.js:205:41)
    at Ch (http://mcp:8123/api/hassio_ingress/agq7_LTdjPOzs41H1xKPvcnptVO0EBsqgwdKgYB1KqU/scripts/vendor.ea7989ca51c5d50873f3.js:70204:137)
    at ck (http://mcp:8123/api/hassio_ingress/agq7_LTdjPOzs41H1xKPvcnptVO0EBsqgwdKgYB1KqU/scripts/vendor.ea7989ca51c5d50873f3.js:70314:460)
    at bk (http://mcp:8123/api/hassio_ingress/agq7_LTdjPOzs41H1xKPvcnptVO0EBsqgwdKgYB1KqU/scripts/vendor.ea7989ca51c5d50873f3.js:70297:347)
    at ak (http://mcp:8123/api/hassio_ingress/agq7_LTdjPOzs41H1xKPvcnptVO0EBsqgwdKgYB1KqU/scripts/vendor.ea7989ca51c5d50873f3.js:70297:278)
    at Tj (http://mcp:8123/api/hassio_ingress/agq7_LTdjPOzs41H1xKPvcnptVO0EBsqgwdKgYB1KqU/scripts/vendor.ea7989ca51c5d50873f3.js:70297:138)
    at Lj (http://mcp:8123/api/hassio_ingress/agq7_LTdjPOzs41H1xKPvcnptVO0EBsqgwdKgYB1KqU/scripts/vendor.ea7989ca51c5d50873f3.js:70290:163)
    at http://mcp:8123/api/hassio_ingress/agq7_LTdjPOzs41H1xKPvcnptVO0EBsqgwdKgYB1KqU/scripts/vendor.ea7989ca51c5d50873f3.js:70170:115
    at exports.unstable_runWithPriority (http://mcp:8123/api/hassio_ingress/agq7_LTdjPOzs41H1xKPvcnptVO0EBsqgwdKgYB1KqU/scripts/vendor.ea7989ca51c5d50873f3.js:73463:343)
    at gg (http://mcp:8123/api/hassio_ingress/agq7_LTdjPOzs41H1xKPvcnptVO0EBsqgwdKgYB1KqU/scripts/vendor.ea7989ca51c5d50873f3.js:70169:325)
```

### Did you donwload state.json.zip?

I will attach state.json.zip

**Comment by frankivo** [comment]
[initialState.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/7416565/initialState.json.zip)

Looks I hit the same thing

**Comment by nurikk** [comment]
Hi! @Koenkk, here we have case when device has been removed (0x5c0272fffe84a19c Staircase Groundfloor Light), but still present it map response, can you have a look?

**Comment by nurikk** [comment]
> [initialState.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/7416565/initialState.json.zip)
> 
> Looks I hit the same thing

Hi, you're using quite outdated version, try to update to the latest `dev`

**Comment by frankivo** [comment]
> 
> 
> > [initialState.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/7416565/initialState.json.zip)
> > Looks I hit the same thing
> 
> Hi, you're using quite outdated version, try to update to the latest `dev`

I was on latest-dev, now on latest. Seems fixed :)

**Comment by nurikk** [comment]
> > > [initialState.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/7416565/initialState.json.zip)
> > > Looks I hit the same thing
> > 
> > 
> > Hi, you're using quite outdated version, try to update to the latest `dev`
> 
> I was on latest-dev, now on latest. Seems fixed :)

you were using `1.17.0-dev commit: 258938e`, you might tracking no origin branch
