### ISSUE TITLE
Error when adding IKEA bulb

### ISSUE THREAD

**Issue by magnusoverli** [nurikk/z2m-frontend#981]
### What happened?

During interview process of IKEA LED 1837R5 this error came up:

[initialState.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/7420200/initialState.json.zip)

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: https://z2m.<redacted>.<redacted>.org/#/
**Previous url**: 


**Error type**: TypeError
**Error message**: Cannot read properties of undefined (reading 'toLowerCase')



TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at PowerSource (https://z2m.<redacted>.<redacted>.org/main.9d873c333b70084db7e9.js:1350:33)
    at Ch (https://z2m.<redacted>.<redacted>.org/scripts/vendor.ea7989ca51c5d50873f3.js:70204:137)
    at ck (https://z2m.<redacted>.<redacted>.org/scripts/vendor.ea7989ca51c5d50873f3.js:70314:460)
    at bk (https://z2m.<redacted>.<redacted>.org/scripts/vendor.ea7989ca51c5d50873f3.js:70297:347)
    at ak (https://z2m.<redacted>.<redacted>.org/scripts/vendor.ea7989ca51c5d50873f3.js:70297:278)
    at Tj (https://z2m.<redacted>.<redacted>.org/scripts/vendor.ea7989ca51c5d50873f3.js:70297:138)
    at Lj (https://z2m.<redacted>.<redacted>.org/scripts/vendor.ea7989ca51c5d50873f3.js:70290:163)
    at https://z2m.<redacted>.<redacted>.org/scripts/vendor.ea7989ca51c5d50873f3.js:70170:115
    at exports.unstable_runWithPriority (https://z2m.<redacted>.<redacted>.org/scripts/vendor.ea7989ca51c5d50873f3.js:73463:343)
    at gg (https://z2m.<redacted>.<redacted>.org/scripts/vendor.ea7989ca51c5d50873f3.js:70169:325)
```

### Did you donwload state.json.zip?

I will attach state.json.zip

**Comment by nurikk** [comment]
Fixed, thanks
